import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration implements MigrationInterface {
    name = 'Migration1736267629059'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS auth`);
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS storage`);
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS meta`);
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS messages`);

        await queryRunner.query(`CREATE TABLE "meta"."stats" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "metric" character varying(255) NOT NULL, "region" character varying(255) NOT NULL, "value" integer NOT NULL, "time" TIMESTAMP WITH TIME ZONE, "period" character varying(4) NOT NULL, CONSTRAINT "PK_899834554a81df3dd44e6004c1e" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE INDEX "_key_metric_period_time" ON "meta"."stats" ("metric", "period", "time") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "_key_period_time" ON "meta"."stats" ("period", "time") `);
        await queryRunner.query(`CREATE INDEX "_key_time" ON "meta"."stats" ("time") `);
        await queryRunner.query(`CREATE TABLE "meta"."databases" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "name" character varying(256) NOT NULL, "enabled" boolean DEFAULT true, "search" character varying(16384), CONSTRAINT "PK_a4f3afe454ad5428d0b400f708f" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4f56ebcf8cba238205136aa00f" ON "meta"."databases" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_76768c4da0c82f87ca31cf732b" ON "meta"."databases" ("search") `);
        await queryRunner.query(`CREATE TABLE "auth"."tokens" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "userId" integer, "type" integer NOT NULL, "secret" character varying(512), "expire" TIMESTAMP, "userAgent" character varying(16384), "ip" character varying(45), "user_$id" character varying, CONSTRAINT "PK_b6a486db9ee76782688fb5b96d9" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c26f11a8b165c263af3ad865f" ON "auth"."tokens" ("userId", "user_$id") `);
        await queryRunner.query(`CREATE TABLE "auth"."authenticators" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "userId" integer, "type" character varying(255), "verified" boolean DEFAULT false, "data" text, "user_$id" character varying, CONSTRAINT "PK_abf143ba05a8dc08c7a11aca370" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE TABLE "auth"."challenges" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "userId" integer, "type" character varying(255), "token" character varying(512), "code" character varying(512), "expire" TIMESTAMP WITH TIME ZONE, "user_$id" character varying, CONSTRAINT "PK_010665a2e9a009704ba91d009e1" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_id" ON "auth"."challenges" ("userId", "user_$id") `);
        await queryRunner.query(`CREATE TABLE "auth"."sessions" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "userId" integer, "provider" character varying(128), "providerUid" character varying(2048), "providerAccessToken" character varying(16384), "providerAccessTokenExpiry" TIMESTAMP WITH TIME ZONE, "providerRefreshToken" character varying(16384), "secret" character varying(512), "userAgent" character varying(16384), "ip" character varying(45), "countryCode" character varying(2), "osCode" character varying(256), "osName" character varying(256), "osVersion" character varying(256), "clientType" character varying(256), "clientCode" character varying(256), "clientName" character varying(256), "clientVersion" character varying(256), "clientEngine" character varying(256), "clientEngineVersion" character varying(256), "deviceName" character varying(256), "deviceBrand" character varying(256), "deviceModel" character varying(256), "factors" text, "expire" TIMESTAMP WITH TIME ZONE NOT NULL, "mfaUpdatedAt" TIMESTAMP WITH TIME ZONE, "user_$id" character varying, CONSTRAINT "PK_aeffb29358c4053ea79da705f92" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE TABLE "auth"."teams" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "name" character varying(128), "total" integer, "search" character varying(16384), "prefs" json DEFAULT '{}', CONSTRAINT "PK_9c38492631ac6dad4d76ea36584" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_48c0c32e6247a2de155baeaf98" ON "auth"."teams" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6ada59c75ff2761704cccebd8" ON "auth"."teams" ("total") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4ab53f394a0ccc38437919456" ON "auth"."teams" ("search") `);
        await queryRunner.query(`CREATE TABLE "auth"."memberships" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "userId" integer, "teamId" integer, "roles" character varying(128) array, "invited" TIMESTAMP WITH TIME ZONE, "joined" TIMESTAMP WITH TIME ZONE, "confirm" boolean, "secret" character varying(256), "search" character varying(16384), "user_$id" character varying, "team_$id" character varying, CONSTRAINT "PK_8861928175ba0999a8dc753fc9c" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE INDEX "confirm_index" ON "auth"."memberships" ("confirm") `);
        await queryRunner.query(`CREATE INDEX "joined_index" ON "auth"."memberships" ("joined") `);
        await queryRunner.query(`CREATE INDEX "invited_index" ON "auth"."memberships" ("invited") `);
        await queryRunner.query(`CREATE INDEX "teamId_index" ON "auth"."memberships" ("teamId") `);
        await queryRunner.query(`CREATE INDEX "userId_index" ON "auth"."memberships" ("userId") `);
        await queryRunner.query(`CREATE INDEX "search_index" ON "auth"."memberships" ("search") `);
        await queryRunner.query(`CREATE INDEX "team_index" ON "auth"."memberships" ("teamId", "team_$id") `);
        await queryRunner.query(`CREATE INDEX "user_index" ON "auth"."memberships" ("userId", "user_$id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_85f35eea70810a5e1fd14fbce0" ON "auth"."memberships" ("teamId", "team_$id", "userId", "user_$id") `);
        await queryRunner.query(`CREATE TABLE "messages"."topics" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "name" character varying(128) NOT NULL, "subscribe" character varying(128) array, "emailTotal" integer DEFAULT '0', "smsTotal" integer DEFAULT '0', "pushTotal" integer DEFAULT '0', "search" character varying(16384) DEFAULT '', CONSTRAINT "PK_8da93d4008fbccd9f503d434977" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1304b1c61016e63f60cd147ce6" ON "messages"."topics" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9a92751714b0cd99bcca9f18b" ON "messages"."topics" ("search") `);
        await queryRunner.query(`CREATE TABLE "messages"."targets" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "userId" integer NOT NULL, "sessionId" character varying(255), "session" character varying(255), "providerType" character varying(255) NOT NULL, "providerId" character varying(255), "providerInternalId" character varying(255), "identifier" character varying(255) NOT NULL, "name" character varying(255), "expired" boolean DEFAULT false, "user_$id" character varying, CONSTRAINT "PK_563a43f869ca79e0cd0b4733ea8" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE TABLE "auth"."users" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "name" character varying(256), "email" character varying(320), "phone" character varying(16), "status" boolean, "labels" character varying(128) array, "passwordHistory" character varying(16384) array, "password" character varying(16384), "hash" character varying(256), "hashOptions" json, "passwordUpdate" TIMESTAMP, "prefs" json, "registration" TIMESTAMP, "emailVerification" boolean, "phoneVerification" boolean, "reset" boolean, "mfa" boolean, "mfaRecoveryCodes" character varying(256) array, "search" character varying(16384), "accessedAt" TIMESTAMP, CONSTRAINT "PK_3b9fd93fa9b6c22e850d5f3f0d7" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ACCESSED_AT" ON "auth"."users" ("accessedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_SEARCH" ON "auth"."users" ("search") `);
        await queryRunner.query(`CREATE INDEX "IDX_PHONE_VERIFICATION" ON "auth"."users" ("phoneVerification") `);
        await queryRunner.query(`CREATE INDEX "IDX_EMAIL_VERIFICATION" ON "auth"."users" ("emailVerification") `);
        await queryRunner.query(`CREATE INDEX "IDX_REGISTRATION" ON "auth"."users" ("registration") `);
        await queryRunner.query(`CREATE INDEX "IDX_PASSWORD_UPDATE" ON "auth"."users" ("passwordUpdate") `);
        await queryRunner.query(`CREATE INDEX "IDX_STATUS" ON "auth"."users" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_PHONE" ON "auth"."users" ("phone") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_EMAIL" ON "auth"."users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_NAME" ON "auth"."users" ("name") `);
        await queryRunner.query(`CREATE TABLE "storage"."buckets" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "enabled" boolean NOT NULL DEFAULT true, "name" character varying(128) NOT NULL, "fileSecurity" boolean NOT NULL DEFAULT false, "maximumFileSize" integer NOT NULL, "allowedFileExtensions" text NOT NULL, "compression" character varying(10) NOT NULL, "encryption" boolean NOT NULL DEFAULT true, "antivirus" boolean NOT NULL DEFAULT true, "search" character varying(16384), CONSTRAINT "PK_11e0973eb9758f5cd4c88ed8156" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE TABLE "storage"."files" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "bucketId" integer NOT NULL, "name" character varying(2048) NOT NULL, "path" character varying(2048) NOT NULL, "signature" character varying(2048) NOT NULL, "mimeType" character varying(255) NOT NULL, "metadata" character varying(75000) NOT NULL, "sizeOriginal" integer NOT NULL, "sizeActual" integer NOT NULL, "algorithm" character varying(255) NOT NULL, "comment" character varying(2048) NOT NULL, "openSSLVersion" character varying(64) NOT NULL, "openSSLCipher" character varying(64) NOT NULL, "openSSLTag" character varying(2048) NOT NULL, "openSSLIV" character varying(2048) NOT NULL, "chunksTotal" integer NOT NULL, "chunksUploaded" integer NOT NULL, "search" character varying(16384), "bucket_$id" character varying, CONSTRAINT "PK_b745b01fca9bd6ac0fe7e940bd0" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_03457cb4a0bd785d24201481f6" ON "storage"."files" ("bucketId") `);
        await queryRunner.query(`CREATE INDEX "IDX_332d10755187ac3c580e21fbc0" ON "storage"."files" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_aacdd3a68ed158c5b526d67276" ON "storage"."files" ("signature") `);
        await queryRunner.query(`CREATE INDEX "IDX_389d4090f38da709582e7e3a95" ON "storage"."files" ("mimeType") `);
        await queryRunner.query(`CREATE INDEX "IDX_a1d014cb180d27ab17fc21be50" ON "storage"."files" ("sizeOriginal") `);
        await queryRunner.query(`CREATE INDEX "IDX_d8e7903f3a8a0a28a49f6b4886" ON "storage"."files" ("chunksTotal") `);
        await queryRunner.query(`CREATE INDEX "IDX_bfced34fec53fd4205673bec3f" ON "storage"."files" ("chunksUploaded") `);
        await queryRunner.query(`CREATE INDEX "IDX_9cb7d3810278adbffd4230ce68" ON "storage"."files" ("search") `);
        await queryRunner.query(`CREATE TABLE "messages"."subscribers" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "targetId" character varying(128) NOT NULL, "targetInternalId" character varying(128) NOT NULL, "userId" character varying(128) NOT NULL, "userInternalId" character varying(128) NOT NULL, "topicId" character varying(128) NOT NULL, "topicInternalId" character varying(128) NOT NULL, "providerType" character varying(128) NOT NULL, "search" character varying(16384) DEFAULT '', CONSTRAINT "PK_b49ce0407397e212ac33dd638b1" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1198809f29d22accb0143684ff" ON "messages"."subscribers" ("targetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_64f26a3234a4bac78f6b6e9523" ON "messages"."subscribers" ("targetInternalId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e82da94a504e2d6dff5c9f393" ON "messages"."subscribers" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b5f276933ed75028216a4a843" ON "messages"."subscribers" ("userInternalId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d966300036db0e1ac00fa51c32" ON "messages"."subscribers" ("topicId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd461838f998443c5441989db5" ON "messages"."subscribers" ("topicInternalId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6fef292713b917a8e5f41bbba9" ON "messages"."subscribers" ("search") `);
        await queryRunner.query(`CREATE TABLE "messages"."messages" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "providerType" character varying(128) NOT NULL, "status" character varying(128) NOT NULL DEFAULT 'processing', "data" text NOT NULL, "topics" character varying(21845) array DEFAULT '{}', "users" character varying(21845) array DEFAULT '{}', "targets" character varying(21845) array DEFAULT '{}', "scheduledAt" TIMESTAMP, "scheduleInternalId" character varying(128), "scheduleId" character varying(128), "deliveredAt" TIMESTAMP, "deliveryErrors" text array, "deliveredTotal" integer DEFAULT '0', "search" character varying(16384) DEFAULT '', CONSTRAINT "PK_f61ecb5cef1799f6735da4d8d95" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_35000359daf153b15b27ee21e2" ON "messages"."messages" ("providerType") `);
        await queryRunner.query(`CREATE INDEX "IDX_de1963a30b933e2c55054a21ea" ON "messages"."messages" ("search") `);
        await queryRunner.query(`CREATE INDEX "idx_schedule_id" ON "messages"."messages" ("scheduleId") `);
        await queryRunner.query(`CREATE INDEX "idx_schedule_internal_id" ON "messages"."messages" ("scheduleInternalId") `);
        await queryRunner.query(`CREATE INDEX "idx_scheduled_at" ON "messages"."messages" ("scheduledAt") `);
        await queryRunner.query(`CREATE INDEX "idx_status" ON "messages"."messages" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_provider_type" ON "messages"."messages" ("providerType") `);
        await queryRunner.query(`CREATE TABLE "messages"."providers" ("id" SERIAL NOT NULL, "$id" character varying NOT NULL, "$createdAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$updatedAt" TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT now(), "$deletedAt" TIMESTAMP(0) WITH TIME ZONE, "$permissions" text, "name" character varying(128) NOT NULL, "provider" character varying(128) NOT NULL, "type" character varying(128) NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "credentials" character varying(16384) NOT NULL, "options" character varying(16384) DEFAULT '', "search" character varying(65535) DEFAULT '', CONSTRAINT "PK_0a60b53faff1df3205f5c4038bf" PRIMARY KEY ("id", "$id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d735474e539e674ba3702eddc4" ON "messages"."providers" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6e65bb1ecd94653de7b16bb80" ON "messages"."providers" ("provider") `);
        await queryRunner.query(`CREATE INDEX "IDX_06250375d112fc6ec96ca3ee7c" ON "messages"."providers" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_75bc90bfd88301b175518fde3b" ON "messages"."providers" ("search") `);
        await queryRunner.query(`ALTER TABLE "auth"."tokens" ADD CONSTRAINT "FK_8c26f11a8b165c263af3ad865f8" FOREIGN KEY ("userId", "user_$id") REFERENCES "auth"."users"("id","$id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth"."authenticators" ADD CONSTRAINT "FK_2f3a0e7f07ebe75b1a85fbc0e18" FOREIGN KEY ("userId", "user_$id") REFERENCES "auth"."users"("id","$id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth"."challenges" ADD CONSTRAINT "FK_fec373b440cc69f2abfa95eaf49" FOREIGN KEY ("userId", "user_$id") REFERENCES "auth"."users"("id","$id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth"."sessions" ADD CONSTRAINT "FK_3f4cee83dc7df0ef302718cbfce" FOREIGN KEY ("userId", "user_$id") REFERENCES "auth"."users"("id","$id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth"."memberships" ADD CONSTRAINT "FK_cb4caa97cf5305699e35ae76e19" FOREIGN KEY ("userId", "user_$id") REFERENCES "auth"."users"("id","$id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth"."memberships" ADD CONSTRAINT "FK_8627d403970d84365ed1100820c" FOREIGN KEY ("teamId", "team_$id") REFERENCES "auth"."teams"("id","$id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages"."targets" ADD CONSTRAINT "FK_613736577e5dc1bd20e523634a8" FOREIGN KEY ("userId", "user_$id") REFERENCES "auth"."users"("id","$id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "storage"."files" ADD CONSTRAINT "FK_208a033c1c2b40c48e20c95ce3b" FOREIGN KEY ("bucketId", "bucket_$id") REFERENCES "storage"."buckets"("id","$id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "storage"."files" DROP CONSTRAINT "FK_208a033c1c2b40c48e20c95ce3b"`);
        await queryRunner.query(`ALTER TABLE "messages"."targets" DROP CONSTRAINT "FK_613736577e5dc1bd20e523634a8"`);
        await queryRunner.query(`ALTER TABLE "auth"."memberships" DROP CONSTRAINT "FK_8627d403970d84365ed1100820c"`);
        await queryRunner.query(`ALTER TABLE "auth"."memberships" DROP CONSTRAINT "FK_cb4caa97cf5305699e35ae76e19"`);
        await queryRunner.query(`ALTER TABLE "auth"."sessions" DROP CONSTRAINT "FK_3f4cee83dc7df0ef302718cbfce"`);
        await queryRunner.query(`ALTER TABLE "auth"."challenges" DROP CONSTRAINT "FK_fec373b440cc69f2abfa95eaf49"`);
        await queryRunner.query(`ALTER TABLE "auth"."authenticators" DROP CONSTRAINT "FK_2f3a0e7f07ebe75b1a85fbc0e18"`);
        await queryRunner.query(`ALTER TABLE "auth"."tokens" DROP CONSTRAINT "FK_8c26f11a8b165c263af3ad865f8"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_75bc90bfd88301b175518fde3b"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_06250375d112fc6ec96ca3ee7c"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_e6e65bb1ecd94653de7b16bb80"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_d735474e539e674ba3702eddc4"`);
        await queryRunner.query(`DROP TABLE "messages"."providers"`);
        await queryRunner.query(`DROP INDEX "messages"."idx_provider_type"`);
        await queryRunner.query(`DROP INDEX "messages"."idx_status"`);
        await queryRunner.query(`DROP INDEX "messages"."idx_scheduled_at"`);
        await queryRunner.query(`DROP INDEX "messages"."idx_schedule_internal_id"`);
        await queryRunner.query(`DROP INDEX "messages"."idx_schedule_id"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_de1963a30b933e2c55054a21ea"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_35000359daf153b15b27ee21e2"`);
        await queryRunner.query(`DROP TABLE "messages"."messages"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_6fef292713b917a8e5f41bbba9"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_fd461838f998443c5441989db5"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_d966300036db0e1ac00fa51c32"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_3b5f276933ed75028216a4a843"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_3e82da94a504e2d6dff5c9f393"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_64f26a3234a4bac78f6b6e9523"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_1198809f29d22accb0143684ff"`);
        await queryRunner.query(`DROP TABLE "messages"."subscribers"`);
        await queryRunner.query(`DROP INDEX "storage"."IDX_9cb7d3810278adbffd4230ce68"`);
        await queryRunner.query(`DROP INDEX "storage"."IDX_bfced34fec53fd4205673bec3f"`);
        await queryRunner.query(`DROP INDEX "storage"."IDX_d8e7903f3a8a0a28a49f6b4886"`);
        await queryRunner.query(`DROP INDEX "storage"."IDX_a1d014cb180d27ab17fc21be50"`);
        await queryRunner.query(`DROP INDEX "storage"."IDX_389d4090f38da709582e7e3a95"`);
        await queryRunner.query(`DROP INDEX "storage"."IDX_aacdd3a68ed158c5b526d67276"`);
        await queryRunner.query(`DROP INDEX "storage"."IDX_332d10755187ac3c580e21fbc0"`);
        await queryRunner.query(`DROP INDEX "storage"."IDX_03457cb4a0bd785d24201481f6"`);
        await queryRunner.query(`DROP TABLE "storage"."files"`);
        await queryRunner.query(`DROP TABLE "storage"."buckets"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_NAME"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_EMAIL"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_PHONE"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_STATUS"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_PASSWORD_UPDATE"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_REGISTRATION"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_EMAIL_VERIFICATION"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_PHONE_VERIFICATION"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_SEARCH"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_ACCESSED_AT"`);
        await queryRunner.query(`DROP TABLE "auth"."users"`);
        await queryRunner.query(`DROP TABLE "messages"."targets"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_a9a92751714b0cd99bcca9f18b"`);
        await queryRunner.query(`DROP INDEX "messages"."IDX_1304b1c61016e63f60cd147ce6"`);
        await queryRunner.query(`DROP TABLE "messages"."topics"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_85f35eea70810a5e1fd14fbce0"`);
        await queryRunner.query(`DROP INDEX "auth"."user_index"`);
        await queryRunner.query(`DROP INDEX "auth"."team_index"`);
        await queryRunner.query(`DROP INDEX "auth"."search_index"`);
        await queryRunner.query(`DROP INDEX "auth"."userId_index"`);
        await queryRunner.query(`DROP INDEX "auth"."teamId_index"`);
        await queryRunner.query(`DROP INDEX "auth"."invited_index"`);
        await queryRunner.query(`DROP INDEX "auth"."joined_index"`);
        await queryRunner.query(`DROP INDEX "auth"."confirm_index"`);
        await queryRunner.query(`DROP TABLE "auth"."memberships"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_a4ab53f394a0ccc38437919456"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_d6ada59c75ff2761704cccebd8"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_48c0c32e6247a2de155baeaf98"`);
        await queryRunner.query(`DROP TABLE "auth"."teams"`);
        await queryRunner.query(`DROP TABLE "auth"."sessions"`);
        await queryRunner.query(`DROP INDEX "auth"."idx_user_id"`);
        await queryRunner.query(`DROP TABLE "auth"."challenges"`);
        await queryRunner.query(`DROP TABLE "auth"."authenticators"`);
        await queryRunner.query(`DROP INDEX "auth"."IDX_8c26f11a8b165c263af3ad865f"`);
        await queryRunner.query(`DROP TABLE "auth"."tokens"`);
        await queryRunner.query(`DROP INDEX "meta"."IDX_76768c4da0c82f87ca31cf732b"`);
        await queryRunner.query(`DROP INDEX "meta"."IDX_4f56ebcf8cba238205136aa00f"`);
        await queryRunner.query(`DROP TABLE "meta"."databases"`);
        await queryRunner.query(`DROP INDEX "meta"."_key_time"`);
        await queryRunner.query(`DROP INDEX "meta"."_key_period_time"`);
        await queryRunner.query(`DROP INDEX "meta"."_key_metric_period_time"`);
        await queryRunner.query(`DROP TABLE "meta"."stats"`);
    }

}
