import { Auth } from '@nuvix/core/helpers'
import {
  AttributeType,
  Collection,
  Database,
  ID,
  IndexType,
  Order,
} from '@nuvix/db'

export const authCollections = {
  users: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('users'),
    name: 'Users',
    attributes: [
      {
        $id: ID.custom('name'),
        key: ID.custom('name'),
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('email'),
        key: ID.custom('email'),
        type: AttributeType.String,
        size: 320,
        default: null,
      },
      {
        $id: ID.custom('phone'),
        key: ID.custom('phone'),
        type: AttributeType.String,
        size: 16, // leading '+' and 15 digitts maximum by E.164 format
        default: null,
      },
      {
        $id: ID.custom('status'),
        key: ID.custom('status'),
        type: AttributeType.Boolean,
        default: null,
      },
      {
        $id: ID.custom('labels'),
        key: ID.custom('labels'),
        type: AttributeType.String,
        size: 128,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('passwordHistory'),
        key: ID.custom('passwordHistory'),
        type: AttributeType.String,
        size: 16384,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('password'),
        key: ID.custom('password'),
        type: AttributeType.String,
        size: 16384,
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('hash'),
        key: ID.custom('hash'),
        type: AttributeType.String,
        size: 256,
        default: Auth.DEFAULT_ALGO,
      },
      {
        $id: ID.custom('hashOptions'), // Configuration of hashing algorithm
        key: ID.custom('hashOptions'),
        type: AttributeType.Json,
        default: Auth.DEFAULT_ALGO_OPTIONS,
      },
      {
        $id: ID.custom('passwordUpdate'),
        key: ID.custom('passwordUpdate'),
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('prefs'),
        key: ID.custom('prefs'),
        type: AttributeType.Json,
        default: {},
      },
      {
        $id: ID.custom('registration'),
        key: ID.custom('registration'),
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('emailVerification'),
        key: ID.custom('emailVerification'),
        type: AttributeType.Boolean,
        default: null,
      },
      {
        $id: ID.custom('phoneVerification'),
        key: ID.custom('phoneVerification'),
        type: AttributeType.Boolean,
        default: null,
      },
      {
        $id: ID.custom('reset'),
        key: ID.custom('reset'),
        type: AttributeType.Boolean,
        default: null,
      },
      {
        $id: ID.custom('mfa'),
        key: ID.custom('mfa'),
        type: AttributeType.Boolean,
        default: null,
      },
      {
        $id: ID.custom('mfaRecoveryCodes'),
        key: ID.custom('mfaRecoveryCodes'),
        type: AttributeType.String,
        size: 256,
        default: [],
        array: true,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('authenticators'),
        key: ID.custom('authenticators'),
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryAuthenticators'],
      },
      {
        $id: ID.custom('sessions'),
        key: ID.custom('sessions'),
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQuerySessions'],
      },
      {
        $id: ID.custom('tokens'),
        key: ID.custom('tokens'),
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryTokens'],
      },
      {
        $id: ID.custom('challenges'),
        key: ID.custom('challenges'),
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryChallenges'],
      },
      {
        $id: ID.custom('memberships'),
        key: ID.custom('memberships'),
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryMemberships'],
      },
      {
        $id: ID.custom('targets'),
        key: ID.custom('targets'),
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryTargets'],
      },
      {
        $id: ID.custom('search'),
        key: ID.custom('search'),
        type: AttributeType.String,
        size: 16384,
        default: null,
        filters: ['userSearch'],
      },
      {
        $id: ID.custom('accessedAt'),
        key: ID.custom('accessedAt'),
        type: AttributeType.Timestamptz,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_name'),
        type: IndexType.Key,
        attributes: ['name'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_email'),
        type: IndexType.Unique,
        attributes: ['email'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_phone'),
        type: IndexType.Unique,
        attributes: ['phone'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_status'),
        type: IndexType.Key,
        attributes: ['status'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_passwordUpdate'),
        type: IndexType.Key,
        attributes: ['passwordUpdate'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_registration'),
        type: IndexType.Key,
        attributes: ['registration'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_emailVerification'),
        type: IndexType.Key,
        attributes: ['emailVerification'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_phoneVerification'),
        type: IndexType.Key,
        attributes: ['phoneVerification'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
      {
        $id: '_key_accessedAt',
        type: IndexType.Key,
        attributes: ['accessedAt'],
        orders: [],
      },
    ],
  },

  teams: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('teams'),
    name: 'Teams',
    attributes: [
      {
        $id: ID.custom('name'),
        key: ID.custom('name'),
        type: AttributeType.String,
        size: 128,
        default: null,
      },
      {
        $id: ID.custom('total'),
        key: ID.custom('total'),
        type: AttributeType.Integer,
        size: 4,
        default: null,
      },
      {
        $id: ID.custom('search'),
        key: ID.custom('search'),
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
      {
        $id: ID.custom('prefs'),
        key: ID.custom('prefs'),
        type: AttributeType.Json,
        default: {},
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
      {
        $id: ID.custom('_key_name'),
        type: IndexType.Key,
        attributes: ['name'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_total'),
        type: IndexType.Key,
        attributes: ['total'],
        orders: [Order.Asc],
      },
    ],
  },

  tokens: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('tokens'),
    name: 'Tokens',
    attributes: [
      {
        $id: ID.custom('userInternalId'),
        key: ID.custom('userInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('userId'),
        key: ID.custom('userId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('type'),
        key: ID.custom('type'),
        type: AttributeType.Integer,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('secret'),
        key: ID.custom('secret'),
        type: AttributeType.String,
        size: 1000,
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('expire'),
        key: ID.custom('expire'),
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('userAgent'),
        key: ID.custom('userAgent'),
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
      {
        $id: ID.custom('ip'),
        key: ID.custom('ip'),
        type: AttributeType.String,
        size: 45, // https://stackoverflow.com/a/166157/2299554
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_user'),
        type: IndexType.Key,
        attributes: ['userInternalId'],
        orders: [Order.Asc],
      },
    ],
  },

  authenticators: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('authenticators'),
    name: 'Authenticators',
    attributes: [
      {
        $id: ID.custom('userInternalId'),
        key: ID.custom('userInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('userId'),
        key: ID.custom('userId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('type'),
        key: ID.custom('type'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('verified'),
        key: ID.custom('verified'),
        type: AttributeType.Boolean,
        default: false,
      },
      {
        $id: ID.custom('data'),
        key: ID.custom('data'),
        type: AttributeType.String,
        size: 65535,
        default: [],
        filters: ['json', 'encrypt'],
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_userInternalId'),
        type: IndexType.Key,
        attributes: ['userInternalId'],
        orders: [Order.Asc],
      },
    ],
  },

  challenges: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('challenges'),
    name: 'Challenges',
    attributes: [
      {
        $id: ID.custom('userInternalId'),
        key: ID.custom('userInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('userId'),
        key: ID.custom('userId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('type'),
        key: ID.custom('type'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('token'),
        key: ID.custom('token'),
        type: AttributeType.String,
        size: 512, // https://www.tutorialspoint.com/how-long-is-the-sha256-hash-in-mysql (512 for encryption)
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('code'),
        key: ID.custom('code'),
        type: AttributeType.String,
        size: 512,
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('expire'),
        key: ID.custom('expire'),
        type: AttributeType.Timestamptz,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_user'),
        type: IndexType.Key,
        attributes: ['userInternalId'],
        orders: [Order.Asc],
      },
    ],
  },

  sessions: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('sessions'),
    name: 'Sessions',
    attributes: [
      {
        $id: ID.custom('userInternalId'),
        key: ID.custom('userInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('userId'),
        key: ID.custom('userId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('provider'),
        key: ID.custom('provider'),
        type: AttributeType.String,
        size: 128,
        default: null,
      },
      {
        $id: ID.custom('providerUid'),
        key: ID.custom('providerUid'),
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('providerAccessToken'),
        key: ID.custom('providerAccessToken'),
        type: AttributeType.String,
        size: 16384,
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('providerAccessTokenExpiry'),
        key: ID.custom('providerAccessTokenExpiry'),
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('providerRefreshToken'),
        key: ID.custom('providerRefreshToken'),
        type: AttributeType.String,
        size: 16384,
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('secret'),
        key: ID.custom('secret'),
        type: AttributeType.String,
        size: 512, // https://www.tutorialspoint.com/how-long-is-the-sha256-hash-in-mysql (512 for encryption)
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('userAgent'),
        key: ID.custom('userAgent'),
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
      {
        $id: ID.custom('ip'),
        key: ID.custom('ip'),
        type: AttributeType.String,
        size: 45, // https://stackoverflow.com/a/166157/2299554
        default: null,
      },
      {
        $id: ID.custom('countryCode'),
        key: ID.custom('countryCode'),
        type: AttributeType.String,
        size: 2,
        required: false,
      },
      {
        $id: ID.custom('osCode'),
        key: ID.custom('osCode'),
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('osName'),
        key: ID.custom('osName'),
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('osVersion'),
        key: ID.custom('osVersion'),
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('clientType'),
        key: ID.custom('clientType'),
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('clientCode'),
        key: ID.custom('clientCode'),
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('clientName'),
        key: ID.custom('clientName'),
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('clientVersion'),
        key: ID.custom('clientVersion'),
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('clientEngine'),
        key: ID.custom('clientEngine'),
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('clientEngineVersion'),
        key: ID.custom('clientEngineVersion'),
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('deviceName'),
        key: ID.custom('deviceName'),
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('deviceBrand'),
        key: ID.custom('deviceBrand'),
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('deviceModel'),
        key: ID.custom('deviceModel'),
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('factors'),
        key: ID.custom('factors'),
        type: AttributeType.String,
        size: 256,
        default: [],
        array: true,
      },
      {
        $id: ID.custom('expire'),
        key: ID.custom('expire'),
        type: AttributeType.Timestamptz,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('mfaUpdatedAt'),
        key: ID.custom('mfaUpdatedAt'),
        type: AttributeType.Timestamptz,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_provider_providerUid'),
        type: IndexType.Key,
        attributes: ['provider', 'providerUid'],
        orders: [Order.Asc, Order.Asc],
      },
      {
        $id: ID.custom('_key_user'),
        type: IndexType.Key,
        attributes: ['userInternalId'],
        orders: [Order.Asc],
      },
    ],
  },

  identities: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('identities'),
    name: 'Identities',
    attributes: [
      {
        $id: ID.custom('userInternalId'),
        key: ID.custom('userInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('userId'),
        key: ID.custom('userId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('provider'),
        key: ID.custom('provider'),
        type: AttributeType.String,
        size: 128,
        default: null,
      },
      {
        $id: ID.custom('providerUid'),
        key: ID.custom('providerUid'),
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('providerEmail'),
        key: ID.custom('providerEmail'),
        type: AttributeType.String,
        size: 320,
        default: null,
      },
      {
        $id: ID.custom('providerAccessToken'),
        key: ID.custom('providerAccessToken'),
        type: AttributeType.String,
        size: 16384,
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('providerAccessTokenExpiry'),
        key: ID.custom('providerAccessTokenExpiry'),
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('providerRefreshToken'),
        key: ID.custom('providerRefreshToken'),
        type: AttributeType.String,
        size: 16384,
        default: null,
        filters: ['encrypt'],
      },
      {
        // Used to store data from provider that may or may not be sensitive
        $id: ID.custom('secrets'),
        key: ID.custom('secrets'),
        type: AttributeType.String,
        size: 16384,
        default: [],
        filters: ['json', 'encrypt'],
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_userInternalId_provider_providerUid'),
        type: IndexType.Unique,
        attributes: ['userInternalId', 'provider', 'providerUid'],
        orders: [Order.Asc, Order.Asc],
      },
      {
        $id: ID.custom('_key_provider_providerUid'),
        type: IndexType.Unique,
        attributes: ['provider', 'providerUid'],
        orders: [Order.Asc, Order.Asc],
      },
      {
        $id: ID.custom('_key_userId'),
        type: IndexType.Key,
        attributes: ['userId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_userInternalId'),
        type: IndexType.Key,
        attributes: ['userInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_provider'),
        type: IndexType.Key,
        attributes: ['provider'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerUid'),
        type: IndexType.Key,
        attributes: ['providerUid'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerEmail'),
        type: IndexType.Key,
        attributes: ['providerEmail'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerAccessTokenExpiry'),
        type: IndexType.Key,
        attributes: ['providerAccessTokenExpiry'],
        orders: [Order.Asc],
      },
    ],
  },

  targets: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('targets'),
    name: 'Targets',
    attributes: [
      {
        $id: ID.custom('userId'),
        key: ID.custom('userId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('userInternalId'),
        key: ID.custom('userInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('sessionId'),
        key: ID.custom('sessionId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('sessionInternalId'),
        key: ID.custom('sessionInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('providerType'),
        key: ID.custom('providerType'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerId'),
        key: ID.custom('providerId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('providerInternalId'),
        key: ID.custom('providerInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('identifier'),
        key: ID.custom('identifier'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('name'),
        key: ID.custom('name'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('expired'),
        key: ID.custom('expired'),
        type: AttributeType.Boolean,
        default: false,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_userId'),
        type: IndexType.Key,
        attributes: ['userId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_userInternalId'),
        type: IndexType.Key,
        attributes: ['userInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerId'),
        type: IndexType.Key,
        attributes: ['providerId'],
        orders: [],
      },
      {
        $id: ID.custom('_key_providerInternalId'),
        type: IndexType.Key,
        attributes: ['providerInternalId'],
        orders: [],
      },
      {
        $id: ID.custom('_key_identifier'),
        type: IndexType.Unique,
        attributes: ['identifier'],
        orders: [],
      },
    ],
  },

  memberships: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('memberships'),
    name: 'Memberships',
    attributes: [
      {
        $id: ID.custom('userInternalId'),
        key: ID.custom('userInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('userId'),
        key: ID.custom('userId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('teamInternalId'),
        key: ID.custom('teamInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('teamId'),
        key: ID.custom('teamId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('roles'),
        key: ID.custom('roles'),
        type: AttributeType.String,
        size: 128,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('invited'),
        key: ID.custom('invited'),
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('joined'),
        key: ID.custom('joined'),
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('confirm'),
        key: ID.custom('confirm'),
        type: AttributeType.Boolean,
        default: null,
      },
      {
        $id: ID.custom('secret'),
        key: ID.custom('secret'),
        type: AttributeType.String,
        size: 1026,
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('search'),
        key: ID.custom('search'),
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_unique'),
        type: IndexType.Unique,
        attributes: ['teamInternalId', 'userInternalId'],
        orders: [Order.Asc, Order.Asc],
      },
      {
        $id: ID.custom('_key_user'),
        type: IndexType.Key,
        attributes: ['userInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_team'),
        type: IndexType.Key,
        attributes: ['teamInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
      {
        $id: ID.custom('_key_userId'),
        type: IndexType.Key,
        attributes: ['userId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_teamId'),
        type: IndexType.Key,
        attributes: ['teamId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_invited'),
        type: IndexType.Key,
        attributes: ['invited'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_joined'),
        type: IndexType.Key,
        attributes: ['joined'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_confirm'),
        type: IndexType.Key,
        attributes: ['confirm'],
        orders: [Order.Asc],
      },
    ],
  },
}

export const commonCollections = (
  _for: 'platform' | 'project',
): Record<string, Collection> => ({
  cache: {
    $collection: Database.METADATA,
    $id: 'cache',
    name: 'Cache',
    attributes: [
      {
        $id: 'resource',
        key: 'resource',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: 'resourceType',
        key: 'resourceType',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('mimeType'),
        key: ID.custom('mimeType'),
        type: AttributeType.String,
        size: 255, // https://tools.ietf.org/html/rfc4288#section-4.2
        default: null,
      },
      {
        $id: 'accessedAt',
        key: 'accessedAt',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: 'signature',
        key: 'signature',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
    ],
    indexes: [
      {
        $id: '_key_accessedAt',
        type: IndexType.Key,
        attributes: ['accessedAt'],
        orders: [],
      },
      {
        $id: '_key_resource',
        type: IndexType.Key,
        attributes: ['resource'],
        orders: [],
      },
    ],
  },

  buckets: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('buckets'),
    name: 'Buckets',
    attributes: [
      {
        $id: ID.custom('enabled'),
        key: ID.custom('enabled'),
        type: AttributeType.Boolean,
        required: true,
      },
      {
        $id: ID.custom('name'),
        key: ID.custom('name'),
        type: AttributeType.String,
        size: 128,
        required: true,
      },
      {
        $id: ID.custom('fileSecurity'),
        key: ID.custom('fileSecurity'),
        type: AttributeType.Boolean,
        size: 1,
      },
      {
        $id: ID.custom('maximumFileSize'),
        key: ID.custom('maximumFileSize'),
        type: AttributeType.Integer,
        size: 8,
        required: true,
      },
      {
        $id: ID.custom('allowedFileExtensions'),
        key: ID.custom('allowedFileExtensions'),
        type: AttributeType.String,
        size: 64,
        required: true,
        array: true,
      },
      {
        $id: 'compression',
        key: 'compression',
        type: AttributeType.String,
        size: 10,
        required: true,
      },
      {
        $id: ID.custom('encryption'),
        key: ID.custom('encryption'),
        type: AttributeType.Boolean,
        required: true,
      },
      {
        $id: ID.custom('antivirus'),
        key: ID.custom('antivirus'),
        type: AttributeType.Boolean,
        required: true,
      },
      {
        $id: ID.custom('search'),
        key: ID.custom('search'),
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_fulltext_name'),
        type: IndexType.FullText,
        attributes: ['name'],
        orders: [],
      },
      {
        $id: ID.custom('_key_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
      {
        $id: ID.custom('_key_enabled'),
        type: IndexType.Key,
        attributes: ['enabled'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_name'),
        type: IndexType.Key,
        attributes: ['name'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_fileSecurity'),
        type: IndexType.Key,
        attributes: ['fileSecurity'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_maximumFileSize'),
        type: IndexType.Key,
        attributes: ['maximumFileSize'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_encryption'),
        type: IndexType.Key,
        attributes: ['encryption'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_antivirus'),
        type: IndexType.Key,
        attributes: ['antivirus'],
        orders: [Order.Asc],
      },
    ],
  },

  stats: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('stats'),
    name: 'Stats',
    attributes: [
      {
        $id: ID.custom('metric'),
        key: ID.custom('metric'),
        type: AttributeType.String,
        size: 255,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('region'),
        key: ID.custom('region'),
        type: AttributeType.String,
        size: 255,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('value'),
        key: ID.custom('value'),
        type: AttributeType.Integer,
        size: 8,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('time'),
        key: ID.custom('time'),
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('period'),
        key: ID.custom('period'),
        type: AttributeType.String,
        size: 4,
        required: true,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_time'),
        type: IndexType.Key,
        attributes: ['time'],
        orders: [Order.Desc],
      },
      {
        $id: ID.custom('_key_period_time'),
        type: IndexType.Key,
        attributes: ['period', 'time'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_metric_period_time'),
        type: IndexType.Unique,
        attributes: ['metric', 'period', 'time'],
        orders: [Order.Desc],
      },
    ],
  },

  providers: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('providers'),
    name: 'Providers',
    attributes: [
      {
        $id: ID.custom('name'),
        key: ID.custom('name'),
        type: AttributeType.String,
        size: 128,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('provider'),
        key: ID.custom('provider'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('type'),
        key: ID.custom('type'),
        type: AttributeType.String,
        size: 128,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('enabled'),
        key: ID.custom('enabled'),
        type: AttributeType.Boolean,
        required: true,
        default: true,
      },
      {
        $id: ID.custom('credentials'),
        key: ID.custom('credentials'),
        type: AttributeType.String,
        size: 16384,
        required: true,
        default: null,
        filters: ['json', 'encrypt'],
      },
      {
        $id: ID.custom('options'),
        key: ID.custom('options'),
        type: AttributeType.Json,
        default: [],
      },
      {
        $id: ID.custom('search'),
        key: ID.custom('search'),
        type: AttributeType.String,
        size: 65535,
        default: '',
        filters: ['providerSearch'],
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_provider'),
        type: IndexType.Key,
        attributes: ['provider'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_name'),
        type: IndexType.FullText,
        attributes: ['name'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_type'),
        type: IndexType.Key,
        attributes: ['type'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_enabled_type'),
        type: IndexType.Key,
        attributes: ['enabled', 'type'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
    ],
  },

  messages: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('messages'),
    name: 'Messages',
    attributes: [
      {
        $id: ID.custom('providerType'),
        key: ID.custom('providerType'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('status'),
        key: ID.custom('status'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: 'processing',
      },
      {
        $id: ID.custom('data'),
        key: ID.custom('data'),
        type: AttributeType.Json,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('topics'),
        key: ID.custom('topics'),
        type: AttributeType.String,
        size: 21845,
        array: true,
      },
      {
        $id: ID.custom('users'),
        key: ID.custom('users'),
        type: AttributeType.String,
        size: 21845,
        array: true,
      },
      {
        $id: ID.custom('targets'),
        key: ID.custom('targets'),
        type: AttributeType.String,
        size: 21845,
        array: true,
      },
      {
        $id: ID.custom('scheduledAt'),
        key: ID.custom('scheduledAt'),
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('scheduleInternalId'),
        key: ID.custom('scheduleInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('scheduleId'),
        key: ID.custom('scheduleId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('deliveredAt'),
        key: ID.custom('deliveredAt'),
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('deliveryErrors'),
        key: ID.custom('deliveryErrors'),
        type: AttributeType.String,
        size: 65535,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('deliveredTotal'),
        key: ID.custom('deliveredTotal'),
        type: AttributeType.Integer,
        default: 0,
      },
      {
        $id: ID.custom('search'),
        key: ID.custom('search'),
        type: AttributeType.String,
        size: 16384,
        default: '',
        filters: ['messageSearch'],
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
    ],
  },

  topics: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('topics'),
    name: 'Topics',
    attributes: [
      {
        $id: ID.custom('name'),
        key: ID.custom('name'),
        type: AttributeType.String,
        size: 128,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('subscribe'),
        key: ID.custom('subscribe'),
        type: AttributeType.String,
        size: 128,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('emailTotal'),
        key: ID.custom('emailTotal'),
        type: AttributeType.Integer,
        default: 0,
      },
      {
        $id: ID.custom('smsTotal'),
        key: ID.custom('smsTotal'),
        type: AttributeType.Integer,
        default: 0,
      },
      {
        $id: ID.custom('pushTotal'),
        key: ID.custom('pushTotal'),
        type: AttributeType.Integer,
        default: 0,
      },
      {
        $id: ID.custom('targets'),
        key: ID.custom('targets'),
        type: AttributeType.Virtual,
        default: null,
        filters: [
          _for === 'platform'
            ? 'subQueryTopicTargets'
            : 'subQueryProjectTopicTargets',
        ],
      },
      {
        $id: ID.custom('search'),
        key: ID.custom('search'),
        type: AttributeType.String,
        size: 16384,
        default: '',
        filters: ['topicSearch'],
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_name'),
        type: IndexType.FullText,
        attributes: ['name'],
        orders: [],
      },
      {
        $id: ID.custom('_key_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [Order.Asc],
      },
    ],
  },

  subscribers: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('subscribers'),
    name: 'Subscribers',
    attributes: [
      {
        $id: ID.custom('targetId'),
        key: ID.custom('targetId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('targetInternalId'),
        key: ID.custom('targetInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('userId'),
        key: ID.custom('userId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('userInternalId'),
        key: ID.custom('userInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('topicId'),
        key: ID.custom('topicId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('topicInternalId'),
        key: ID.custom('topicInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerType'),
        key: ID.custom('providerType'),
        type: AttributeType.String,
        size: 128,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('search'),
        key: ID.custom('search'),
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_targetId'),
        type: IndexType.Key,
        attributes: ['targetId'],
        orders: [],
      },
      {
        $id: ID.custom('_key_targetInternalId'),
        type: IndexType.Key,
        attributes: ['targetInternalId'],
        orders: [],
      },
      {
        $id: ID.custom('_key_userId'),
        type: IndexType.Key,
        attributes: ['userId'],
        orders: [],
      },
      {
        $id: ID.custom('_key_userInternalId'),
        type: IndexType.Key,
        attributes: ['userInternalId'],
        orders: [],
      },
      {
        $id: ID.custom('_key_topicId'),
        type: IndexType.Key,
        attributes: ['topicId'],
        orders: [],
      },
      {
        $id: ID.custom('_key_topicInternalId'),
        type: IndexType.Key,
        attributes: ['topicInternalId'],
        orders: [],
      },
      {
        $id: ID.custom('_unique_target_topic'),
        type: IndexType.Unique,
        attributes: ['targetInternalId', 'topicInternalId'],
        orders: [],
      },
      {
        $id: ID.custom('_fulltext_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
    ],
  },
})
