import {
  AttributeType,
  Collection,
  Database,
  ID,
  IndexType,
  Order,
} from '@nuvix-tech/db';
import { commonCollections } from './common';
import { APP_DATABASE_ATTRIBUTE_EMAIL } from '../constants';

export const consoleCollections: Record<string, Collection> = {
  teams: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('teams'),
    name: 'Teams',
    attributes: [
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: 128,
        default: null,
      },
      {
        $id: ID.custom('total'),
        key: 'total',
        type: AttributeType.Integer,
        size: 4,
        default: null,
      },
      {
        $id: ID.custom('search'),
        key: 'search',
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
      {
        $id: ID.custom('prefs'),
        key: 'prefs',
        type: AttributeType.Json,
        default: {},
      },
      {
        $id: ID.custom('budgetAlerts'),
        key: 'budgetAlerts',
        type: AttributeType.String,
        size: 1000,
        default: [],
        array: true,
      },
      {
        $id: ID.custom('billingPlan'),
        key: 'billingPlan',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('billingEmail'),
        key: 'billingEmail',
        type: AttributeType.String,
        size: 326,
        default: null,
      },
      {
        $id: ID.custom('billingStartDate'),
        key: 'billingStartDate',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('billingCurrentInvoiceDate'),
        key: 'billingCurrentInvoiceDate',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('billingNextInvoiceDate'),
        key: 'billingNextInvoiceDate',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('billingTrialStartDate'),
        key: 'billingTrialStartDate',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('billingTrialDays'),
        key: 'billingTrialDays',
        type: AttributeType.Integer,
        default: 0,
      },
      {
        $id: ID.custom('billingAggregationId'),
        key: 'billingAggregationId',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('paymentMethodId'),
        key: 'paymentMethodId',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('billingAddressId'),
        key: 'billingAddressId',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('backupPaymentMethodId'),
        key: 'backupPaymentMethodId',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('agreementBAA'),
        key: 'agreementBAA',
        size: 1000,
        type: AttributeType.String,
        default: null,
      },
      {
        $id: ID.custom('programManagerName'),
        key: 'programManagerName',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('programManagerCalendar'),
        key: 'programManagerCalendar',
        type: AttributeType.String,
        size: 1000,
        default: null,
      },
      {
        $id: ID.custom('programDiscordChannelName'),
        key: 'programDiscordChannelName',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('programDiscordChannelUrl'),
        key: 'programDiscordChannelUrl',
        type: AttributeType.String,
        size: 500,
        default: null,
      },
      {
        $id: ID.custom('billingLimits'),
        key: 'billingLimits',
        type: AttributeType.Json,
        default: {},
      },
      {
        $id: ID.custom('billingPlanDowngrade'),
        key: 'billingPlanDowngrade',
        type: AttributeType.Json,
        default: {},
      },
      {
        $id: ID.custom('billingTaxId'),
        key: 'billingTaxId',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('markedForDeletion'),
        key: 'markedForDeletion',
        type: AttributeType.Boolean,
        required: true,
        default: false,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
      {
        $id: ID.custom('_key_name'),
        type: IndexType.Key,
        attributes: ['name'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_total'),
        type: IndexType.Key,
        attributes: ['total'],
        orders: [Order.Asc],
      },
    ],
  },

  billings: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('billing'),
    name: 'Billing',
    attributes: [
      {
        $id: ID.custom('userId'),
        key: 'userId',
        type: AttributeType.String,
        size: 255,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('streetAddress'),
        key: 'streetAddress',
        type: AttributeType.String,
        size: 1001,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('addressLine2'),
        key: 'addressLine2',
        type: AttributeType.String,
        size: 1001,
        default: null,
      },
      {
        $id: ID.custom('country'),
        key: 'country',
        type: AttributeType.String,
        size: 201,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('city'),
        key: 'city',
        type: AttributeType.String,
        size: 301,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('state'),
        key: 'state',
        type: AttributeType.String,
        size: 289,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('postalCode'),
        key: 'postalCode',
        type: AttributeType.String,
        size: 8,
        required: true,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_userId'),
        type: IndexType.Key,
        attributes: ['userId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_city'),
        type: IndexType.Key,
        attributes: ['city'],
        orders: [Order.Asc],
      },
    ],
  },

  invoices: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('invoice'),
    name: 'Invoice',
    attributes: [
      {
        $id: ID.custom('userId'),
        key: 'userId',
        type: AttributeType.String,
        size: 255,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('userInternalId'),
        key: 'userInternalId',
        type: AttributeType.Integer,
        size: 24,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('orgId'),
        key: 'orgId',
        type: AttributeType.String,
        size: 255,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('orgInternalId'),
        key: 'orgInternalId',
        type: AttributeType.Integer,
        size: 24,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('aggregationId'),
        key: 'aggregationId',
        type: AttributeType.String,
        size: 255,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('plan'),
        key: 'plan',
        type: AttributeType.String,
        size: 255,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('usage'),
        key: 'usage',
        type: AttributeType.Json,
        required: true,
        default: {},
      },
      {
        $id: ID.custom('amount'),
        key: 'amount',
        type: AttributeType.Float,
        size: 4,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('tax'),
        key: 'tax',
        type: AttributeType.Float,
        size: 4,
        default: 0,
      },
      {
        $id: ID.custom('taxAmount'),
        key: 'taxAmount',
        type: AttributeType.Float,
        size: 4,
        default: 0,
      },
      {
        $id: ID.custom('vat'),
        key: 'vat',
        type: AttributeType.Float,
        size: 4,
        default: 0,
      },
      {
        $id: ID.custom('vatAmount'),
        key: 'vatAmount',
        type: AttributeType.Float,
        size: 4,
        default: 0,
      },
      {
        $id: ID.custom('grossAmount'),
        key: 'grossAmount',
        type: AttributeType.Float,
        size: 4,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('creditsUsed'),
        key: 'creditsUsed',
        type: AttributeType.Float,
        size: 4,
        default: 0,
      },
      {
        $id: ID.custom('currency'),
        key: 'currency',
        type: AttributeType.String,
        size: 3,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('clientSecret'),
        key: 'clientSecret',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('status'),
        key: 'status',
        type: AttributeType.String,
        size: 50,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('lastError'),
        key: 'lastError',
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('dueAt'),
        key: 'dueAt',
        type: AttributeType.String,
        size: 50,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('from'),
        key: 'from',
        type: AttributeType.String,
        size: 50,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('to'),
        key: 'to',
        type: AttributeType.String,
        size: 50,
        required: true,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_userId'),
        type: IndexType.Key,
        attributes: ['userId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_orgId'),
        type: IndexType.Key,
        attributes: ['orgId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_status'),
        type: IndexType.Key,
        attributes: ['status'],
        orders: [Order.Asc],
      },
    ],
  },

  'payment-methods': {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('paymentMethods'),
    name: 'Payment Methods',
    attributes: [
      {
        $id: ID.custom('providerMethodId'),
        key: 'providerMethodId',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('clientSecret'),
        key: 'clientSecret',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('providerUserId'),
        key: 'providerUserId',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('userId'),
        key: 'userId',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('expiryMonth'),
        key: 'expiryMonth',
        type: AttributeType.Integer,
        default: null,
      },
      {
        $id: ID.custom('expiryYear'),
        key: 'expiryYear',
        type: AttributeType.Integer,
        default: null,
      },
      {
        $id: ID.custom('last4'),
        key: 'last4',
        type: AttributeType.String,
        size: 4,
        default: null,
      },
      {
        $id: ID.custom('brand'),
        key: 'brand',
        type: AttributeType.String,
        size: 50,
        default: null,
      },
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('mandateId'),
        key: 'mandateId',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('country'),
        key: 'country',
        type: AttributeType.String,
        size: 50,
        default: null,
      },
      {
        $id: ID.custom('lastError'),
        key: 'lastError',
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('default'),
        key: 'default',
        type: AttributeType.Boolean,
        default: false,
      },
      {
        $id: ID.custom('expired'),
        key: 'expired',
        type: AttributeType.Boolean,
        default: false,
      },
      {
        $id: ID.custom('failed'),
        key: 'failed',
        type: AttributeType.Boolean,
        default: false,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_userId'),
        type: IndexType.Key,
        attributes: ['userId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerMethodId'),
        type: IndexType.Key,
        attributes: ['providerMethodId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_expiryYear'),
        type: IndexType.Key,
        attributes: ['expiryYear'],
        orders: [Order.Asc],
      },
    ],
  },

  projects: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('projects'),
    name: 'Projects',
    attributes: [
      {
        $id: ID.custom('teamInternalId'),
        key: 'teamInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('teamId'),
        key: 'teamId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: 128,
        default: null,
      },
      {
        $id: ID.custom('region'),
        key: 'region',
        type: AttributeType.String,
        size: 128,
        default: null,
      },
      {
        $id: ID.custom('description'),
        key: 'description',
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('database'),
        key: 'database',
        type: AttributeType.String,
        size: 65535,
        required: true,
        default: null,
        filters: ['json', 'encrypt'],
      },
      {
        $id: ID.custom('logo'),
        key: 'logo',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('url'),
        key: 'url',
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
      {
        $id: ID.custom('version'),
        key: 'version',
        type: AttributeType.String,
        size: 16,
        default: null,
      },
      {
        $id: ID.custom('legalName'),
        key: 'legalName',
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('legalCountry'),
        key: 'legalCountry',
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('legalState'),
        key: 'legalState',
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('legalCity'),
        key: 'legalCity',
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('legalAddress'),
        key: 'legalAddress',
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('legalTaxId'),
        key: 'legalTaxId',
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: 'accessedAt',
        key: 'accessedAt',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: 'enabled',
        key: 'enabled',
        type: AttributeType.Boolean,
        default: true,
      },
      {
        $id: 'status',
        key: 'status',
        type: AttributeType.String,
        size: 50,
        default: 'pending',
      },
      {
        $id: 'metadata',
        key: 'metadata',
        type: AttributeType.Json,
        default: {},
      },
      {
        $id: ID.custom('services'),
        key: 'services',
        type: AttributeType.Json,
        size: 16384,
        default: [],
      },
      {
        $id: ID.custom('apis'),
        key: 'apis',
        type: AttributeType.Json,
        size: 16384,
        default: [],
      },
      {
        $id: ID.custom('smtp'),
        key: 'smtp',
        type: AttributeType.String,
        size: 16384,
        default: {},
        filters: ['json', 'encrypt'],
      },
      {
        $id: ID.custom('templates'),
        key: 'templates',
        type: AttributeType.Json,
        default: [],
      },
      {
        $id: ID.custom('auths'),
        key: 'auths',
        type: AttributeType.Json,
        default: {},
      },
      {
        $id: ID.custom('oAuthProviders'),
        key: 'oAuthProviders',
        type: AttributeType.String,
        size: 16384,
        default: [],
        filters: ['json', 'encrypt'],
      },
      {
        $id: ID.custom('platforms'),
        key: 'platforms',
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryPlatforms'],
      },
      {
        $id: ID.custom('webhooks'),
        key: 'webhooks',
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryWebhooks'],
      },
      {
        $id: ID.custom('keys'),
        key: 'keys',
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryKeys'],
      },
      {
        $id: ID.custom('search'),
        key: 'search',
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
      {
        $id: ID.custom('_key_name'),
        type: IndexType.Key,
        attributes: ['name'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_team'),
        type: IndexType.Key,
        attributes: ['teamId'],
        orders: [Order.Asc],
      },
    ],
  },

  schedules: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('schedules'),
    name: 'schedules',
    attributes: [
      {
        $id: ID.custom('resourceType'),
        key: 'resourceType',
        type: AttributeType.String,
        size: 100,
        default: null,
      },
      {
        $id: ID.custom('resourceInternalId'),
        key: 'resourceInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('resourceId'),
        key: 'resourceId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('resourceUpdatedAt'),
        key: 'resourceUpdatedAt',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('schedule'),
        key: 'schedule',
        type: AttributeType.String,
        size: 100,
        default: null,
      },
      {
        $id: ID.custom('data'),
        key: 'data',
        type: AttributeType.String,
        size: 65535,
        default: {},
        filters: ['json', 'encrypt'],
      },
      {
        $id: ID.custom('active'),
        key: 'active',
        type: AttributeType.Boolean,
        default: null,
      },
      {
        $id: ID.custom('region'),
        key: 'region',
        type: AttributeType.String,
        size: 10,
        required: true,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_region_resourceType_resourceUpdatedAt'),
        type: IndexType.Key,
        attributes: ['region', 'resourceType', 'resourceUpdatedAt'],
        orders: [],
      },
      {
        $id: ID.custom('_key_region_resourceType_projectId_resourceId'),
        type: IndexType.Key,
        attributes: ['region', 'resourceType', 'projectId', 'resourceId'],
        orders: [],
      },
    ],
  },

  platforms: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('platforms'),
    name: 'platforms',
    attributes: [
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('type'),
        key: 'type',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: 256,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('key'),
        key: 'key',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('store'),
        key: 'store',
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('hostname'),
        key: 'hostname',
        type: AttributeType.String,
        size: 256,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_project'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
    ],
  },

  keys: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('keys'),
    name: 'keys',
    attributes: [
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: 0,
      },
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('scopes'),
        key: 'scopes',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('secret'),
        key: 'secret',
        type: AttributeType.String,
        size: 1600, // string(256) doubling for encryption
        required: true,
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('expire'),
        key: 'expire',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('accessedAt'),
        key: 'accessedAt',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('sdks'),
        key: 'sdks',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
        array: true,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_project'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: '_key_accessedAt',
        type: IndexType.Key,
        attributes: ['accessedAt'],
        orders: [],
      },
    ],
  },

  webhooks: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('webhooks'),
    name: 'webhooks',
    attributes: [
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('url'),
        key: 'url',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('httpUser'),
        key: 'httpUser',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('httpPass'),
        key: 'httpPass',
        type: AttributeType.String,
        size: Database.LENGTH_KEY, // TODO will the length suffice after encryption?
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('security'),
        key: 'security',
        type: AttributeType.Boolean,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('events'),
        key: 'events',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('signatureKey'),
        key: 'signatureKey',
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('enabled'),
        key: 'enabled',
        type: AttributeType.Boolean,
        default: true,
      },
      {
        $id: ID.custom('logs'),
        key: 'logs',
        type: AttributeType.String,
        size: 1000000,
        default: '',
      },
      {
        $id: ID.custom('attempts'),
        key: 'attempts',
        type: AttributeType.Integer,
        size: 4,
        default: 0,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_project'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
    ],
  },

  certificates: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('certificates'),
    name: 'Certificates',
    attributes: [
      {
        $id: ID.custom('domain'),
        key: 'domain',
        type: AttributeType.String,
        // The maximum total length of a domain name or number is 255 characters.
        // https://datatracker.ietf.org/doc/html/rfc2821#section-4.5.3.1
        // https://datatracker.ietf.org/doc/html/rfc5321#section-4.5.3.1.2
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('issueDate'),
        key: 'issueDate',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('renewDate'),
        key: 'renewDate',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('attempts'),
        key: 'attempts',
        type: AttributeType.Integer,
        size: 4,
        default: null,
      },
      {
        $id: ID.custom('logs'),
        key: 'logs',
        type: AttributeType.Json,
        default: null,
      },
      {
        $id: ID.custom('updated'),
        key: 'updated',
        type: AttributeType.Timestamptz,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_domain'),
        type: IndexType.Key,
        attributes: ['domain'],
        orders: [Order.Asc],
      },
    ],
  },

  realtime: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('realtime'),
    name: 'Realtime Connections',
    attributes: [
      {
        $id: ID.custom('container'),
        key: 'container',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('timestamp'),
        key: 'timestamp',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('value'),
        key: 'value',
        type: AttributeType.Json,
        required: true,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_timestamp'),
        type: IndexType.Key,
        attributes: ['timestamp'],
        orders: [Order.Desc],
      },
    ],
  },

  rules: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('rules'),
    name: 'Rules',
    attributes: [
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('domain'),
        key: 'domain',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('resourceType'),
        key: 'resourceType',
        type: AttributeType.String,
        size: 100,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('resourceInternalId'),
        key: 'resourceInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('resourceId'),
        key: 'resourceId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('status'),
        key: 'status',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('certificateId'),
        key: 'certificateId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_domain'),
        type: IndexType.Unique,
        attributes: ['domain'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_projectInternalId'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_projectId'),
        type: IndexType.Key,
        attributes: ['projectId'],
        orders: [Order.Asc],
      },
      {
        $id: '_key_resourceInternalId',
        type: IndexType.Key,
        attributes: ['resourceInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: '_key_resourceId',
        type: IndexType.Key,
        attributes: ['resourceId'],
        orders: [Order.Asc],
      },
      {
        $id: '_key_resourceType',
        type: IndexType.Key,
        attributes: ['resourceType'],
        orders: [Order.Asc],
      },
    ],
  },

  installations: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('installations'),
    name: 'installations',
    attributes: [
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerInstallationId'),
        key: 'providerInstallationId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('organization'),
        key: 'organization',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('provider'),
        key: 'provider',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('personal'),
        key: 'personal',
        type: AttributeType.Boolean,
        default: false,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_projectInternalId'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_projectId'),
        type: IndexType.Key,
        attributes: ['projectId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerInstallationId'),
        type: IndexType.Key,
        attributes: ['providerInstallationId'],
        orders: [Order.Asc],
      },
    ],
  },

  repositories: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('repositories'),
    name: 'repositories',
    attributes: [
      {
        $id: ID.custom('installationId'),
        key: 'installationId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('installationInternalId'),
        key: 'installationInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerRepositoryId'),
        key: 'providerRepositoryId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('resourceId'),
        key: 'resourceId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('resourceInternalId'),
        key: 'resourceInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('resourceType'),
        key: 'resourceType',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerPullRequestIds'),
        key: 'providerPullRequestIds',
        type: AttributeType.String,
        size: 128,
        default: null,
        array: true,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_installationId'),
        type: IndexType.Key,
        attributes: ['installationId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_installationInternalId'),
        type: IndexType.Key,
        attributes: ['installationInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_projectInternalId'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_projectId'),
        type: IndexType.Key,
        attributes: ['projectId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerRepositoryId'),
        type: IndexType.Key,
        attributes: ['providerRepositoryId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_resourceId'),
        type: IndexType.Key,
        attributes: ['resourceId'],
        orders: [Order.Asc],
      },
      {
        $id: '_key_resourceInternalId',
        type: IndexType.Key,
        attributes: ['resourceInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_resourceType'),
        type: IndexType.Key,
        attributes: ['resourceType'],
        orders: [Order.Asc],
      },
    ],
  },

  vcsComments: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('vcsComments'),
    name: 'vcsComments',
    attributes: [
      {
        $id: ID.custom('installationId'),
        key: 'installationId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('installationInternalId'),
        key: 'installationInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerRepositoryId'),
        key: 'providerRepositoryId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerCommentId'),
        key: 'providerCommentId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerPullRequestId'),
        key: 'providerPullRequestId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerBranch'),
        key: 'providerBranch',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_installationId'),
        type: IndexType.Key,
        attributes: ['installationId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_installationInternalId'),
        type: IndexType.Key,
        attributes: ['installationInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_projectInternalId'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_projectId'),
        type: IndexType.Key,
        attributes: ['projectId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerRepositoryId'),
        type: IndexType.Key,
        attributes: ['providerRepositoryId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerPullRequestId'),
        type: IndexType.Key,
        attributes: ['providerPullRequestId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerBranch'),
        type: IndexType.Key,
        attributes: ['providerBranch'],
        orders: [Order.Asc],
      },
    ],
  },

  vcsCommentLocks: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('vcsCommentLocks'),
    name: 'vcsCommentLocks',
    attributes: [],
    indexes: [],
  },

  plans: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('plans'),
    name: 'Plans',
    attributes: [
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: 128,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('order'),
        key: 'order',
        type: AttributeType.Integer,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('price'),
        key: 'price',
        type: AttributeType.Integer,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('trial'),
        key: 'trial',
        type: AttributeType.Integer,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('bandwidth'),
        key: 'bandwidth',
        type: AttributeType.Integer,
        size: 4,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('storage'),
        key: 'storage',
        type: AttributeType.Integer,
        size: 4,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('members'),
        key: 'members',
        type: AttributeType.Integer,
        size: 4,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('webhooks'),
        key: 'webhooks',
        type: AttributeType.Integer,
        size: 4,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('platforms'),
        key: 'platforms',
        type: AttributeType.Integer,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('users'),
        key: 'users',
        type: AttributeType.Integer,
        size: 4,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('teams'),
        key: 'teams',
        type: AttributeType.Integer,
        size: 4,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('databases'),
        key: 'databases',
        type: AttributeType.Integer,
        size: 4,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('buckets'),
        key: 'buckets',
        type: AttributeType.Integer,
        size: 4,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('fileSize'),
        key: 'fileSize',
        type: AttributeType.Integer,
        size: 4,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('functions'),
        key: 'functions',
        type: AttributeType.Integer,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('executions'),
        key: 'executions',
        type: AttributeType.Integer,
        size: 4,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('realtime'),
        key: 'realtime',
        type: AttributeType.Integer,
        size: 4,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('logs'),
        key: 'logs',
        type: AttributeType.Integer,
        size: 4,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('addons'),
        key: 'addons',
        type: AttributeType.Json,
        default: {},
      },
      {
        $id: ID.custom('customSmtp'),
        key: 'customSmtp',
        type: AttributeType.Boolean,
        required: true,
        default: false,
      },
      {
        $id: ID.custom('emailBranding'),
        key: 'emailBranding',
        type: AttributeType.Boolean,
        required: true,
        default: true,
      },
      {
        $id: ID.custom('requiresPaymentMethod'),
        key: 'requiresPaymentMethod',
        type: AttributeType.Boolean,
        required: true,
        default: false,
      },
      {
        $id: ID.custom('requiresBillingAddress'),
        key: 'requiresBillingAddress',
        type: AttributeType.Boolean,
        required: true,
        default: false,
      },
      {
        $id: ID.custom('isAvailable'),
        key: 'isAvailable',
        type: AttributeType.Boolean,
        required: true,
        default: true,
      },
      {
        $id: ID.custom('selfService'),
        key: 'selfService',
        type: AttributeType.Boolean,
        required: true,
        default: true,
      },
      {
        $id: ID.custom('premiumSupport'),
        key: 'premiumSupport',
        type: AttributeType.Boolean,
        required: true,
        default: false,
      },
      {
        $id: ID.custom('budgeting'),
        key: 'budgeting',
        type: AttributeType.Boolean,
        required: true,
        default: false,
      },
      {
        $id: ID.custom('supportsMockNumbers'),
        key: 'supportsMockNumbers',
        type: AttributeType.Boolean,
        required: true,
        default: false,
      },
      {
        $id: ID.custom('backupsEnabled'),
        key: 'backupsEnabled',
        type: AttributeType.Boolean,
        required: true,
        default: false,
      },
      {
        $id: ID.custom('backupPolicies'),
        key: 'backupPolicies',
        type: AttributeType.Integer,
        required: true,
        default: -1,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_name'),
        type: IndexType.Key,
        attributes: ['name'],
        orders: [Order.Asc],
      },
    ],
  },

  waitlist: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('waitlist'),
    name: 'Waitlist',
    attributes: [
      {
        $id: ID.custom('email'),
        key: 'email',
        type: AttributeType.String,
        format: APP_DATABASE_ATTRIBUTE_EMAIL,
        size: 2000,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('source'),
        key: 'source',
        type: AttributeType.String,
        size: 64,
        default: null,
      },
      {
        $id: ID.custom('note'),
        key: 'note',
        type: AttributeType.String,
        size: 1024,
        default: null,
      },
      {
        $id: ID.custom('notified'),
        key: 'notified',
        type: AttributeType.Boolean,
        default: true,
      },
      {
        $id: ID.custom('metadata'),
        key: 'metadata',
        type: AttributeType.Json,
        default: {},
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_email'),
        type: IndexType.Unique,
        attributes: ['email'],
        orders: [Order.Asc],
      },
    ],
  },

  ...commonCollections,
};
