import { Database, ID } from "@nuvix/database";
import { commonCollections } from "./common";

export const consoleCollections = {
    teams: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('teams'),
        name: 'Teams',
        attributes: [
            {
                $id: ID.custom('name'),
                type: Database.VAR_STRING,
                format: '',
                size: 128,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('total'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('search'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('prefs'),
                type: Database.VAR_STRING,
                format: '',
                size: 65535,
                signed: true,
                required: false,
                default: {},
                array: false,
                filters: ['json'],
            },
            {
                $id: ID.custom('budgetAlerts'),
                type: Database.VAR_STRING,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: [],
                array: true,
                filters: [],
            },
            {
                $id: ID.custom('billingPlan'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('billingEmail'),
                type: Database.VAR_STRING,
                format: '',
                size: 326,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('billingStartDate'),
                type: Database.VAR_DATETIME,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('billingCurrentInvoiceDate'),
                type: Database.VAR_DATETIME,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('billingNextInvoiceDate'),
                type: Database.VAR_DATETIME,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('billingTrialStartDate'),
                type: Database.VAR_DATETIME,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('billingTrialDays'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: 0,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('billingAggregationId'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('paymentMethodId'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('billingAddressId'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('backupPaymentMethodId'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('agreementBAA'),
                type: Database.VAR_STRING,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('programManagerName'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('programManagerCalendar'),
                type: Database.VAR_STRING,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('programDiscordChannelName'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('programDiscordChannelUrl'),
                type: Database.VAR_STRING,
                format: '',
                size: 500,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('billingLimits'),
                type: Database.VAR_STRING,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: {},
                array: false,
                filters: ['json'],
            },
            {
                $id: ID.custom('billingPlanDowngrade'),
                type: Database.VAR_STRING,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: {},
                array: false,
                filters: ['json'],
            },
            {
                $id: ID.custom('billingTaxId'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('markedForDeletion'),
                type: Database.VAR_BOOLEAN,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: false,
                array: false,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_search'),
                type: Database.INDEX_FULLTEXT,
                attributes: ['search'],
                lengths: [],
                orders: [],
            },
            {
                $id: ID.custom('_key_name'),
                type: Database.INDEX_KEY,
                attributes: ['name'],
                lengths: [128],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_total'),
                type: Database.INDEX_KEY,
                attributes: ['total'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
        ],
    },

    billings: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('billing'),
        name: 'Billing',
        attributes: [
            {
                $id: ID.custom('userId'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('streetAddress'),
                type: Database.VAR_STRING,
                format: '',
                size: 1001,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('addressLine2'),
                type: Database.VAR_STRING,
                format: '',
                size: 1001,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('country'),
                type: Database.VAR_STRING,
                format: '',
                size: 201,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('city'),
                type: Database.VAR_STRING,
                format: '',
                size: 301,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('state'),
                type: Database.VAR_STRING,
                format: '',
                size: 289,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('postalCode'),
                type: Database.VAR_STRING,
                format: '',
                size: 8,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_userId'),
                type: Database.INDEX_KEY,
                attributes: ['userId'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_city'),
                type: Database.INDEX_KEY,
                attributes: ['city'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
        ],
    },

    invoices: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('invoice'),
        name: 'Invoice',
        attributes: [
            {
                $id: ID.custom('userId'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('userInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: 24,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('orgId'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('orgInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: 24,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('aggregationId'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('plan'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('usage'),
                type: Database.VAR_STRING,
                format: '',
                size: 65535,
                signed: true,
                required: true,
                default: {},
                array: false,
                filters: ['json'],
            },
            {
                $id: ID.custom('amount'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('tax'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: 0,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('taxAmount'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: 0,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('vat'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: 0,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('vatAmount'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: 0,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('grossAmount'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('creditsUsed'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: 0,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('currency'),
                type: Database.VAR_STRING,
                format: '',
                size: 3,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('clientSecret'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('status'),
                type: Database.VAR_STRING,
                format: '',
                size: 50,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('lastError'),
                type: Database.VAR_STRING,
                format: '',
                size: 2048,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('dueAt'),
                type: Database.VAR_STRING,
                format: '',
                size: 50,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('from'),
                type: Database.VAR_STRING,
                format: '',
                size: 50,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('to'),
                type: Database.VAR_STRING,
                format: '',
                size: 50,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_userId'),
                type: Database.INDEX_KEY,
                attributes: ['userId'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_orgId'),
                type: Database.INDEX_KEY,
                attributes: ['orgId'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_status'),
                type: Database.INDEX_KEY,
                attributes: ['status'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
        ],
    },

    'payment-methods': {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('paymentMethods'),
        name: 'Payment Methods',
        attributes: [
            {
                $id: ID.custom('providerMethodId'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('clientSecret'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('providerUserId'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('userId'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('expiryMonth'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('expiryYear'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('last4'),
                type: Database.VAR_STRING,
                format: '',
                size: 4,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('brand'),
                type: Database.VAR_STRING,
                format: '',
                size: 50,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('name'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('mandateId'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('country'),
                type: Database.VAR_STRING,
                format: '',
                size: 50,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('lastError'),
                type: Database.VAR_STRING,
                format: '',
                size: 2048,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('default'),
                type: Database.VAR_BOOLEAN,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: false,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('expired'),
                type: Database.VAR_BOOLEAN,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: false,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('failed'),
                type: Database.VAR_BOOLEAN,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: false,
                array: false,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_userId'),
                type: Database.INDEX_KEY,
                attributes: ['userId'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_providerMethodId'),
                type: Database.INDEX_KEY,
                attributes: ['providerMethodId'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_expiryYear'),
                type: Database.INDEX_KEY,
                attributes: ['expiryYear'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
        ],
    },

    projects: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('projects'),
        name: 'Projects',
        attributes: [
            {
                $id: ID.custom('teamInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('teamId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('name'),
                type: Database.VAR_STRING,
                format: '',
                size: 128,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('region'),
                type: Database.VAR_STRING,
                format: '',
                size: 128,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('description'),
                type: Database.VAR_STRING,
                format: '',
                size: 256,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('database'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: ['json', 'encrypt'],
            },
            {
                $id: ID.custom('logo'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('url'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('version'),
                type: Database.VAR_STRING,
                format: '',
                size: 16,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('legalName'),
                type: Database.VAR_STRING,
                format: '',
                size: 256,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('legalCountry'),
                type: Database.VAR_STRING,
                format: '',
                size: 256,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('legalState'),
                type: Database.VAR_STRING,
                format: '',
                size: 256,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('legalCity'),
                type: Database.VAR_STRING,
                format: '',
                size: 256,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('legalAddress'),
                type: Database.VAR_STRING,
                format: '',
                size: 256,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('legalTaxId'),
                type: Database.VAR_STRING,
                format: '',
                size: 256,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: 'accessedAt',
                type: Database.VAR_DATETIME,
                format: '',
                size: 0,
                signed: false,
                required: false,
                default: null,
                array: false,
                filters: ['datetime'],
            },
            {
                $id: 'enabled',
                type: Database.VAR_BOOLEAN,
                format: '',
                size: 0,
                signed: false,
                required: false,
                default: true,
                array: false,
                filters: [],
            },
             {
                $id: 'status',
                type: Database.VAR_STRING,
                format: '',
                size: 50,
                signed: false,
                required: false,
                default: 'pending',
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('services'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: false,
                default: [],
                array: false,
                filters: ['json'],
            },
            {
                $id: ID.custom('apis'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: false,
                default: [],
                array: false,
                filters: ['json'],
            },
            {
                $id: ID.custom('smtp'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: false,
                default: [],
                array: false,
                filters: ['json', 'encrypt'],
            },
            {
                $id: ID.custom('templates'),
                type: Database.VAR_STRING,
                format: '',
                size: 1000000, // TODO make sure size fits
                signed: true,
                required: false,
                default: [],
                array: false,
                filters: ['json'],
            },
            {
                $id: ID.custom('auths'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: false,
                default: [],
                array: false,
                filters: ['json'],
            },
            {
                $id: ID.custom('oAuthProviders'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: false,
                default: [],
                array: false,
                filters: ['json', 'encrypt'],
            },
            {
                $id: ID.custom('platforms'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: ['subQueryPlatforms'],
            },
            {
                $id: ID.custom('webhooks'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: ['subQueryWebhooks'],
            },
            {
                $id: ID.custom('keys'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: ['subQueryKeys'],
            },
            {
                $id: ID.custom('search'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_search'),
                type: Database.INDEX_FULLTEXT,
                attributes: ['search'],
                lengths: [],
                orders: [],
            },
            {
                $id: ID.custom('_key_name'),
                type: Database.INDEX_KEY,
                attributes: ['name'],
                lengths: [128],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_team'),
                type: Database.INDEX_KEY,
                attributes: ['teamId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
        ],
    },

    schedules: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('schedules'),
        name: 'schedules',
        attributes: [
            {
                $id: ID.custom('resourceType'),
                type: Database.VAR_STRING,
                format: '',
                size: 100,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('resourceInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('resourceId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('resourceUpdatedAt'),
                type: Database.VAR_DATETIME,
                format: '',
                size: 0,
                signed: false,
                required: false,
                default: null,
                array: false,
                filters: ['datetime'],
            },
            {
                $id: ID.custom('projectId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('schedule'),
                type: Database.VAR_STRING,
                format: '',
                size: 100,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('data'),
                type: Database.VAR_STRING,
                format: '',
                size: 65535,
                signed: true,
                required: false,
                default: {},
                array: false,
                filters: ['json', 'encrypt'],
            },
            {
                $id: ID.custom('active'),
                type: Database.VAR_BOOLEAN,
                signed: true,
                size: 0,
                format: '',
                filters: [],
                required: false,
                default: null,
                array: false,
            },
            {
                $id: ID.custom('region'),
                type: Database.VAR_STRING,
                format: '',
                size: 10,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_region_resourceType_resourceUpdatedAt'),
                type: Database.INDEX_KEY,
                attributes: ['region', 'resourceType', 'resourceUpdatedAt'],
                lengths: [],
                orders: [],
            },
            {
                $id: ID.custom('_key_region_resourceType_projectId_resourceId'),
                type: Database.INDEX_KEY,
                attributes: ['region', 'resourceType', 'projectId', 'resourceId'],
                lengths: [],
                orders: [],
            },
        ],
    },

    platforms: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('platforms'),
        name: 'platforms',
        attributes: [
            {
                $id: ID.custom('projectInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('projectId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('type'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('name'),
                type: Database.VAR_STRING,
                format: '',
                size: 256,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('key'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('store'),
                type: Database.VAR_STRING,
                format: '',
                size: 256,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('hostname'),
                type: Database.VAR_STRING,
                format: '',
                size: 256,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_project'),
                type: Database.INDEX_KEY,
                attributes: ['projectInternalId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
        ],
    },

    keys: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('keys'),
        name: 'keys',
        attributes: [
            {
                $id: ID.custom('projectInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('projectId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: 0,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('name'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('scopes'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: true,
                filters: [],
            },
            {
                $id: ID.custom('secret'),
                type: Database.VAR_STRING,
                format: '',
                size: 1600, // var_dump of \bin2hex(\random_bytes(128)): string(256) doubling for encryption
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: ['encrypt'],
            },
            {
                $id: ID.custom('expire'),
                type: Database.VAR_DATETIME,
                format: '',
                size: 0,
                signed: false,
                required: false,
                default: null,
                array: false,
                filters: ['datetime'],
            },
            {
                $id: ID.custom('accessedAt'),
                type: Database.VAR_DATETIME,
                format: '',
                size: 0,
                signed: false,
                required: false,
                default: null,
                array: false,
                filters: ['datetime'],
            },
            {
                $id: ID.custom('sdks'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: true,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_project'),
                type: Database.INDEX_KEY,
                attributes: ['projectInternalId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: '_key_accessedAt',
                type: Database.INDEX_KEY,
                attributes: ['accessedAt'],
                lengths: [],
                orders: [],
            },
        ],
    },

    webhooks: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('webhooks'),
        name: 'webhooks',
        attributes: [
            {
                $id: ID.custom('projectInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('projectId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('name'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('url'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('httpUser'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('httpPass'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY, // TODO will the length suffice after encryption?
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: ['encrypt'],
            },
            {
                $id: ID.custom('security'),
                type: Database.VAR_BOOLEAN,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('events'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: true,
                filters: [],
            },
            {
                $id: ID.custom('signatureKey'),
                type: Database.VAR_STRING,
                format: '',
                size: 2048,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('enabled'),
                type: Database.VAR_BOOLEAN,
                signed: true,
                size: 0,
                format: '',
                filters: [],
                required: false,
                default: true,
                array: false,
            },
            {
                $id: ID.custom('logs'),
                type: Database.VAR_STRING,
                format: '',
                size: 1000000,
                signed: true,
                required: false,
                default: '',
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('attempts'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: 0,
                array: false,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_project'),
                type: Database.INDEX_KEY,
                attributes: ['projectInternalId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
        ],
    },

    certificates: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('certificates'),
        name: 'Certificates',
        attributes: [
            {
                $id: ID.custom('domain'),
                type: Database.VAR_STRING,
                format: '',
                // The maximum total length of a domain name or number is 255 characters.
                // https://datatracker.ietf.org/doc/html/rfc2821#section-4.5.3.1
                // https://datatracker.ietf.org/doc/html/rfc5321#section-4.5.3.1.2
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('issueDate'),
                type: Database.VAR_DATETIME,
                format: '',
                size: 0,
                signed: false,
                required: false,
                default: null,
                array: false,
                filters: ['datetime'],
            },
            {
                $id: ID.custom('renewDate'),
                type: Database.VAR_DATETIME,
                format: '',
                size: 0,
                signed: false,
                required: false,
                default: null,
                array: false,
                filters: ['datetime'],
            },
            {
                $id: ID.custom('attempts'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('logs'),
                type: Database.VAR_STRING,
                format: '',
                size: 1000000,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('updated'),
                type: Database.VAR_DATETIME,
                format: '',
                size: 0,
                signed: false,
                required: false,
                default: null,
                array: false,
                filters: ['datetime'],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_domain'),
                type: Database.INDEX_KEY,
                attributes: ['domain'],
                lengths: [255],
                orders: [Database.ORDER_ASC],
            },
        ],
    },

    realtime: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('realtime'),
        name: 'Realtime Connections',
        attributes: [
            {
                $id: ID.custom('container'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('timestamp'),
                type: Database.VAR_DATETIME,
                format: '',
                size: 0,
                signed: false,
                required: false,
                default: null,
                array: false,
                filters: ['datetime'],
            },
            {
                $id: ID.custom('value'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [], //TODO: use json filter
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_timestamp'),
                type: Database.INDEX_KEY,
                attributes: ['timestamp'],
                lengths: [],
                orders: [Database.ORDER_DESC],
            },
        ],
    },

    rules: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('rules'),
        name: 'Rules',
        attributes: [
            {
                $id: ID.custom('projectId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('projectInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('domain'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('resourceType'),
                type: Database.VAR_STRING,
                format: '',
                size: 100,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('resourceInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('resourceId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('status'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('certificateId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_domain'),
                type: Database.INDEX_UNIQUE,
                attributes: ['domain'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_projectInternalId'),
                type: Database.INDEX_KEY,
                attributes: ['projectInternalId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_projectId'),
                type: Database.INDEX_KEY,
                attributes: ['projectId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: '_key_resourceInternalId',
                type: Database.INDEX_KEY,
                attributes: ['resourceInternalId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: '_key_resourceId',
                type: Database.INDEX_KEY,
                attributes: ['resourceId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: '_key_resourceType',
                type: Database.INDEX_KEY,
                attributes: ['resourceType'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
        ],
    },

    installations: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('installations'),
        name: 'installations',
        attributes: [
            {
                $id: ID.custom('projectId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('projectInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('providerInstallationId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('organization'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('provider'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('personal'),
                type: Database.VAR_BOOLEAN,
                signed: true,
                size: 0,
                format: '',
                filters: [],
                required: false,
                default: false,
                array: false,
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_projectInternalId'),
                type: Database.INDEX_KEY,
                attributes: ['projectInternalId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_projectId'),
                type: Database.INDEX_KEY,
                attributes: ['projectId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_providerInstallationId'),
                type: Database.INDEX_KEY,
                attributes: ['providerInstallationId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
        ],
    },

    repositories: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('repositories'),
        name: 'repositories',
        attributes: [
            {
                $id: ID.custom('installationId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('installationInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('projectId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('projectInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('providerRepositoryId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('resourceId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('resourceInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('resourceType'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('providerPullRequestIds'),
                type: Database.VAR_STRING,
                format: '',
                size: 128,
                signed: true,
                required: false,
                default: null,
                array: true,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_installationId'),
                type: Database.INDEX_KEY,
                attributes: ['installationId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_installationInternalId'),
                type: Database.INDEX_KEY,
                attributes: ['installationInternalId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_projectInternalId'),
                type: Database.INDEX_KEY,
                attributes: ['projectInternalId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_projectId'),
                type: Database.INDEX_KEY,
                attributes: ['projectId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_providerRepositoryId'),
                type: Database.INDEX_KEY,
                attributes: ['providerRepositoryId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_resourceId'),
                type: Database.INDEX_KEY,
                attributes: ['resourceId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: '_key_resourceInternalId',
                type: Database.INDEX_KEY,
                attributes: ['resourceInternalId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_resourceType'),
                type: Database.INDEX_KEY,
                attributes: ['resourceType'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
        ],
    },

    vcsComments: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('vcsComments'),
        name: 'vcsComments',
        attributes: [
            {
                $id: ID.custom('installationId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('installationInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('projectId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('projectInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('providerRepositoryId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('providerCommentId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('providerPullRequestId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('providerBranch'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_installationId'),
                type: Database.INDEX_KEY,
                attributes: ['installationId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_installationInternalId'),
                type: Database.INDEX_KEY,
                attributes: ['installationInternalId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_projectInternalId'),
                type: Database.INDEX_KEY,
                attributes: ['projectInternalId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_projectId'),
                type: Database.INDEX_KEY,
                attributes: ['projectId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_providerRepositoryId'),
                type: Database.INDEX_KEY,
                attributes: ['providerRepositoryId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_providerPullRequestId'),
                type: Database.INDEX_KEY,
                attributes: ['providerPullRequestId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_providerBranch'),
                type: Database.INDEX_KEY,
                attributes: ['providerBranch'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
        ],
    },

    vcsCommentLocks: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('vcsCommentLocks'),
        name: 'vcsCommentLocks',
        attributes: [],
        indexes: [],
    },

    plans: {
        $collection: ID.custom(Database.METADATA),
        $id: ID.custom('plans'),
        name: 'Plans',
        attributes: [
            {
                $id: ID.custom('name'),
                type: Database.VAR_STRING,
                format: '',
                size: 128,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('order'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('price'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('trial'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('bandwidth'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('storage'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('members'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('webhooks'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('platforms'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('users'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('teams'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('databases'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('buckets'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('fileSize'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('functions'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('executions'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('realtime'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('logs'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('addons'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: false,
                default: {},
                array: false,
                filters: ['json'],
            },
            {
                $id: ID.custom('customSmtp'),
                type: Database.VAR_BOOLEAN,
                signed: true,
                size: 0,
                format: '',
                filters: [],
                required: true,
                default: false,
                array: false,
            },
            {
                $id: ID.custom('emailBranding'),
                type: Database.VAR_BOOLEAN,
                signed: true,
                size: 0,
                format: '',
                filters: [],
                required: true,
                default: true,
                array: false,
            },
            {
                $id: ID.custom('requiresPaymentMethod'),
                type: Database.VAR_BOOLEAN,
                signed: true,
                size: 0,
                format: '',
                filters: [],
                required: true,
                default: false,
                array: false,
            },
            {
                $id: ID.custom('requiresBillingAddress'),
                type: Database.VAR_BOOLEAN,
                signed: true,
                size: 0,
                format: '',
                filters: [],
                required: true,
                default: false,
                array: false,
            },
            {
                $id: ID.custom('isAvailable'),
                type: Database.VAR_BOOLEAN,
                signed: true,
                size: 0,
                format: '',
                filters: [],
                required: true,
                default: true,
                array: false,
            },
            {
                $id: ID.custom('selfService'),
                type: Database.VAR_BOOLEAN,
                signed: true,
                size: 0,
                format: '',
                filters: [],
                required: true,
                default: true,
                array: false,
            },
            {
                $id: ID.custom('premiumSupport'),
                type: Database.VAR_BOOLEAN,
                signed: true,
                size: 0,
                format: '',
                filters: [],
                required: true,
                default: false,
                array: false,
            },
            {
                $id: ID.custom('budgeting'),
                type: Database.VAR_BOOLEAN,
                signed: true,
                size: 0,
                format: '',
                filters: [],
                required: true,
                default: false,
                array: false,
            },
            {
                $id: ID.custom('supportsMockNumbers'),
                type: Database.VAR_BOOLEAN,
                signed: true,
                size: 0,
                format: '',
                filters: [],
                required: true,
                default: false,
                array: false,
            },
            {
                $id: ID.custom('backupsEnabled'),
                type: Database.VAR_BOOLEAN,
                signed: true,
                size: 0,
                format: '',
                filters: [],
                required: true,
                default: false,
                array: false,
            },
            {
                $id: ID.custom('backupPolicies'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: true,
                required: true,
                default: -1,
                array: false,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_name'),
                type: Database.INDEX_KEY,
                attributes: ['name'],
                lengths: [128],
                orders: [Database.ORDER_ASC],
            },
        ],
    },

    ...commonCollections,
};