import {
  AttributeType,
  Collection,
  Database,
  ID,
  IndexType,
  Order,
} from '@nuvix/db'
import { authCollections, commonCollections } from './common'

export const internalCollections: Record<string, Collection> = {
  ...authCollections,

  projects: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('projects'),
    name: 'Projects',
    attributes: [
      {
        $id: ID.custom('teamInternalId'),
        key: 'teamInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('teamId'),
        key: 'teamId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: 128,
        default: null,
      },
      {
        $id: ID.custom('region'),
        key: 'region',
        type: AttributeType.String,
        size: 128,
        default: null,
      },
      {
        $id: ID.custom('description'),
        key: 'description',
        type: AttributeType.String,
        size: 512,
        default: null,
      },
      {
        $id: ID.custom('database'),
        key: 'database',
        type: AttributeType.String,
        size: 65535,
        required: true,
        default: null,
        filters: ['json', 'encrypt'],
      },
      {
        $id: ID.custom('logo'),
        key: 'logo',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('url'),
        key: 'url',
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: 'accessedAt',
        key: 'accessedAt',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: 'enabled',
        key: 'enabled',
        type: AttributeType.Boolean,
        default: true,
      },
      {
        $id: 'status',
        key: 'status',
        type: AttributeType.String,
        size: 50,
        default: 'pending',
      },
      {
        $id: ID.custom('environment'),
        key: 'environment',
        type: AttributeType.String,
        size: 50,
        default: 'production',
      },
      {
        $id: 'metadata',
        key: 'metadata',
        type: AttributeType.Json,
        default: {},
      },
      {
        $id: ID.custom('services'),
        key: 'services',
        type: AttributeType.Json,
        size: 16384,
        default: [],
      },
      {
        $id: ID.custom('apis'),
        key: 'apis',
        type: AttributeType.Json,
        size: 16384,
        default: [],
      },
      {
        $id: ID.custom('smtp'),
        key: 'smtp',
        type: AttributeType.String,
        size: 16384,
        default: {},
        filters: ['json', 'encrypt'],
      },
      {
        $id: ID.custom('templates'),
        key: 'templates',
        type: AttributeType.Json,
        default: [],
      },
      {
        $id: ID.custom('auths'),
        key: 'auths',
        type: AttributeType.Json,
        default: {},
      },
      {
        $id: ID.custom('oAuthProviders'),
        key: 'oAuthProviders',
        type: AttributeType.Json,
        default: [],
      },
      {
        $id: ID.custom('platforms'),
        key: 'platforms',
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryPlatforms'],
      },
      {
        $id: ID.custom('webhooks'),
        key: 'webhooks',
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryWebhooks'],
      },
      {
        $id: ID.custom('keys'),
        key: 'keys',
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryKeys'],
      },
      {
        $id: ID.custom('search'),
        key: 'search',
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
      {
        $id: ID.custom('_key_name'),
        type: IndexType.Key,
        attributes: ['name'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_team'),
        type: IndexType.Key,
        attributes: ['teamId'],
        orders: [Order.Asc],
      },
    ],
  },

  schedules: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('schedules'),
    name: 'schedules',
    attributes: [
      {
        $id: ID.custom('resourceType'),
        key: 'resourceType',
        type: AttributeType.String,
        size: 100,
        default: null,
      },
      {
        $id: ID.custom('resourceInternalId'),
        key: 'resourceInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('resourceId'),
        key: 'resourceId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('resourceUpdatedAt'),
        key: 'resourceUpdatedAt',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('schedule'),
        key: 'schedule',
        type: AttributeType.String,
        size: 100,
        default: null,
      },
      {
        $id: ID.custom('data'),
        key: 'data',
        type: AttributeType.String,
        size: 65535,
        default: {},
        filters: ['json', 'encrypt'],
      },
      {
        $id: ID.custom('active'),
        key: 'active',
        type: AttributeType.Boolean,
        default: null,
      },
      {
        $id: ID.custom('region'),
        key: 'region',
        type: AttributeType.String,
        size: 10,
        required: true,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_region_resourceType_resourceUpdatedAt'),
        type: IndexType.Key,
        attributes: ['region', 'resourceType', 'resourceUpdatedAt'],
        orders: [],
      },
      {
        $id: ID.custom('_key_region_resourceType_projectId_resourceId'),
        type: IndexType.Key,
        attributes: ['region', 'resourceType', 'projectId', 'resourceId'],
        orders: [],
      },
    ],
  },

  platforms: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('platforms'),
    name: 'platforms',
    attributes: [
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('type'),
        key: 'type',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: 256,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('key'),
        key: 'key',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('store'),
        key: 'store',
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('hostname'),
        key: 'hostname',
        type: AttributeType.String,
        size: 256,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_project'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
    ],
  },

  keys: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('keys'),
    name: 'keys',
    attributes: [
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: 0,
      },
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('scopes'),
        key: 'scopes',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('secret'),
        key: 'secret',
        type: AttributeType.String,
        size: 1600, // string(256) doubling for encryption
        required: true,
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('expire'),
        key: 'expire',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('accessedAt'),
        key: 'accessedAt',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('sdks'),
        key: 'sdks',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
        array: true,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_project'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: '_key_accessedAt',
        type: IndexType.Key,
        attributes: ['accessedAt'],
        orders: [],
      },
    ],
  },

  webhooks: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('webhooks'),
    name: 'webhooks',
    attributes: [
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('url'),
        key: 'url',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('httpUser'),
        key: 'httpUser',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('httpPass'),
        key: 'httpPass',
        type: AttributeType.String,
        size: Database.LENGTH_KEY * 2, // doubled for encryption
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('security'),
        key: 'security',
        type: AttributeType.Boolean,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('events'),
        key: 'events',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('signatureKey'),
        key: 'signatureKey',
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('enabled'),
        key: 'enabled',
        type: AttributeType.Boolean,
        default: true,
      },
      {
        $id: ID.custom('logs'),
        key: 'logs',
        type: AttributeType.String,
        size: 1000000,
        default: '',
      },
      {
        $id: ID.custom('attempts'),
        key: 'attempts',
        type: AttributeType.Integer,
        size: 4,
        default: 0,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_project'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
    ],
  },

  certificates: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('certificates'),
    name: 'Certificates',
    attributes: [
      {
        $id: ID.custom('domain'),
        key: 'domain',
        type: AttributeType.String,
        // The maximum total length of a domain name or number is 255 characters.
        // https://datatracker.ietf.org/doc/html/rfc2821#section-4.5.3.1
        // https://datatracker.ietf.org/doc/html/rfc5321#section-4.5.3.1.2
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('issueDate'),
        key: 'issueDate',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('renewDate'),
        key: 'renewDate',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('attempts'),
        key: 'attempts',
        type: AttributeType.Integer,
        size: 4,
        default: null,
      },
      {
        $id: ID.custom('logs'),
        key: 'logs',
        type: AttributeType.Json,
        default: null,
      },
      {
        $id: ID.custom('updated'),
        key: 'updated',
        type: AttributeType.Timestamptz,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_domain'),
        type: IndexType.Key,
        attributes: ['domain'],
        orders: [Order.Asc],
      },
    ],
  },

  realtime: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('realtime'),
    name: 'Realtime Connections',
    attributes: [
      {
        $id: ID.custom('container'),
        key: 'container',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('timestamp'),
        key: 'timestamp',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('value'),
        key: 'value',
        type: AttributeType.Json,
        required: true,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_timestamp'),
        type: IndexType.Key,
        attributes: ['timestamp'],
        orders: [Order.Desc],
      },
    ],
  },

  rules: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('rules'),
    name: 'Rules',
    attributes: [
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('domain'),
        key: 'domain',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('resourceType'),
        key: 'resourceType',
        type: AttributeType.String,
        size: 100,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('resourceInternalId'),
        key: 'resourceInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('resourceId'),
        key: 'resourceId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('status'),
        key: 'status',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('certificateId'),
        key: 'certificateId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_domain'),
        type: IndexType.Unique,
        attributes: ['domain'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_projectInternalId'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_projectId'),
        type: IndexType.Key,
        attributes: ['projectId'],
        orders: [Order.Asc],
      },
      {
        $id: '_key_resourceInternalId',
        type: IndexType.Key,
        attributes: ['resourceInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: '_key_resourceId',
        type: IndexType.Key,
        attributes: ['resourceId'],
        orders: [Order.Asc],
      },
      {
        $id: '_key_resourceType',
        type: IndexType.Key,
        attributes: ['resourceType'],
        orders: [Order.Asc],
      },
    ],
  },

  installations: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('installations'),
    name: 'installations',
    attributes: [
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerInstallationId'),
        key: 'providerInstallationId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('organization'),
        key: 'organization',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('provider'),
        key: 'provider',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('personal'),
        key: 'personal',
        type: AttributeType.Boolean,
        default: false,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_projectInternalId'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_projectId'),
        type: IndexType.Key,
        attributes: ['projectId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerInstallationId'),
        type: IndexType.Key,
        attributes: ['providerInstallationId'],
        orders: [Order.Asc],
      },
    ],
  },

  repositories: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('repositories'),
    name: 'repositories',
    attributes: [
      {
        $id: ID.custom('installationId'),
        key: 'installationId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('installationInternalId'),
        key: 'installationInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerRepositoryId'),
        key: 'providerRepositoryId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('resourceId'),
        key: 'resourceId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('resourceInternalId'),
        key: 'resourceInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('resourceType'),
        key: 'resourceType',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerPullRequestIds'),
        key: 'providerPullRequestIds',
        type: AttributeType.String,
        size: 128,
        default: null,
        array: true,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_installationId'),
        type: IndexType.Key,
        attributes: ['installationId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_installationInternalId'),
        type: IndexType.Key,
        attributes: ['installationInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_projectInternalId'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_projectId'),
        type: IndexType.Key,
        attributes: ['projectId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerRepositoryId'),
        type: IndexType.Key,
        attributes: ['providerRepositoryId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_resourceId'),
        type: IndexType.Key,
        attributes: ['resourceId'],
        orders: [Order.Asc],
      },
      {
        $id: '_key_resourceInternalId',
        type: IndexType.Key,
        attributes: ['resourceInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_resourceType'),
        type: IndexType.Key,
        attributes: ['resourceType'],
        orders: [Order.Asc],
      },
    ],
  },

  vcsComments: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('vcsComments'),
    name: 'vcsComments',
    attributes: [
      {
        $id: ID.custom('installationId'),
        key: 'installationId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('installationInternalId'),
        key: 'installationInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerRepositoryId'),
        key: 'providerRepositoryId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerCommentId'),
        key: 'providerCommentId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerPullRequestId'),
        key: 'providerPullRequestId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('providerBranch'),
        key: 'providerBranch',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_installationId'),
        type: IndexType.Key,
        attributes: ['installationId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_installationInternalId'),
        type: IndexType.Key,
        attributes: ['installationInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_projectInternalId'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_projectId'),
        type: IndexType.Key,
        attributes: ['projectId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerRepositoryId'),
        type: IndexType.Key,
        attributes: ['providerRepositoryId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerPullRequestId'),
        type: IndexType.Key,
        attributes: ['providerPullRequestId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerBranch'),
        type: IndexType.Key,
        attributes: ['providerBranch'],
        orders: [Order.Asc],
      },
    ],
  },

  vcsCommentLocks: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('vcsCommentLocks'),
    name: 'vcsCommentLocks',
    attributes: [],
    indexes: [],
  },

  envtokens: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('envtokens'),
    name: 'Environment Tokens',
    attributes: [
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('token'),
        key: 'token',
        type: AttributeType.String,
        size: 512,
        required: true,
        default: null,
        // not encrypted as it public token
      },
      {
        $id: ID.custom('config'),
        key: 'config',
        type: AttributeType.String,
        size: 16384,
        default: null,
        filters: ['json', 'encrypt'],
      },
      {
        $id: ID.custom('metadata'),
        key: 'metadata',
        type: AttributeType.Json,
        default: {},
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_project'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_name_project'),
        type: IndexType.Unique,
        attributes: ['name', 'projectInternalId'],
        orders: [Order.Asc, Order.Asc],
      },
      {
        $id: ID.custom('_key_token'),
        type: IndexType.Unique,
        attributes: ['token'],
        orders: [Order.Asc],
      },
    ],
  },

  roles: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('roles'),
    name: 'Roles',
    attributes: [
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: 100,
        required: true,
      },
      {
        $id: ID.custom('description'),
        key: 'description',
        type: AttributeType.String,
        size: 1000,
        default: null,
      },
      {
        $id: ID.custom('scopes'),
        key: 'scopes',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        array: true,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_name'),
        type: IndexType.Unique,
        attributes: ['name'],
        orders: [Order.Asc],
      },
    ],
  },
  ...commonCollections('platform'),
}
