import {
  AttributeType,
  Collection,
  Database,
  ID,
  IndexType,
  Order,
} from '@nuvix/db'
import { authCollections, commonCollections } from './common'

export const internalCollections: Record<string, Collection> = {
  ...authCollections,

  projects: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('projects'),
    name: 'Projects',
    attributes: [
      {
        $id: ID.custom('teamInternalId'),
        key: 'teamInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('teamId'),
        key: 'teamId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: 128,
        default: null,
      },
      {
        $id: ID.custom('region'),
        key: 'region',
        type: AttributeType.String,
        size: 128,
        default: null,
      },
      {
        $id: ID.custom('description'),
        key: 'description',
        type: AttributeType.String,
        size: 512,
        default: null,
      },
      {
        $id: ID.custom('database'),
        key: 'database',
        type: AttributeType.String,
        size: 65535,
        required: true,
        default: null,
        filters: ['json', 'encrypt'],
      },
      {
        $id: ID.custom('logo'),
        key: 'logo',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('url'),
        key: 'url',
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: 'accessedAt',
        key: 'accessedAt',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: 'enabled',
        key: 'enabled',
        type: AttributeType.Boolean,
        default: true,
      },
      {
        $id: 'status',
        key: 'status',
        type: AttributeType.String,
        size: 50,
        default: 'pending',
      },
      {
        $id: ID.custom('environment'),
        key: 'environment',
        type: AttributeType.String,
        size: 50,
        default: 'production',
      },
      {
        $id: 'metadata',
        key: 'metadata',
        type: AttributeType.Json,
        default: {},
      },
      {
        $id: ID.custom('services'),
        key: 'services',
        type: AttributeType.Json,
        size: 16384,
        default: [],
      },
      {
        $id: ID.custom('apis'),
        key: 'apis',
        type: AttributeType.Json,
        size: 16384,
        default: [],
      },
      {
        $id: ID.custom('smtp'),
        key: 'smtp',
        type: AttributeType.String,
        size: 16384,
        default: {},
        filters: ['json', 'encrypt'],
      },
      {
        $id: ID.custom('templates'),
        key: 'templates',
        type: AttributeType.Json,
        default: [],
      },
      {
        $id: ID.custom('auths'),
        key: 'auths',
        type: AttributeType.Json,
        default: {},
      },
      {
        $id: ID.custom('oAuthProviders'),
        key: 'oAuthProviders',
        type: AttributeType.Json,
        default: [],
      },
      {
        $id: ID.custom('platforms'),
        key: 'platforms',
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryPlatforms'],
      },
      {
        $id: ID.custom('webhooks'),
        key: 'webhooks',
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryWebhooks'],
      },
      {
        $id: ID.custom('keys'),
        key: 'keys',
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryKeys'],
      },
      {
        $id: ID.custom('search'),
        key: 'search',
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
      {
        $id: ID.custom('_key_name'),
        type: IndexType.Key,
        attributes: ['name'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_team'),
        type: IndexType.Key,
        attributes: ['teamId'],
        orders: [Order.Asc],
      },
    ],
  },

  schedules: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('schedules'),
    name: 'schedules',
    attributes: [
      {
        $id: ID.custom('resourceType'),
        key: 'resourceType',
        type: AttributeType.String,
        size: 100,
        default: null,
      },
      {
        $id: ID.custom('resourceInternalId'),
        key: 'resourceInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('resourceId'),
        key: 'resourceId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('resourceUpdatedAt'),
        key: 'resourceUpdatedAt',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('schedule'),
        key: 'schedule',
        type: AttributeType.String,
        size: 100,
        default: null,
      },
      {
        $id: ID.custom('data'),
        key: 'data',
        type: AttributeType.String,
        size: 65535,
        default: {},
        filters: ['json', 'encrypt'],
      },
      {
        $id: ID.custom('active'),
        key: 'active',
        type: AttributeType.Boolean,
        default: null,
      },
      {
        $id: ID.custom('region'),
        key: 'region',
        type: AttributeType.String,
        size: 10,
        required: true,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_region_resourceType_resourceUpdatedAt'),
        type: IndexType.Key,
        attributes: ['region', 'resourceType', 'resourceUpdatedAt'],
        orders: [],
      },
      {
        $id: ID.custom('_key_region_resourceType_projectId_resourceId'),
        type: IndexType.Key,
        attributes: ['region', 'resourceType', 'projectId', 'resourceId'],
        orders: [],
      },
    ],
  },

  platforms: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('platforms'),
    name: 'platforms',
    attributes: [
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('type'),
        key: 'type',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: 256,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('key'),
        key: 'key',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('store'),
        key: 'store',
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('hostname'),
        key: 'hostname',
        type: AttributeType.String,
        size: 256,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_project'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
    ],
  },

  keys: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('keys'),
    name: 'keys',
    attributes: [
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: 0,
      },
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('scopes'),
        key: 'scopes',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('secret'),
        key: 'secret',
        type: AttributeType.String,
        size: 1600, // string(256) doubling for encryption
        required: true,
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('expire'),
        key: 'expire',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('accessedAt'),
        key: 'accessedAt',
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('sdks'),
        key: 'sdks',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
        array: true,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_project'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: '_key_accessedAt',
        type: IndexType.Key,
        attributes: ['accessedAt'],
        orders: [],
      },
    ],
  },

  webhooks: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('webhooks'),
    name: 'webhooks',
    attributes: [
      {
        $id: ID.custom('projectInternalId'),
        key: 'projectInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('projectId'),
        key: 'projectId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('url'),
        key: 'url',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('httpUser'),
        key: 'httpUser',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('httpPass'),
        key: 'httpPass',
        type: AttributeType.String,
        size: Database.LENGTH_KEY * 2, // doubled for encryption
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('security'),
        key: 'security',
        type: AttributeType.Boolean,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('events'),
        key: 'events',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('signatureKey'),
        key: 'signatureKey',
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('enabled'),
        key: 'enabled',
        type: AttributeType.Boolean,
        default: true,
      },
      {
        $id: ID.custom('logs'),
        key: 'logs',
        type: AttributeType.String,
        size: 1000000,
        default: '',
      },
      {
        $id: ID.custom('attempts'),
        key: 'attempts',
        type: AttributeType.Integer,
        size: 4,
        default: 0,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_project'),
        type: IndexType.Key,
        attributes: ['projectInternalId'],
        orders: [Order.Asc],
      },
    ],
  },

  ...commonCollections,
}
