import {
  AttributeType,
  Collection,
  Database,
  ID,
  IndexType,
  Order,
} from '@nuvix-tech/db';

export const bucketCollections: Record<string, Collection> = {
  files: {
    $collection: ID.custom('buckets'),
    $id: ID.custom('files'),
    name: 'Files',
    attributes: [
      {
        $id: ID.custom('bucketId'),
        key: 'bucketId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('bucketInternalId'),
        key: 'bucketInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('path'),
        key: 'path',
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('signature'),
        key: 'signature',
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('mimeType'),
        key: 'mimeType',
        type: AttributeType.String,
        size: 255, // https://tools.ietf.org/html/rfc4288#section-4.2
        default: null,
      },
      {
        $id: ID.custom('metadata'),
        key: 'metadata',
        type: AttributeType.Json,
        size: 75000, // https://tools.ietf.org/html/rfc4288#section-4.2
        default: null,
      },
      {
        $id: ID.custom('sizeOriginal'),
        key: 'sizeOriginal',
        type: AttributeType.Integer,
        size: 8,
        default: null,
      },
      {
        $id: ID.custom('sizeActual'),
        key: 'sizeActual',
        type: AttributeType.Integer,
        size: 8,
        default: null,
      },
      {
        $id: ID.custom('algorithm'),
        key: 'algorithm',
        type: AttributeType.String,
        size: 255,
        default: null,
      },
      {
        $id: ID.custom('comment'),
        key: 'comment',
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('encryptionOptions'),
        key: 'encryptionOptions',
        type: AttributeType.Json,
        size: 64,
        default: null,
      },
      {
        $id: ID.custom('chunksTotal'),
        key: 'chunksTotal',
        type: AttributeType.Integer,
        size: 0,
        default: null,
      },
      {
        $id: ID.custom('chunksUploaded'),
        key: 'chunksUploaded',
        type: AttributeType.Integer,
        size: 0,
        default: null,
      },
      {
        $id: ID.custom('search'),
        key: 'search',
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
      {
        $id: ID.custom('_key_bucket'),
        type: IndexType.Key,
        attributes: ['bucketId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_name'),
        type: IndexType.Key,
        attributes: ['name'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_signature'),
        type: IndexType.Key,
        attributes: ['signature'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_mimeType'),
        type: IndexType.Key,
        attributes: ['mimeType'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_sizeOriginal'),
        type: IndexType.Key,
        attributes: ['sizeOriginal'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_chunksTotal'),
        type: IndexType.Key,
        attributes: ['chunksTotal'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_chunksUploaded'),
        type: IndexType.Key,
        attributes: ['chunksUploaded'],
        orders: [Order.Asc],
      },
    ],
  },
};

export const dbCollections: Record<string, Collection> = {
  collections: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('_collections'),
    name: 'Collections',
    attributes: [
      {
        $id: ID.custom('name'),
        key: 'name',
        type: AttributeType.String,
        size: 256,
        required: true,
      },
      {
        $id: ID.custom('enabled'),
        key: 'enabled',
        type: AttributeType.Boolean,
        size: 0,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('documentSecurity'),
        key: 'documentSecurity',
        type: AttributeType.Boolean,
        size: 0,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('attributes'),
        key: 'attributes',
        type: AttributeType.Virtual,
        filters: ['subQueryAttributes'],
      },
      {
        $id: ID.custom('indexes'),
        key: 'indexes',
        type: AttributeType.Virtual,
        filters: ['subQueryIndexes'],
      },
      {
        $id: ID.custom('metadata'),
        key: ID.custom('metadata'),
        type: AttributeType.Json,
        default: {},
      },
      {
        $id: ID.custom('search'),
        key: 'search',
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_fulltext_search'),
        type: IndexType.FullText,
        attributes: ['search'],

        orders: [],
      },
      {
        $id: ID.custom('_key_name'),
        type: IndexType.Key,
        attributes: ['name'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_enabled'),
        type: IndexType.Key,
        attributes: ['enabled'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_documentSecurity'),
        type: IndexType.Key,
        attributes: ['documentSecurity'],
        orders: [Order.Asc],
      },
    ],
  },

  attributes: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('_attributes'),
    name: 'Attributes',
    attributes: [
      {
        $id: ID.custom('collectionInternalId'),
        key: 'collectionInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('collectionId'),
        key: 'collectionId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('key'),
        key: 'key',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('type'),
        key: 'type',
        type: AttributeType.String,
        size: 256,
        default: null,
      },
      {
        $id: ID.custom('status'),
        key: 'status',
        type: AttributeType.String,
        size: 16,
        default: null,
      },
      {
        $id: ID.custom('error'),
        key: 'error',
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('size'),
        key: 'size',
        type: AttributeType.Integer,
        size: 8,
        default: null,
      },
      {
        $id: ID.custom('required'),
        key: 'required',
        type: AttributeType.Boolean,
        default: null,
      },
      {
        $id: ID.custom('default'),
        key: 'default',
        type: AttributeType.String,
        size: 16384,
        default: null,
        filters: ['casting'],
      },
      {
        $id: ID.custom('array'),
        key: 'array',
        type: AttributeType.Boolean,
        default: null,
      },
      {
        $id: ID.custom('format'),
        key: 'format',
        type: AttributeType.String,
        size: 64,
        default: null,
      },
      {
        $id: ID.custom('formatOptions'),
        key: 'formatOptions',
        type: AttributeType.Json,
        size: 16384,
        default: {},
        filters: ['range', 'enum'],
      },
      {
        $id: ID.custom('filters'),
        key: 'filters',
        type: AttributeType.String,
        size: 64,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('options'),
        key: 'options',
        type: AttributeType.Json,
        size: 16384,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_collection'),
        type: IndexType.Key,
        attributes: ['collectionInternalId'],
        orders: [Order.Asc],
      },
    ],
  },

  indexes: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('_indexes'),
    name: 'Indexes',
    attributes: [
      {
        $id: ID.custom('collectionInternalId'),
        key: 'collectionInternalId',
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('collectionId'),
        key: 'collectionId',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('key'),
        key: 'key',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('type'),
        key: 'type',
        type: AttributeType.String,
        size: 16,
        default: null,
      },
      {
        $id: ID.custom('status'),
        key: 'status',
        type: AttributeType.String,
        size: 16,
        default: null,
      },
      {
        $id: ID.custom('error'),
        key: 'error',
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('attributes'),
        key: 'attributes',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('orders'),
        key: 'orders',
        type: AttributeType.String,
        size: 4,
        default: null,
        array: true,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_db_collection'),
        type: IndexType.Key,
        attributes: ['collectionInternalId'],
        orders: [Order.Asc],
      },
    ],
  },
};
