import { Database, ID } from "@nuvix/database";

export const bucketCollections = {
    files: {
        $collection: ID.custom('buckets'),
        $id: ID.custom('files'),
        $name: 'Files',
        attributes: [
            {
                array: false,
                $id: ID.custom('bucketId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                filters: [],
            },
            {
                array: false,
                $id: ID.custom('bucketInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                filters: [],
            },
            {
                $id: ID.custom('name'),
                type: Database.VAR_STRING,
                format: '',
                size: 2048,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('path'),
                type: Database.VAR_STRING,
                format: '',
                size: 2048,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('signature'),
                type: Database.VAR_STRING,
                format: '',
                size: 2048,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('mimeType'),
                type: Database.VAR_STRING,
                format: '',
                size: 255, // https://tools.ietf.org/html/rfc4288#section-4.2
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('metadata'),
                type: Database.VAR_STRING,
                format: '',
                size: 75000, // https://tools.ietf.org/html/rfc4288#section-4.2
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: ['json'],
            },
            {
                $id: ID.custom('sizeOriginal'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 8,
                signed: false,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('sizeActual'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 8,
                signed: false,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('algorithm'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('comment'),
                type: Database.VAR_STRING,
                format: '',
                size: 2048,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('openSSLVersion'),
                type: Database.VAR_STRING,
                format: '',
                size: 64,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('openSSLCipher'),
                type: Database.VAR_STRING,
                format: '',
                size: 64,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('openSSLTag'),
                type: Database.VAR_STRING,
                format: '',
                size: 2048,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('openSSLIV'),
                type: Database.VAR_STRING,
                format: '',
                size: 2048,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('chunksTotal'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: false,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('chunksUploaded'),
                type: Database.VAR_INTEGER,
                format: '',
                size: 0,
                signed: false,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('search'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_search'),
                type: Database.INDEX_FULLTEXT,
                attributes: ['search'],
                lengths: [],
                orders: [],
            },
            {
                $id: ID.custom('_key_bucket'),
                type: Database.INDEX_KEY,
                attributes: ['bucketId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_name'),
                type: Database.INDEX_KEY,
                attributes: ['name'],
                lengths: [256],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_signature'),
                type: Database.INDEX_KEY,
                attributes: ['signature'],
                lengths: [256],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_mimeType'),
                type: Database.INDEX_KEY,
                attributes: ['mimeType'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_sizeOriginal'),
                type: Database.INDEX_KEY,
                attributes: ['sizeOriginal'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_chunksTotal'),
                type: Database.INDEX_KEY,
                attributes: ['chunksTotal'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_chunksUploaded'),
                type: Database.INDEX_KEY,
                attributes: ['chunksUploaded'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
        ],
    },
    objects: {
        $collection: ID.custom('buckets'),
        $id: ID.custom('objects'),
        $name: 'Objects',
        attributes: [
            {
                array: false,
                $id: ID.custom('bucketId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: false,
                default: null,
                filters: [],
            },
            {
                array: false,
                $id: ID.custom('bucketInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                filters: [],
            },
            {
                $id: ID.custom('name'),
                type: Database.VAR_STRING,
                format: '',
                size: 5000,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('version'),
                type: Database.VAR_STRING,
                format: '',
                size: 255,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('tokens'),
                type: Database.VAR_STRING,
                format: '',
                size: 1000,
                signed: true,
                required: true,
                default: null,
                array: true,
                filters: [],
            },
            {
                $id: ID.custom('metadata'),
                type: Database.VAR_STRING,
                format: '',
                size: 75000,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: ['json'],
            },
            {
                $id: ID.custom('search'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_key_search'),
                type: Database.INDEX_FULLTEXT,
                attributes: ['search'],
                lengths: [],
                orders: [],
            },
            {
                $id: ID.custom('_key_bucket'),
                type: Database.INDEX_KEY,
                attributes: ['bucketId'],
                lengths: [Database.LENGTH_KEY],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_name'),
                type: Database.INDEX_KEY,
                attributes: ['name'],
                lengths: [256],
                orders: [Database.ORDER_ASC],
            },
        ],
    },
};

export const dbCollections = {
    collections: {
        $collection: ID.custom('databases'),
        $id: ID.custom('collections'),
        name: 'Collections',
        attributes: [
            {
                $id: ID.custom('databaseInternalId'),
                type: Database.VAR_STRING,
                format: '',
                size: Database.LENGTH_KEY,
                signed: true,
                required: true,
                default: null,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('databaseId'),
                type: Database.VAR_STRING,
                signed: true,
                size: Database.LENGTH_KEY,
                format: '',
                filters: [],
                required: true,
                default: null,
                array: false,
            },
            {
                $id: ID.custom('name'),
                type: Database.VAR_STRING,
                size: 256,
                required: true,
                signed: true,
                array: false,
                filters: [],
            },
            {
                $id: ID.custom('enabled'),
                type: Database.VAR_BOOLEAN,
                signed: true,
                size: 0,
                format: '',
                filters: [],
                required: true,
                default: null,
                array: false,
            },
            {
                $id: ID.custom('documentSecurity'),
                type: Database.VAR_BOOLEAN,
                signed: true,
                size: 0,
                format: '',
                filters: [],
                required: true,
                default: null,
                array: false,
            },
            {
                $id: ID.custom('attributes'),
                type: Database.VAR_STRING,
                size: 1000000,
                required: false,
                signed: true,
                array: false,
                filters: ['subQueryAttributes'],
            },
            {
                $id: ID.custom('indexes'),
                type: Database.VAR_STRING,
                size: 1000000,
                required: false,
                signed: true,
                array: false,
                filters: ['subQueryIndexes'],
            },
            {
                $id: ID.custom('search'),
                type: Database.VAR_STRING,
                format: '',
                size: 16384,
                signed: true,
                required: false,
                default: null,
                array: false,
                filters: [],
            },
        ],
        indexes: [
            {
                $id: ID.custom('_fulltext_search'),
                type: Database.INDEX_FULLTEXT,
                attributes: ['search'],
                lengths: [],
                orders: [],
            },
            {
                $id: ID.custom('_key_name'),
                type: Database.INDEX_KEY,
                attributes: ['name'],
                lengths: [256],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_enabled'),
                type: Database.INDEX_KEY,
                attributes: ['enabled'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
            {
                $id: ID.custom('_key_documentSecurity'),
                type: Database.INDEX_KEY,
                attributes: ['documentSecurity'],
                lengths: [],
                orders: [Database.ORDER_ASC],
            },
        ],
    },
};