import {
  ID,
  Database,
  AttributeType,
  IndexType,
  Order,
  Collection,
} from '@nuvix-tech/db';
import { commonCollections } from './common';

export const projectCollections: Record<string, Collection> = {
  functions: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('functions'),
    name: 'Functions',
    attributes: [
      {
        $id: ID.custom('execute'),
        key: ID.custom('execute'),
        type: AttributeType.String,
        size: 128,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('name'),
        key: ID.custom('name'),
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('enabled'),
        key: ID.custom('enabled'),
        type: AttributeType.Boolean,
        required: true,
      },
      {
        $id: ID.custom('live'),
        key: ID.custom('live'),
        type: AttributeType.Boolean,
        required: true,
      },
      {
        $id: ID.custom('installationId'),
        key: ID.custom('installationId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('installationInternalId'),
        key: ID.custom('installationInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('providerRepositoryId'),
        key: ID.custom('providerRepositoryId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('repositoryId'),
        key: ID.custom('repositoryId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('repositoryInternalId'),
        key: ID.custom('repositoryInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('providerBranch'),
        key: ID.custom('providerBranch'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('providerRootDirectory'),
        key: ID.custom('providerRootDirectory'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('providerSilentMode'),
        key: ID.custom('providerSilentMode'),
        type: AttributeType.Boolean,
        default: false,
      },
      {
        $id: ID.custom('logging'),
        key: ID.custom('logging'),
        type: AttributeType.Boolean,
        required: true,
      },
      {
        $id: ID.custom('runtime'),
        key: ID.custom('runtime'),
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('deploymentInternalId'),
        key: ID.custom('deploymentInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('deployment'),
        key: ID.custom('deployment'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('vars'),
        key: ID.custom('vars'),
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryVariables'],
      },
      {
        $id: ID.custom('varsProject'),
        key: ID.custom('varsProject'),
        type: AttributeType.Virtual,
        default: null,
        filters: ['subQueryProjectVariables'],
      },
      {
        $id: ID.custom('events'),
        key: ID.custom('events'),
        type: AttributeType.String,
        size: 256,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('scheduleInternalId'),
        key: ID.custom('scheduleInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('scheduleId'),
        key: ID.custom('scheduleId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('schedule'),
        key: ID.custom('schedule'),
        type: AttributeType.String,
        size: 128,
        default: null,
      },
      {
        $id: ID.custom('timeout'),
        key: ID.custom('timeout'),
        type: AttributeType.Integer,
        default: null,
      },
      {
        $id: ID.custom('search'),
        key: ID.custom('search'),
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
      {
        $id: ID.custom('version'),
        key: ID.custom('version'),
        type: AttributeType.String,
        size: 8,
        default: 'v4',
      },
      {
        $id: ID.custom('entrypoint'),
        key: ID.custom('entrypoint'),
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
      {
        $id: ID.custom('commands'),
        key: ID.custom('commands'),
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
      {
        $id: ID.custom('specification'),
        key: ID.custom('specification'),
        type: AttributeType.String,
        size: 128,
      },
      {
        $id: ID.custom('scopes'),
        key: ID.custom('scopes'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: [],
        array: true,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
      {
        $id: ID.custom('_key_name'),
        type: IndexType.Key,
        attributes: ['name'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_enabled'),
        type: IndexType.Key,
        attributes: ['enabled'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_installationId'),
        type: IndexType.Key,
        attributes: ['installationId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_installationInternalId'),
        type: IndexType.Key,
        attributes: ['installationInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_providerRepositoryId'),
        type: IndexType.Key,
        attributes: ['providerRepositoryId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_repositoryId'),
        type: IndexType.Key,
        attributes: ['repositoryId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_repositoryInternalId'),
        type: IndexType.Key,
        attributes: ['repositoryInternalId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_runtime'),
        type: IndexType.Key,
        attributes: ['runtime'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_deployment'),
        type: IndexType.Key,
        attributes: ['deployment'],
        orders: [Order.Asc],
      },
    ],
  },

  deployments: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('deployments'),
    name: 'Deployments',
    attributes: [
      {
        $id: ID.custom('resourceInternalId'),
        key: ID.custom('resourceInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('resourceId'),
        key: ID.custom('resourceId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('resourceType'),
        key: ID.custom('resourceType'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('buildInternalId'),
        key: ID.custom('buildInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('buildId'),
        key: ID.custom('buildId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('entrypoint'),
        key: ID.custom('entrypoint'),
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('commands'),
        key: ID.custom('commands'),
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('path'),
        key: ID.custom('path'),
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('type'),
        key: ID.custom('type'),
        type: AttributeType.String,
        size: 2048,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('installationId'),
        key: ID.custom('installationId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('installationInternalId'),
        key: ID.custom('installationInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('providerRepositoryId'),
        key: ID.custom('providerRepositoryId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('repositoryId'),
        key: ID.custom('repositoryId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('repositoryInternalId'),
        key: ID.custom('repositoryInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('providerRepositoryName'),
        key: ID.custom('providerRepositoryName'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('providerRepositoryOwner'),
        key: ID.custom('providerRepositoryOwner'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('providerRepositoryUrl'),
        key: ID.custom('providerRepositoryUrl'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('providerCommitHash'),
        key: ID.custom('providerCommitHash'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('providerCommitAuthorUrl'),
        key: ID.custom('providerCommitAuthorUrl'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('providerCommitAuthor'),
        key: ID.custom('providerCommitAuthor'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('providerCommitMessage'),
        key: ID.custom('providerCommitMessage'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('providerCommitUrl'),
        key: ID.custom('providerCommitUrl'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('providerBranch'),
        key: ID.custom('providerBranch'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('providerBranchUrl'),
        key: ID.custom('providerBranchUrl'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('providerRootDirectory'),
        key: ID.custom('providerRootDirectory'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
      },
      {
        $id: ID.custom('providerCommentId'),
        key: ID.custom('providerCommentId'),
        type: AttributeType.String,
        size: 2048,
      },
      {
        $id: ID.custom('size'),
        key: ID.custom('size'),
        type: AttributeType.Integer,
        default: null,
      },
      {
        $id: ID.custom('metadata'),
        key: ID.custom('metadata'),
        type: AttributeType.Json,
        size: 16384, // https://tools.ietf.org/html/rfc4288#section-4.2
        default: null,
      },
      {
        $id: ID.custom('chunksTotal'),
        key: ID.custom('chunksTotal'),
        type: AttributeType.Integer,
        default: null,
      },
      {
        $id: ID.custom('chunksUploaded'),
        key: ID.custom('chunksUploaded'),
        type: AttributeType.Integer,
        default: null,
      },
      {
        $id: ID.custom('search'),
        key: ID.custom('search'),
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
      {
        $id: ID.custom('activate'),
        key: ID.custom('activate'),
        type: AttributeType.Boolean,
        default: false,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_resource'),
        type: IndexType.Key,
        attributes: ['resourceId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_resource_type'),
        type: IndexType.Key,
        attributes: ['resourceType'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
      {
        $id: ID.custom('_key_size'),
        type: IndexType.Key,
        attributes: ['size'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_buildId'),
        type: IndexType.Key,
        attributes: ['buildId'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_activate'),
        type: IndexType.Key,
        attributes: ['activate'],
        orders: [Order.Asc],
      },
    ],
  },

  builds: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('builds'),
    name: 'Builds',
    attributes: [
      {
        $id: ID.custom('startTime'),
        key: ID.custom('startTime'),
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('endTime'),
        key: ID.custom('endTime'),
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('duration'),
        key: ID.custom('duration'),
        type: AttributeType.Integer,
        default: null,
      },
      {
        $id: ID.custom('size'),
        key: ID.custom('size'),
        type: AttributeType.Integer,
        default: null,
      },
      {
        $id: ID.custom('deploymentInternalId'),
        key: ID.custom('deploymentInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('deploymentId'),
        key: ID.custom('deploymentId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('runtime'),
        key: ID.custom('runtime'),
        type: AttributeType.String,
        size: 2048,
        required: true,
        default: '',
      },
      {
        $id: ID.custom('status'),
        key: ID.custom('status'),
        type: AttributeType.String,
        size: 256,
        required: true,
        default: 'processing',
      },
      {
        $id: ID.custom('path'),
        key: ID.custom('path'),
        type: AttributeType.String,
        size: 2048,
        default: '',
      },
      {
        $id: ID.custom('logs'),
        key: ID.custom('logs'),
        type: AttributeType.Json,
        default: {},
      },
      {
        $id: ID.custom('sourceType'),
        key: ID.custom('sourceType'),
        type: AttributeType.String,
        size: 2048,
        required: true,
        default: 'local',
      },
      {
        $id: ID.custom('source'),
        key: ID.custom('source'),
        type: AttributeType.String,
        size: 2048,
        required: true,
        default: '',
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_deployment'),
        type: IndexType.Key,
        attributes: ['deploymentId'],

        orders: [Order.Asc],
      },
    ],
  },

  executions: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('executions'),
    name: 'Executions',
    attributes: [
      {
        $id: ID.custom('functionInternalId'),
        key: ID.custom('functionInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('functionId'),
        key: ID.custom('functionId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('deploymentInternalId'),
        key: ID.custom('deploymentInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('deploymentId'),
        key: ID.custom('deploymentId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('trigger'),
        key: ID.custom('trigger'),
        type: AttributeType.String,
        size: 128,
        default: null,
      },
      {
        $id: ID.custom('status'),
        key: ID.custom('status'),
        type: AttributeType.String,
        size: 128,
        default: null,
      },
      {
        $id: ID.custom('duration'),
        key: ID.custom('duration'),
        type: AttributeType.Float,
        default: null,
      },
      {
        $id: ID.custom('errors'),
        key: ID.custom('errors'),
        type: AttributeType.String,
        size: 1000000,
        default: null,
      },
      {
        $id: ID.custom('logs'),
        key: ID.custom('logs'),
        type: AttributeType.Json,
        default: null,
      },
      {
        $id: ID.custom('requestMethod'),
        key: ID.custom('requestMethod'),
        type: AttributeType.String,
        size: 128,
        default: null,
      },
      {
        $id: ID.custom('requestPath'),
        key: ID.custom('requestPath'),
        type: AttributeType.String,
        size: 2048,
        default: null,
      },
      {
        $id: ID.custom('requestHeaders'),
        key: ID.custom('requestHeaders'),
        type: AttributeType.String,
        size: 16384,
        default: null,
        filters: ['json'],
      },
      {
        $id: ID.custom('responseStatusCode'),
        key: ID.custom('responseStatusCode'),
        type: AttributeType.Integer,
        default: null,
      },
      {
        $id: ID.custom('responseHeaders'),
        key: ID.custom('responseHeaders'),
        type: AttributeType.Json,
        size: 16384,
        default: null,
      },
      {
        $id: ID.custom('search'),
        key: ID.custom('search'),
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
      {
        $id: ID.custom('scheduledAt'),
        key: ID.custom('scheduledAt'),
        type: AttributeType.Timestamptz,
        default: null,
      },
      {
        $id: ID.custom('scheduleInternalId'),
        key: ID.custom('scheduleInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('scheduleId'),
        key: ID.custom('scheduleId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
    ],
    indexes: [
      {
        $id: ID.custom('_key_function'),
        type: IndexType.Key,
        attributes: ['functionId'],

        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_fulltext_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
      {
        $id: ID.custom('_key_trigger'),
        type: IndexType.Key,
        attributes: ['trigger'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_status'),
        type: IndexType.Key,
        attributes: ['status'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_requestMethod'),
        type: IndexType.Key,
        attributes: ['requestMethod'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_requestPath'),
        type: IndexType.Key,
        attributes: ['requestPath'],

        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_deployment'),
        type: IndexType.Key,
        attributes: ['deploymentId'],

        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_responseStatusCode'),
        type: IndexType.Key,
        attributes: ['responseStatusCode'],
        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_key_duration'),
        type: IndexType.Key,
        attributes: ['duration'],
        orders: [Order.Asc],
      },
    ],
  },

  variables: {
    $collection: Database.METADATA,
    $id: 'variables',
    name: 'variables',
    attributes: [
      {
        $id: ID.custom('resourceType'),
        key: ID.custom('resourceType'),
        type: AttributeType.String,
        size: 100,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('resourceInternalId'),
        key: ID.custom('resourceInternalId'),
        type: AttributeType.Integer,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: ID.custom('resourceId'),
        key: ID.custom('resourceId'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: 'key',
        key: 'key',
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        default: null,
      },
      {
        $id: 'value',
        key: 'value',
        type: AttributeType.String,
        size: 8192,
        required: true,
        default: null,
        filters: ['encrypt'],
      },
      {
        $id: ID.custom('search'),
        key: ID.custom('search'),
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
    ],
    indexes: [
      {
        $id: '_key_resourceInternalId',
        type: IndexType.Key,
        attributes: ['resourceInternalId'],

        orders: [],
      },
      {
        $id: '_key_resourceType',
        type: IndexType.Key,
        attributes: ['resourceType'],
        orders: [Order.Asc],
      },
      {
        $id: '_key_resourceId_resourceType',
        type: IndexType.Key,
        attributes: ['resourceId', 'resourceType'],
        orders: [Order.Asc, Order.Asc],
      },
      {
        $id: '_key_uniqueKey',
        type: IndexType.Unique,
        attributes: ['resourceId', 'key', 'resourceType'],
        orders: [Order.Asc, Order.Asc, Order.Asc],
      },
      {
        $id: '_key_key',
        type: IndexType.Key,
        attributes: ['key'],

        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_fulltext_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
    ],
  },

  migrations: {
    $collection: ID.custom(Database.METADATA),
    $id: ID.custom('migrations'),
    name: 'Migrations',
    attributes: [
      {
        $id: ID.custom('status'),
        key: ID.custom('status'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('stage'),
        key: ID.custom('stage'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('source'),
        key: ID.custom('source'),
        type: AttributeType.String,
        size: 8192,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('credentials'),
        key: ID.custom('credentials'),
        type: AttributeType.String,
        size: 65536,
        default: [],
        filters: ['json', 'encrypt'],
      },
      {
        $id: ID.custom('resources'),
        key: ID.custom('resources'),
        type: AttributeType.String,
        size: Database.LENGTH_KEY,
        required: true,
        default: [],
        array: true,
      },
      {
        $id: ID.custom('statusCounters'),
        key: ID.custom('statusCounters'),
        type: AttributeType.Json,
        size: 3000,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('resourceData'),
        key: ID.custom('resourceData'),
        type: AttributeType.Json,
        size: 131070,
        required: true,
        default: null,
      },
      {
        $id: ID.custom('errors'),
        key: ID.custom('errors'),
        type: AttributeType.String,
        size: 65535,
        required: true,
        default: null,
        array: true,
      },
      {
        $id: ID.custom('search'),
        key: ID.custom('search'),
        type: AttributeType.String,
        size: 16384,
        default: null,
      },
    ],
    indexes: [
      {
        $id: '_key_status',
        type: IndexType.Key,
        attributes: ['status'],

        orders: [Order.Asc],
      },
      {
        $id: '_key_stage',
        type: IndexType.Key,
        attributes: ['stage'],

        orders: [Order.Asc],
      },
      {
        $id: '_key_source',
        type: IndexType.Key,
        attributes: ['source'],

        orders: [Order.Asc],
      },
      {
        $id: ID.custom('_fulltext_search'),
        type: IndexType.FullText,
        attributes: ['search'],
        orders: [],
      },
    ],
  },

  ...commonCollections('project'),
};
