import { AttributeType, type Collection, Database, ID, IndexType } from '@nuvix/db'

const users: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('users'),
  name: 'Users',
  documentSecurity: true,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('name'),
      key: 'name',
      type: AttributeType.String,
      size: 256,
    },
    {
      $id: ID.custom('email'),
      key: 'email',
      type: AttributeType.String,
      size: 320,
    },
    {
      $id: ID.custom('phone'),
      key: 'phone',
      type: AttributeType.String,
      size: 16,
    },
    {
      $id: ID.custom('status'),
      key: 'status',
      type: AttributeType.Boolean,
    },
    {
      $id: ID.custom('labels'),
      key: 'labels',
      type: AttributeType.String,
      size: 128,
      array: true,
    },
    {
      $id: ID.custom('passwordHistory'),
      key: 'passwordHistory',
      type: AttributeType.String,
      size: 16384,
      array: true,
    },
    {
      $id: ID.custom('password'),
      key: 'password',
      type: AttributeType.String,
      size: 16384,
      filters: ['encrypt'],
    },
    {
      $id: ID.custom('hash'),
      key: 'hash',
      type: AttributeType.String,
      size: 256,
      default: 'argon2id',
    },
    {
      $id: ID.custom('hashOptions'),
      key: 'hashOptions',
      type: AttributeType.Json,
      filters: ['json'],
      __type: 'Record<string, unknown>',
    },
    {
      $id: ID.custom('passwordUpdate'),
      key: 'passwordUpdate',
      type: AttributeType.Timestamptz,
    },
    {
      $id: ID.custom('prefs'),
      key: 'prefs',
      type: AttributeType.Json,
      default: {},
      filters: ['json'],
      __type: 'Record<string, unknown>',
    },
    {
      $id: ID.custom('registration'),
      key: 'registration',
      type: AttributeType.Timestamptz,
    },
    {
      $id: ID.custom('emailVerification'),
      key: 'emailVerification',
      type: AttributeType.Boolean,
    },
    {
      $id: ID.custom('phoneVerification'),
      key: 'phoneVerification',
      type: AttributeType.Boolean,
    },
    {
      $id: ID.custom('reset'),
      key: 'reset',
      type: AttributeType.Boolean,
    },
    {
      $id: ID.custom('mfa'),
      key: 'mfa',
      type: AttributeType.Boolean,
    },
    {
      $id: ID.custom('mfaRecoveryCodes'),
      key: 'mfaRecoveryCodes',
      type: AttributeType.String,
      size: 256,
      array: true,
      default: [],
      filters: ['encrypt'],
      __type: 'string[]',
    },
    {
      $id: ID.custom('authenticators'),
      key: 'authenticators',
      type: AttributeType.Virtual,
      filters: ['subQueryAuthenticators'],
      __type: 'Authenticators[]',
    },
    {
      $id: ID.custom('sessions'),
      key: 'sessions',
      type: AttributeType.Virtual,
      filters: ['subQuerySessions'],
      __type: 'Sessions[]',
    },
    {
      $id: ID.custom('tokens'),
      key: 'tokens',
      type: AttributeType.Virtual,
      filters: ['subQueryTokens'],
      __type: 'Tokens[]',
    },
    {
      $id: ID.custom('memberships'),
      key: 'memberships',
      type: AttributeType.Virtual,
      filters: ['subQueryMemberships'],
      __type: 'Memberships[]',
    },
    {
      $id: ID.custom('targets'),
      key: 'targets',
      type: AttributeType.Virtual,
      filters: ['subQueryTargets'],
      __type: 'Targets[]',
    },
    {
      $id: ID.custom('search'),
      key: 'search',
      type: AttributeType.String,
      size: 16384,
      filters: ['userSearch'],
    },
    {
      $id: ID.custom('accessedAt'),
      key: 'accessedAt',
      type: AttributeType.Timestamptz,
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_name'),
      key: 'idx_name',
      type: IndexType.Key,
      attributes: ['name'],
    },
    {
      $id: ID.custom('idx_email'),
      key: 'idx_email',
      type: IndexType.Unique,
      attributes: ['email'],
    },
    {
      $id: ID.custom('idx_phone'),
      key: 'idx_phone',
      type: IndexType.Unique,
      attributes: ['phone'],
    },
    {
      $id: ID.custom('idx_status'),
      key: 'idx_status',
      type: IndexType.Key,
      attributes: ['status'],
    },
    {
      $id: ID.custom('idx_registration'),
      key: 'idx_registration',
      type: IndexType.Key,
      attributes: ['registration'],
    },
    {
      $id: ID.custom('idx_email_verification'),
      key: 'idx_email_verification',
      type: IndexType.Key,
      attributes: ['emailVerification'],
    },
    {
      $id: ID.custom('idx_phone_verification'),
      key: 'idx_phone_verification',
      type: IndexType.Key,
      attributes: ['phoneVerification'],
    },
    {
      $id: ID.custom('idx_search'),
      key: 'idx_search',
      type: IndexType.FullText,
      attributes: ['search'],
    },
    {
      $id: ID.custom('idx_accessed_at'),
      key: 'idx_accessed_at',
      type: IndexType.Key,
      attributes: ['accessedAt'],
    },
  ],
}

const teams: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('teams'),
  name: 'Teams',
  documentSecurity: true,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('name'),
      key: 'name',
      type: AttributeType.String,
      size: 128,
      required: true,
    },
    {
      $id: ID.custom('total'),
      key: 'total',
      type: AttributeType.Integer,
      size: 8,
      default: 0,
    },
    {
      $id: ID.custom('prefs'),
      key: 'prefs',
      type: AttributeType.Json,
      default: {},
      filters: ['json'],
      __type: 'Record<string, unknown>',
    },
    {
      $id: ID.custom('memberships'),
      key: 'memberships',
      type: AttributeType.Virtual,
      filters: ['subQueryMemberships'],
      __type: 'Memberships[]',
    },
    {
      $id: ID.custom('search'),
      key: 'search',
      type: AttributeType.String,
      size: 16384,
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_name'),
      key: 'idx_name',
      type: IndexType.Key,
      attributes: ['name'],
    },
    {
      $id: ID.custom('idx_search'),
      key: 'idx_search',
      type: IndexType.FullText,
      attributes: ['search'],
    },
  ],
}

const tokens: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('tokens'),
  name: 'Tokens',
  documentSecurity: true,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('userInternalId'),
      key: 'userInternalId',
      type: AttributeType.Integer,
      size: 8,
      required: true,
    },
    {
      $id: ID.custom('userId'),
      key: 'userId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
    },
    {
      $id: ID.custom('type'),
      key: 'type',
      type: AttributeType.Integer,
      required: true,
    },
    {
      $id: ID.custom('secret'),
      key: 'secret',
      type: AttributeType.String,
      size: 1000,
      filters: ['encrypt'],
    },
    {
      $id: ID.custom('expire'),
      key: 'expire',
      type: AttributeType.Timestamptz,
    },
    {
      $id: ID.custom('userAgent'),
      key: 'userAgent',
      type: AttributeType.String,
      size: 16384,
    },
    {
      $id: ID.custom('ip'),
      key: 'ip',
      type: AttributeType.String,
      size: 45,
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_user_internal_id'),
      key: 'idx_user_internal_id',
      type: IndexType.Key,
      attributes: ['userInternalId'],
    },
  ],
}

const authenticators: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('authenticators'),
  name: 'Authenticators',
  documentSecurity: true,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('userInternalId'),
      key: 'userInternalId',
      type: AttributeType.Integer,
      size: 8,
    },
    {
      $id: ID.custom('userId'),
      key: 'userId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
    },
    {
      $id: ID.custom('type'),
      key: 'type',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
    },
    {
      $id: ID.custom('verified'),
      key: 'verified',
      type: AttributeType.Boolean,
      default: false,
    },
    {
      $id: ID.custom('data'),
      key: 'data',
      type: AttributeType.String,
      size: 65535,
      filters: ['json', 'encrypt'],
      __type: 'Record<string, unknown>',
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_user_internal_id'),
      key: 'idx_user_internal_id',
      type: IndexType.Key,
      attributes: ['userInternalId'],
    },
  ],
}

const challenges: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('challenges'),
  name: 'Challenges',
  documentSecurity: true,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('userInternalId'),
      key: 'userInternalId',
      type: AttributeType.Integer,
      size: 8,
    },
    {
      $id: ID.custom('userId'),
      key: 'userId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
    },
    {
      $id: ID.custom('type'),
      key: 'type',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
    },
    {
      $id: ID.custom('token'),
      key: 'token',
      type: AttributeType.String,
      size: 512,
      filters: ['encrypt'],
    },
    {
      $id: ID.custom('code'),
      key: 'code',
      type: AttributeType.String,
      size: 512,
      filters: ['encrypt'],
    },
    {
      $id: ID.custom('expire'),
      key: 'expire',
      type: AttributeType.Timestamptz,
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_user_internal_id'),
      key: 'idx_user_internal_id',
      type: IndexType.Key,
      attributes: ['userInternalId'],
    },
  ],
}

const sessions: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('sessions'),
  name: 'Sessions',
  documentSecurity: true,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('userInternalId'),
      key: 'userInternalId',
      type: AttributeType.Integer,
      size: 8,
      required: true,
    },
    {
      $id: ID.custom('userId'),
      key: 'userId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
    },
    {
      $id: ID.custom('provider'),
      key: 'provider',
      type: AttributeType.String,
      size: 128,
    },
    {
      $id: ID.custom('providerUid'),
      key: 'providerUid',
      type: AttributeType.String,
      size: 2048,
    },
    {
      $id: ID.custom('providerAccessToken'),
      key: 'providerAccessToken',
      type: AttributeType.String,
      size: 16384,
      filters: ['encrypt'],
    },
    {
      $id: ID.custom('providerAccessTokenExpiry'),
      key: 'providerAccessTokenExpiry',
      type: AttributeType.Timestamptz,
    },
    {
      $id: ID.custom('providerRefreshToken'),
      key: 'providerRefreshToken',
      type: AttributeType.String,
      size: 16384,
      filters: ['encrypt'],
    },
    {
      $id: ID.custom('secret'),
      key: 'secret',
      type: AttributeType.String,
      size: 512,
      filters: ['encrypt'],
    },
    {
      $id: ID.custom('userAgent'),
      key: 'userAgent',
      type: AttributeType.String,
      size: 16384,
    },
    {
      $id: ID.custom('ip'),
      key: 'ip',
      type: AttributeType.String,
      size: 45,
    },
    {
      $id: ID.custom('countryCode'),
      key: 'countryCode',
      type: AttributeType.String,
      size: 2,
    },
    {
      $id: ID.custom('osCode'),
      key: 'osCode',
      type: AttributeType.String,
      size: 256,
    },
    {
      $id: ID.custom('osName'),
      key: 'osName',
      type: AttributeType.String,
      size: 256,
    },
    {
      $id: ID.custom('osVersion'),
      key: 'osVersion',
      type: AttributeType.String,
      size: 256,
    },
    {
      $id: ID.custom('clientType'),
      key: 'clientType',
      type: AttributeType.String,
      size: 256,
    },
    {
      $id: ID.custom('clientCode'),
      key: 'clientCode',
      type: AttributeType.String,
      size: 256,
    },
    {
      $id: ID.custom('clientName'),
      key: 'clientName',
      type: AttributeType.String,
      size: 256,
    },
    {
      $id: ID.custom('clientVersion'),
      key: 'clientVersion',
      type: AttributeType.String,
      size: 256,
    },
    {
      $id: ID.custom('clientEngine'),
      key: 'clientEngine',
      type: AttributeType.String,
      size: 256,
    },
    {
      $id: ID.custom('clientEngineVersion'),
      key: 'clientEngineVersion',
      type: AttributeType.String,
      size: 256,
    },
    {
      $id: ID.custom('deviceName'),
      key: 'deviceName',
      type: AttributeType.String,
      size: 256,
    },
    {
      $id: ID.custom('deviceBrand'),
      key: 'deviceBrand',
      type: AttributeType.String,
      size: 256,
    },
    {
      $id: ID.custom('deviceModel'),
      key: 'deviceModel',
      type: AttributeType.String,
      size: 256,
    },
    {
      $id: ID.custom('factors'),
      key: 'factors',
      type: AttributeType.String,
      size: 256,
      array: true,
      default: [],
    },
    {
      $id: ID.custom('expire'),
      key: 'expire',
      type: AttributeType.Timestamptz,
      required: true,
    },
    {
      $id: ID.custom('mfaUpdatedAt'),
      key: 'mfaUpdatedAt',
      type: AttributeType.Timestamptz,
    },
    {
      $id: ID.custom('tokens'),
      key: 'tokens',
      type: AttributeType.Virtual,
      filters: ['subQueryTokens'],
      __type: 'Tokens[]',
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_provider_provider_uid'),
      key: 'idx_provider_provider_uid',
      type: IndexType.Key,
      attributes: ['provider', 'providerUid'],
    },
    {
      $id: ID.custom('idx_user_internal_id'),
      key: 'idx_user_internal_id',
      type: IndexType.Key,
      attributes: ['userInternalId'],
    },
  ],
}

const identities: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('identities'),
  name: 'Identities',
  documentSecurity: true,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('userInternalId'),
      key: 'userInternalId',
      type: AttributeType.Integer,
      size: 8,
    },
    {
      $id: ID.custom('userId'),
      key: 'userId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
    },
    {
      $id: ID.custom('provider'),
      key: 'provider',
      type: AttributeType.String,
      size: 128,
    },
    {
      $id: ID.custom('providerUid'),
      key: 'providerUid',
      type: AttributeType.String,
      size: 2048,
    },
    {
      $id: ID.custom('providerEmail'),
      key: 'providerEmail',
      type: AttributeType.String,
      size: 320,
    },
    {
      $id: ID.custom('providerAccessToken'),
      key: 'providerAccessToken',
      type: AttributeType.String,
      size: 16384,
      filters: ['encrypt'],
    },
    {
      $id: ID.custom('providerAccessTokenExpiry'),
      key: 'providerAccessTokenExpiry',
      type: AttributeType.Timestamptz,
    },
    {
      $id: ID.custom('providerRefreshToken'),
      key: 'providerRefreshToken',
      type: AttributeType.String,
      size: 16384,
      filters: ['encrypt'],
    },
    {
      $id: ID.custom('secrets'),
      key: 'secrets',
      type: AttributeType.String,
      size: 16384,
      filters: ['json', 'encrypt'],
      __type: 'Record<string, unknown>',
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_user_provider_uid'),
      key: 'idx_user_provider_uid',
      type: IndexType.Unique,
      attributes: ['userInternalId', 'provider', 'providerUid'],
    },
    {
      $id: ID.custom('idx_provider_uid'),
      key: 'idx_provider_uid',
      type: IndexType.Unique,
      attributes: ['provider', 'providerUid'],
    },
    {
      $id: ID.custom('idx_user_id'),
      key: 'idx_user_id',
      type: IndexType.Key,
      attributes: ['userId'],
    },
    {
      $id: ID.custom('idx_user_internal_id'),
      key: 'idx_user_internal_id',
      type: IndexType.Key,
      attributes: ['userInternalId'],
    },
  ],
}

const targets: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('targets'),
  name: 'Targets',
  documentSecurity: true,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('userId'),
      key: 'userId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
      required: true,
    },
    {
      $id: ID.custom('userInternalId'),
      key: 'userInternalId',
      type: AttributeType.Integer,
      size: 8,
      required: true,
    },
    {
      $id: ID.custom('sessionId'),
      key: 'sessionId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
    },
    {
      $id: ID.custom('sessionInternalId'),
      key: 'sessionInternalId',
      type: AttributeType.Integer,
      size: 8,
    },
    {
      $id: ID.custom('providerType'),
      key: 'providerType',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
      required: true,
    },
    {
      $id: ID.custom('providerId'),
      key: 'providerId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
    },
    {
      $id: ID.custom('providerInternalId'),
      key: 'providerInternalId',
      type: AttributeType.Integer,
      size: 8,
    },
    {
      $id: ID.custom('identifier'),
      key: 'identifier',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
      required: true,
    },
    {
      $id: ID.custom('name'),
      key: 'name',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
    },
    {
      $id: ID.custom('expired'),
      key: 'expired',
      type: AttributeType.Boolean,
      default: false,
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_user_id'),
      key: 'idx_user_id',
      type: IndexType.Key,
      attributes: ['userId'],
    },
    {
      $id: ID.custom('idx_user_internal_id'),
      key: 'idx_user_internal_id',
      type: IndexType.Key,
      attributes: ['userInternalId'],
    },
    {
      $id: ID.custom('idx_provider_id'),
      key: 'idx_provider_id',
      type: IndexType.Key,
      attributes: ['providerId'],
    },
    {
      $id: ID.custom('idx_identifier'),
      key: 'idx_identifier',
      type: IndexType.Unique,
      attributes: ['identifier'],
    },
  ],
}

const memberships: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('memberships'),
  name: 'Memberships',
  documentSecurity: true,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('userInternalId'),
      key: 'userInternalId',
      type: AttributeType.Integer,
      size: 8,
      required: true,
    },
    {
      $id: ID.custom('userId'),
      key: 'userId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
    },
    {
      $id: ID.custom('teamInternalId'),
      key: 'teamInternalId',
      type: AttributeType.Integer,
      size: 8,
      required: true,
    },
    {
      $id: ID.custom('teamId'),
      key: 'teamId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
    },
    {
      $id: ID.custom('roles'),
      key: 'roles',
      type: AttributeType.String,
      size: 128,
      array: true,
      default: [],
    },
    {
      $id: ID.custom('invited'),
      key: 'invited',
      type: AttributeType.Timestamptz,
    },
    {
      $id: ID.custom('joined'),
      key: 'joined',
      type: AttributeType.Timestamptz,
    },
    {
      $id: ID.custom('confirm'),
      key: 'confirm',
      type: AttributeType.Boolean,
    },
    {
      $id: ID.custom('secret'),
      key: 'secret',
      type: AttributeType.String,
      size: 1026,
      filters: ['encrypt'],
    },
    {
      $id: ID.custom('search'),
      key: 'search',
      type: AttributeType.String,
      size: 16384,
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_unique'),
      key: 'idx_unique',
      type: IndexType.Unique,
      attributes: ['teamInternalId', 'userInternalId'],
    },
    {
      $id: ID.custom('idx_user_internal_id'),
      key: 'idx_user_internal_id',
      type: IndexType.Key,
      attributes: ['userInternalId'],
    },
    {
      $id: ID.custom('idx_team_internal_id'),
      key: 'idx_team_internal_id',
      type: IndexType.Key,
      attributes: ['teamInternalId'],
    },
    {
      $id: ID.custom('idx_search'),
      key: 'idx_search',
      type: IndexType.FullText,
      attributes: ['search'],
    },
    {
      $id: ID.custom('idx_user_id'),
      key: 'idx_user_id',
      type: IndexType.Key,
      attributes: ['userId'],
    },
    {
      $id: ID.custom('idx_team_id'),
      key: 'idx_team_id',
      type: IndexType.Key,
      attributes: ['teamId'],
    },
    {
      $id: ID.custom('idx_invited'),
      key: 'idx_invited',
      type: IndexType.Key,
      attributes: ['invited'],
    },
    {
      $id: ID.custom('idx_joined'),
      key: 'idx_joined',
      type: IndexType.Key,
      attributes: ['joined'],
    },
    {
      $id: ID.custom('idx_confirm'),
      key: 'idx_confirm',
      type: IndexType.Key,
      attributes: ['confirm'],
    },
  ],
}

const buckets: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('buckets'),
  name: 'Buckets',
  documentSecurity: true,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('enabled'),
      key: 'enabled',
      type: AttributeType.Boolean,
      required: true,
    },
    {
      $id: ID.custom('name'),
      key: 'name',
      type: AttributeType.String,
      size: 128,
      required: true,
    },
    {
      $id: ID.custom('fileSecurity'),
      key: 'fileSecurity',
      type: AttributeType.Boolean,
    },
    {
      $id: ID.custom('maximumFileSize'),
      key: 'maximumFileSize',
      type: AttributeType.Integer,
      size: 8,
      required: true,
    },
    {
      $id: ID.custom('allowedFileExtensions'),
      key: 'allowedFileExtensions',
      type: AttributeType.String,
      size: 64,
      required: true,
      array: true,
    },
    {
      $id: ID.custom('compression'),
      key: 'compression',
      type: AttributeType.String,
      size: 10,
      required: true,
    },
    {
      $id: ID.custom('encryption'),
      key: 'encryption',
      type: AttributeType.Boolean,
      required: true,
    },
    {
      $id: ID.custom('antivirus'),
      key: 'antivirus',
      type: AttributeType.Boolean,
      required: true,
    },
    {
      $id: ID.custom('files'),
      key: 'files',
      type: AttributeType.Virtual,
      filters: ['subQueryFiles'],
      __type: 'Files[]',
    },
    {
      $id: ID.custom('search'),
      key: 'search',
      type: AttributeType.String,
      size: 16384,
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_name'),
      key: 'idx_name',
      type: IndexType.Key,
      attributes: ['name'],
    },
    {
      $id: ID.custom('idx_search'),
      key: 'idx_search',
      type: IndexType.FullText,
      attributes: ['search'],
    },
    {
      $id: ID.custom('idx_enabled'),
      key: 'idx_enabled',
      type: IndexType.Key,
      attributes: ['enabled'],
    },
  ],
}

const files: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('files'),
  name: 'Files',
  documentSecurity: true,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('bucketId'),
      key: 'bucketId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
    },
    {
      $id: ID.custom('bucketInternalId'),
      key: 'bucketInternalId',
      type: AttributeType.Integer,
      size: 8,
      required: true,
    },
    {
      $id: ID.custom('name'),
      key: 'name',
      type: AttributeType.String,
      size: 2048,
    },
    {
      $id: ID.custom('path'),
      key: 'path',
      type: AttributeType.String,
      size: 2048,
    },
    {
      $id: ID.custom('signature'),
      key: 'signature',
      type: AttributeType.String,
      size: 2048,
    },
    {
      $id: ID.custom('mimeType'),
      key: 'mimeType',
      type: AttributeType.String,
      size: 255,
    },
    {
      $id: ID.custom('sizeOriginal'),
      key: 'sizeOriginal',
      type: AttributeType.Integer,
      size: 8,
      required: true,
    },
    {
      $id: ID.custom('chunksTotal'),
      key: 'chunksTotal',
      type: AttributeType.Integer,
      size: 8,
    },
    {
      $id: ID.custom('chunksUploaded'),
      key: 'chunksUploaded',
      type: AttributeType.Integer,
      size: 8,
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_bucket_id'),
      key: 'idx_bucket_id',
      type: IndexType.Key,
      attributes: ['bucketId'],
    },
    {
      $id: ID.custom('idx_bucket_internal_id'),
      key: 'idx_bucket_internal_id',
      type: IndexType.Key,
      attributes: ['bucketInternalId'],
    },
    {
      $id: ID.custom('idx_signature'),
      key: 'idx_signature',
      type: IndexType.Key,
      attributes: ['signature'],
    },
  ],
}

const stats: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('stats'),
  name: 'Stats',
  documentSecurity: false,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('metric'),
      key: 'metric',
      type: AttributeType.String,
      size: 255,
      required: true,
    },
    {
      $id: ID.custom('region'),
      key: 'region',
      type: AttributeType.String,
      size: 255,
      required: true,
    },
    {
      $id: ID.custom('value'),
      key: 'value',
      type: AttributeType.Integer,
      size: 8,
      required: true,
    },
    {
      $id: ID.custom('time'),
      key: 'time',
      type: AttributeType.Timestamptz,
    },
    {
      $id: ID.custom('period'),
      key: 'period',
      type: AttributeType.String,
      size: 4,
      required: true,
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_time'),
      key: 'idx_time',
      type: IndexType.Key,
      attributes: ['time'],
    },
    {
      $id: ID.custom('idx_metric_period_time'),
      key: 'idx_metric_period_time',
      type: IndexType.Unique,
      attributes: ['metric', 'period', 'time'],
    },
  ],
}

const providers: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('providers'),
  name: 'Providers',
  documentSecurity: true,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('name'),
      key: 'name',
      type: AttributeType.String,
      size: 128,
      required: true,
    },
    {
      $id: ID.custom('provider'),
      key: 'provider',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
      required: true,
    },
    {
      $id: ID.custom('type'),
      key: 'type',
      type: AttributeType.String,
      size: 128,
      required: true,
    },
    {
      $id: ID.custom('enabled'),
      key: 'enabled',
      type: AttributeType.Boolean,
      required: true,
      default: true,
    },
    {
      $id: ID.custom('credentials'),
      key: 'credentials',
      type: AttributeType.String,
      size: 16384,
      required: true,
      filters: ['json', 'encrypt'],
      __type: 'Record<string, unknown>',
    },
    {
      $id: ID.custom('options'),
      key: 'options',
      type: AttributeType.Json,
      filters: ['json'],
      __type: 'Record<string, unknown>',
    },
    {
      $id: ID.custom('search'),
      key: 'search',
      type: AttributeType.String,
      size: 65535,
      filters: ['providerSearch'],
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_provider'),
      key: 'idx_provider',
      type: IndexType.Key,
      attributes: ['provider'],
    },
    {
      $id: ID.custom('idx_type'),
      key: 'idx_type',
      type: IndexType.Key,
      attributes: ['type'],
    },
    {
      $id: ID.custom('idx_search'),
      key: 'idx_search',
      type: IndexType.FullText,
      attributes: ['search'],
    },
  ],
}

const messages: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('messages'),
  name: 'Messages',
  documentSecurity: true,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('providerType'),
      key: 'providerType',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
      required: true,
    },
    {
      $id: ID.custom('status'),
      key: 'status',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
      required: true,
      default: 'processing',
    },
    {
      $id: ID.custom('data'),
      key: 'data',
      type: AttributeType.Json,
      required: true,
      filters: ['json'],
      __type: 'Record<string, unknown>',
    },
    {
      $id: ID.custom('topics'),
      key: 'topics',
      type: AttributeType.String,
      size: 21845,
      array: true,
    },
    {
      $id: ID.custom('users'),
      key: 'users',
      type: AttributeType.String,
      size: 21845,
      array: true,
    },
    {
      $id: ID.custom('targets'),
      key: 'targets',
      type: AttributeType.String,
      size: 21845,
      array: true,
    },
    {
      $id: ID.custom('scheduledAt'),
      key: 'scheduledAt',
      type: AttributeType.Timestamptz,
    },
    {
      $id: ID.custom('scheduleInternalId'),
      key: 'scheduleInternalId',
      type: AttributeType.Integer,
      size: 8,
    },
    {
      $id: ID.custom('scheduleId'),
      key: 'scheduleId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
    },
    {
      $id: ID.custom('deliveredAt'),
      key: 'deliveredAt',
      type: AttributeType.Timestamptz,
    },
    {
      $id: ID.custom('deliveryErrors'),
      key: 'deliveryErrors',
      type: AttributeType.String,
      size: 65535,
      array: true,
    },
    {
      $id: ID.custom('deliveredTotal'),
      key: 'deliveredTotal',
      type: AttributeType.Integer,
      size: 8,
      default: 0,
    },
    {
      $id: ID.custom('search'),
      key: 'search',
      type: AttributeType.String,
      size: 16384,
      filters: ['messageSearch'],
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_search'),
      key: 'idx_search',
      type: IndexType.FullText,
      attributes: ['search'],
    },
  ],
}

const topics: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('topics'),
  name: 'Topics',
  documentSecurity: true,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('name'),
      key: 'name',
      type: AttributeType.String,
      size: 128,
      required: true,
    },
    {
      $id: ID.custom('description'),
      key: 'description',
      type: AttributeType.String,
      size: 256,
    },
    {
      $id: ID.custom('subscribe'),
      key: 'subscribe',
      type: AttributeType.String,
      size: 128,
      array: true,
    },
    {
      $id: ID.custom('emailTotal'),
      key: 'emailTotal',
      type: AttributeType.Integer,
      size: 8,
      default: 0,
    },
    {
      $id: ID.custom('smsTotal'),
      key: 'smsTotal',
      type: AttributeType.Integer,
      size: 8,
      default: 0,
    },
    {
      $id: ID.custom('pushTotal'),
      key: 'pushTotal',
      type: AttributeType.Integer,
      size: 8,
      default: 0,
    },
    {
      $id: ID.custom('targets'),
      key: 'targets',
      type: AttributeType.Virtual,
      filters: ['subQueryTopicTargets'],
      __type: 'Targets[]',
    },
    {
      $id: ID.custom('search'),
      key: 'search',
      type: AttributeType.String,
      size: 16384,
      filters: ['topicSearch'],
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_name'),
      key: 'idx_name',
      type: IndexType.FullText,
      attributes: ['name'],
    },
    {
      $id: ID.custom('idx_search'),
      key: 'idx_search',
      type: IndexType.FullText,
      attributes: ['search'],
    },
  ],
}

const subscribers: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('subscribers'),
  name: 'Subscribers',
  documentSecurity: true,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('targetId'),
      key: 'targetId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
      required: true,
    },
    {
      $id: ID.custom('targetInternalId'),
      key: 'targetInternalId',
      type: AttributeType.Integer,
      size: 8,
      required: true,
    },
    {
      $id: ID.custom('userId'),
      key: 'userId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
      required: true,
    },
    {
      $id: ID.custom('userInternalId'),
      key: 'userInternalId',
      type: AttributeType.Integer,
      size: 8,
      required: true,
    },
    {
      $id: ID.custom('topicId'),
      key: 'topicId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
      required: true,
    },
    {
      $id: ID.custom('topicInternalId'),
      key: 'topicInternalId',
      type: AttributeType.Integer,
      size: 8,
      required: true,
    },
    {
      $id: ID.custom('providerType'),
      key: 'providerType',
      type: AttributeType.String,
      size: 128,
      required: true,
    },
    {
      $id: ID.custom('search'),
      key: 'search',
      type: AttributeType.String,
      size: 16384,
    },
  ],
  indexes: [
    {
      $id: ID.custom('idx_target_id'),
      key: 'idx_target_id',
      type: IndexType.Key,
      attributes: ['targetId'],
    },
    {
      $id: ID.custom('idx_user_id'),
      key: 'idx_user_id',
      type: IndexType.Key,
      attributes: ['userId'],
    },
    {
      $id: ID.custom('idx_topic_id'),
      key: 'idx_topic_id',
      type: IndexType.Key,
      attributes: ['topicId'],
    },
    {
      $id: ID.custom('idx_unique_target_topic'),
      key: 'idx_unique_target_topic',
      type: IndexType.Unique,
      attributes: ['targetInternalId', 'topicInternalId'],
    },
  ],
}

/**
 * All core tenant project collections (1:1 with legacy authCollections and commonCollections).
 */
export const authCollections: Collection[] = [
  users,
  sessions,
  tokens,
  authenticators,
  challenges,
  identities,
  targets,
  teams,
  memberships,
  buckets,
  files,
  stats,
  providers,
  messages,
  topics,
  subscribers,
]
