import { AttributeType, type Collection, Database, ID, IndexType } from '@nuvix/db'

/** Control-plane schema shared by the platform writer and server resolver. */
const projects: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('projects'),
  name: 'Projects',
  documentSecurity: false,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('name'),
      key: 'name',
      type: AttributeType.String,
      size: 128,
      required: true,
    },
    {
      $id: ID.custom('status'),
      key: 'status',
      type: AttributeType.String,
      size: 32,
      required: true,
      default: 'provisioning',
    },
    {
      $id: ID.custom('publishableKey'),
      key: 'publishableKey',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
      required: true,
    },
    {
      $id: ID.custom('containerName'),
      key: 'containerName',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
      required: true,
    },
    {
      $id: ID.custom('volumeName'),
      key: 'volumeName',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
      required: true,
    },
    {
      $id: ID.custom('target'),
      key: 'target',
      type: AttributeType.String,
      size: 8192,
      required: false,
      default: null,
      filters: ['json', 'encrypt'],
    },
    {
      $id: ID.custom('errorMessage'),
      key: 'errorMessage',
      type: AttributeType.String,
      size: 1024,
      required: false,
      default: null,
    },
  ],
  indexes: [
    {
      $id: ID.custom('publishableKey'),
      key: 'idx_publishable_key',
      type: IndexType.Unique,
      attributes: ['publishableKey'],
    },
  ],
}

const webhooks: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('webhooks'),
  name: 'Webhooks',
  documentSecurity: false,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('projectInternalId'),
      key: 'projectInternalId',
      type: AttributeType.Integer,
      size: Database.LENGTH_KEY,
      required: true,
    },
    {
      $id: ID.custom('projectId'),
      key: 'projectId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
      required: true,
    },
    {
      $id: ID.custom('name'),
      key: 'name',
      type: AttributeType.String,
      size: 128,
      required: true,
    },
    {
      $id: ID.custom('url'),
      key: 'url',
      type: AttributeType.String,
      size: 2048,
      required: true,
    },
    {
      $id: ID.custom('httpUser'),
      key: 'httpUser',
      type: AttributeType.String,
      size: 128,
      required: false,
      default: null,
    },
    {
      $id: ID.custom('httpPass'),
      key: 'httpPass',
      type: AttributeType.String,
      size: 256,
      required: false,
      default: null,
      filters: ['encrypt'],
    },
    {
      $id: ID.custom('security'),
      key: 'security',
      type: AttributeType.Boolean,
      required: true,
      default: true,
    },
    {
      $id: ID.custom('events'),
      key: 'events',
      type: AttributeType.String,
      size: 128,
      required: true,
      array: true,
    },
    {
      $id: ID.custom('signatureKey'),
      key: 'signatureKey',
      type: AttributeType.String,
      size: 2048,
      required: false,
      default: null,
    },
    {
      $id: ID.custom('enabled'),
      key: 'enabled',
      type: AttributeType.Boolean,
      required: true,
      default: true,
    },
    {
      $id: ID.custom('logs'),
      key: 'logs',
      type: AttributeType.String,
      size: 1000000,
      required: false,
      default: '',
    },
    {
      $id: ID.custom('attempts'),
      key: 'attempts',
      type: AttributeType.Integer,
      size: 4,
      required: false,
      default: 0,
    },
  ],
  indexes: [
    {
      $id: ID.custom('projectInternalId'),
      key: 'idx_webhook_project_internal_id',
      type: IndexType.Key,
      attributes: ['projectInternalId'],
    },
    {
      $id: ID.custom('projectId'),
      key: 'idx_webhook_project_id',
      type: IndexType.Key,
      attributes: ['projectId'],
    },
  ],
}

const keys: Collection = {
  $collection: Database.METADATA,
  $id: ID.custom('keys'),
  name: 'Keys',
  documentSecurity: false,
  enabled: true,
  attributes: [
    {
      $id: ID.custom('projectInternalId'),
      key: 'projectInternalId',
      type: AttributeType.Integer,
      size: Database.LENGTH_KEY,
      required: true,
    },
    {
      $id: ID.custom('projectId'),
      key: 'projectId',
      type: AttributeType.String,
      size: Database.LENGTH_KEY,
      required: true,
    },
    {
      $id: ID.custom('name'),
      key: 'name',
      type: AttributeType.String,
      size: 128,
      required: true,
    },
    {
      $id: ID.custom('scopes'),
      key: 'scopes',
      type: AttributeType.String,
      size: 128,
      required: true,
      array: true,
    },
    {
      $id: ID.custom('secret'),
      key: 'secret',
      type: AttributeType.String,
      size: 1600,
      required: true,
      filters: ['encrypt'],
    },
    {
      $id: ID.custom('expire'),
      key: 'expire',
      type: AttributeType.Timestamptz,
      required: false,
      default: null,
    },
    {
      $id: ID.custom('accessedAt'),
      key: 'accessedAt',
      type: AttributeType.Timestamptz,
      required: false,
      default: null,
    },
    {
      $id: ID.custom('sdks'),
      key: 'sdks',
      type: AttributeType.String,
      size: 128,
      required: false,
      array: true,
      default: [],
    },
  ],
  indexes: [
    {
      $id: ID.custom('projectInternalId'),
      key: 'idx_key_project_internal_id',
      type: IndexType.Key,
      attributes: ['projectInternalId'],
    },
    {
      $id: ID.custom('projectId'),
      key: 'idx_key_project_id',
      type: IndexType.Key,
      attributes: ['projectId'],
    },
  ],
}

export const platformCollections: Collection[] = [projects, webhooks, keys]
