import { Auth } from '../helper/auth.helper';

const member = [
  'global',
  'public',
  'home',
  'console',
  'graphql',
  'sessions.create',
  'sessions.update',
  'sessions.delete',
  'account',
  'teams.read',
  'teams.create',
  'teams.update',
  'teams.delete',
  'documents.read',
  'documents.create',
  'documents.update',
  'documents.delete',
  'files.read',
  'files.create',
  'files.update',
  'files.delete',
  'projects.read',
  'projects.create',
  'projects.update',
  'projects.delete',
  'locale.read',
  'avatars.read',
  'execution.read',
  'execution.create',
  'execution.update',
  'execution.delete',
  'targets.read',
  'targets.create',
  'targets.update',
  'targets.delete',
  'subscribers.create',
  'subscribers.update',
  'subscribers.delete',
  'subscribers.read',
  'assistant.read',
];

const admins = [
  'global',
  'graphql',
  'sessions.create',
  'sessions.update',
  'sessions.delete',
  'teams.read',
  'teams.create',
  'teams.update',
  'teams.delete',
  'documents.read',
  'documents.create',
  'documents.update',
  'documents.delete',
  'files.read',
  'files.create',
  'files.update',
  'files.delete',
  'buckets.read',
  'buckets.create',
  'buckets.update',
  'buckets.delete',
  'users.read',
  'users.create',
  'users.update',
  'users.delete',
  'databases.read',
  'databases.create',
  'databases.update',
  'databases.delete',
  'collections.read',
  'collections.create',
  'collections.update',
  'collections.delete',
  'platforms.read',
  'platforms.create',
  'platforms.update',
  'platforms.delete',
  'keys.read',
  'keys.create',
  'keys.update',
  'keys.delete',
  'webhooks.read',
  'webhooks.create',
  'webhooks.update',
  'webhooks.delete',
  'locale.read',
  'avatars.read',
  'health.read',
  'functions.read',
  'functions.create',
  'functions.update',
  'functions.delete',
  'execution.read',
  'execution.create',
  'execution.update',
  'execution.delete',
  'rules.read',
  'rules.create',
  'rules.update',
  'rules.delete',
  'migrations.read',
  'migrations.create',
  'migrations.update',
  'migrations.delete',
  'vcs.read',
  'vcs.create',
  'vcs.update',
  'vcs.delete',
  'targets.read',
  'targets.create',
  'targets.update',
  'targets.delete',
  'providers.create',
  'providers.update',
  'providers.delete',
  'providers.read',
  'messages.create',
  'messages.update',
  'messages.delete',
  'messages.read',
  'topics.create',
  'topics.update',
  'topics.delete',
  'topics.read',
  'subscribers.create',
  'subscribers.update',
  'subscribers.delete',
  'subscribers.read',

  // schema
  'schema.read',
  'schema.create',
  'schema.update',
  'schema.delete',
];

export const roles = {
  [Auth.USER_ROLE_GUESTS]: {
    label: 'Guests',
    scopes: [
      'global',
      'public',
      'home',
      'console',
      'graphql',
      'sessions.create',
      'sessions.update',
      'sessions.delete',
      'documents.read',
      'documents.create',
      'documents.update',
      'documents.delete',
      'files.read',
      'files.create',
      'files.update',
      'files.delete',
      'locale.read',
      'avatars.read',
      'execution.create',
      'execution.update',
      'execution.delete',
    ],
  },
  [Auth.USER_ROLE_USERS]: {
    label: 'Users',
    scopes: member,
  },
  [Auth.USER_ROLE_ADMIN]: {
    label: 'Admin',
    scopes: admins,
  },
  [Auth.USER_ROLE_DEVELOPER]: {
    label: 'Developer',
    scopes: admins,
  },
  [Auth.USER_ROLE_OWNER]: {
    label: 'Owner',
    scopes: [...admins, ...member],
  },
  [Auth.USER_ROLE_APPS]: {
    label: 'Applications',
    scopes: ['global', 'health.read', 'graphql'],
  },
};
