export const services = {
  account: {
    key: 'account',
    name: 'Account',
    subtitle:
      'The Account service allows you to authenticate and manage a user account.',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.io/docs/client/account',
    tests: false,
    optional: true,
    icon: '/images/services/account.png',
  },
  avatars: {
    key: 'avatars',
    name: 'Avatars',
    subtitle:
      'The Avatars service aims to help you complete everyday tasks related to your app image, icons, and avatars.',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.io/docs/client/avatars',
    tests: false,
    optional: true,
    icon: '/images/services/avatars.png',
  },
  schemas: {
    key: 'schemas',
    name: 'Schemas',
    subtitle:
      'The Schemas service allows you to create structured collections of documents, query and filter lists of documents',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.io/docs/client/databases',
    tests: false,
    optional: true,
    icon: '/images/services/databases.png',
  },
  database: {
    key: 'database',
    name: 'Database',
    subtitle:
      'The Database service allows you to create schemas and manage your database.',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.io/docs/client/databases',
    tests: false,
    optional: true,
    icon: '/images/services/databases.png',
  },
  locale: {
    key: 'locale',
    name: 'Locale',
    subtitle:
      "The Locale service allows you to customize your app based on your users' location.",
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.io/docs/client/locale',
    tests: false,
    optional: true,
    icon: '/images/services/locale.png',
  },
  health: {
    key: 'health',
    name: 'Health',
    subtitle:
      "The Health service allows you to both validate and monitor your nuvix server's health.",
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.io/docs/server/health',
    tests: false,
    optional: true,
    icon: '/images/services/health.png',
  },
  projects: {
    key: 'projects',
    name: 'Projects',
    subtitle:
      'The Project service allows you to manage all the projects in your nuvix server.',
    sdk: true,
    docs: true,
    docsUrl: '',
    tests: false,
    optional: false,
    icon: '',
  },
  project: {
    key: 'project',
    name: 'Project',
    subtitle:
      'The Project service allows you to manage all the projects in your nuvix server.',
    sdk: true,
    docs: true,
    docsUrl: '',
    tests: false,
    optional: false,
    icon: '',
  },
  storage: {
    key: 'storage',
    name: 'Storage',
    subtitle: 'The Storage service allows you to manage your project files.',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.io/docs/client/storage',
    tests: false,
    optional: true,
    icon: '/images/services/storage.png',
  },
  teams: {
    key: 'teams',
    name: 'Teams',
    subtitle:
      'The Teams service allows you to group users of your project and to enable them to share read and write access to your project resources',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.io/docs/client/teams',
    tests: false,
    optional: true,
    icon: '/images/services/teams.png',
  },
  users: {
    key: 'users',
    name: 'Users',
    subtitle: 'The Users service allows you to manage your project users.',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.io/docs/server/users',
    tests: false,
    optional: true,
    icon: '/images/services/users.png',
  },
  vcs: {
    key: 'vcs',
    name: 'VCS',
    subtitle:
      'The VCS service allows you to interact with providers like GitHub, GitLab etc.',
    sdk: false,
    docs: false,
    docsUrl: '',
    tests: false,
    optional: false,
    icon: '',
  },
  functions: {
    key: 'functions',
    name: 'Functions',
    subtitle:
      'The Functions Service allows you view, create and manage your Cloud Functions.',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.io/docs/functions',
    tests: false,
    optional: true,
    icon: '/images/services/functions.png',
  },
  proxy: {
    key: 'proxy',
    name: 'Proxy',
    subtitle:
      'The Proxy Service allows you to configure actions for your domains beyond DNS configuration.',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.io/docs/proxy',
    tests: false,
    optional: false,
    icon: '/images/services/proxy.png',
  },
  mock: {
    key: 'mock',
    name: 'Mock',
    subtitle: '',
    sdk: false,
    docs: false,
    docsUrl: '',
    tests: true,
    optional: false,
    icon: '',
  },
  graphql: {
    key: 'graphql',
    name: 'GraphQL',
    subtitle:
      'The GraphQL API allows you to query and mutate your nuvix server using GraphQL.',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.io/docs/graphql',
    tests: true,
    optional: true,
    icon: '/images/services/graphql.png',
  },
  console: {
    key: 'console',
    name: 'Console',
    subtitle:
      'The Console service allows you to interact with console relevant informations.',
    sdk: true,
    docs: true,
    docsUrl: '',
    tests: false,
    optional: false,
    icon: '',
  },
  migrations: {
    key: 'migrations',
    name: 'Migrations',
    subtitle:
      'The Migrations service allows you to migrate third-party data to your nuvix project.',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.io/docs/migrations',
    tests: true,
    optional: false,
    icon: '/images/services/migrations.png',
  },
  messaging: {
    key: 'messaging',
    name: 'Messaging',
    subtitle:
      'The Messaging service allows you to send messages to any provider type (SMTP, push notification, SMS, etc.).',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.io/docs/server/messaging',
    tests: true,
    optional: true,
    icon: '/images/services/messaging.png',
  },
} as const;
