export const services = {
  account: {
    key: 'account',
    name: 'Account',
    subtitle:
      'The Account service allows you to authenticate and manage a user account.',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.in/docs/client/account',
    tests: false,
    optional: true,
    icon: '/images/services/account.png',
  },
  avatars: {
    key: 'avatars',
    name: 'Avatars',
    subtitle:
      'The Avatars service aims to help you complete everyday tasks related to your app image, icons, and avatars.',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.in/docs/client/avatars',
    tests: false,
    optional: true,
    icon: '/images/services/avatars.png',
  },
  schemas: {
    key: 'schemas',
    name: 'Schemas',
    subtitle:
      'The Schemas service allows you to create structured collections of documents, query and filter lists of documents',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.in/docs/client/databases',
    tests: false,
    optional: true,
    icon: '/images/services/databases.png',
  },
  database: {
    key: 'database',
    name: 'Database',
    subtitle:
      'The Database service allows you to create schemas and manage your database.',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.in/docs/client/databases',
    tests: false,
    optional: true,
    icon: '/images/services/databases.png',
  },
  locale: {
    key: 'locale',
    name: 'Locale',
    subtitle:
      "The Locale service allows you to customize your app based on your users' location.",
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.in/docs/client/locale',
    tests: false,
    optional: true,
    icon: '/images/services/locale.png',
  },
  health: {
    key: 'health',
    name: 'Health',
    subtitle:
      "The Health service allows you to both validate and monitor your nuvix server's health.",
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.in/docs/server/health',
    tests: false,
    optional: true,
    icon: '/images/services/health.png',
  },
  storage: {
    key: 'storage',
    name: 'Storage',
    subtitle: 'The Storage service allows you to manage your project files.',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.in/docs/client/storage',
    tests: false,
    optional: true,
    icon: '/images/services/storage.png',
  },
  teams: {
    key: 'teams',
    name: 'Teams',
    subtitle:
      'The Teams service allows you to group users of your project and to enable them to share read and write access to your project resources',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.in/docs/client/teams',
    tests: false,
    optional: true,
    icon: '/images/services/teams.png',
  },
  users: {
    key: 'users',
    name: 'Users',
    subtitle: 'The Users service allows you to manage your project users.',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.in/docs/server/users',
    tests: false,
    optional: true,
    icon: '/images/services/users.png',
  },
  messaging: {
    key: 'messaging',
    name: 'Messaging',
    subtitle:
      'The Messaging service allows you to send messages to any provider type (SMTP, push notification, SMS, etc.).',
    sdk: true,
    docs: true,
    docsUrl: 'https://nuvix.in/docs/server/messaging',
    tests: true,
    optional: true,
    icon: '/images/services/messaging.png',
  },
} as const
