// Auto-generated by scripts/generate-i18n-types.ts
// Do not edit manually - regenerate with: npm run i18n:types

/**
 * All available translation keys
 */
export type TranslationKey =
  | 'continents.af'
  | 'continents.an'
  | 'continents.as'
  | 'continents.eu'
  | 'continents.na'
  | 'continents.oc'
  | 'continents.sa'
  | 'countries.ad'
  | 'countries.ae'
  | 'countries.af'
  | 'countries.ag'
  | 'countries.al'
  | 'countries.am'
  | 'countries.ao'
  | 'countries.ar'
  | 'countries.at'
  | 'countries.au'
  | 'countries.az'
  | 'countries.ba'
  | 'countries.bb'
  | 'countries.bd'
  | 'countries.be'
  | 'countries.bf'
  | 'countries.bg'
  | 'countries.bh'
  | 'countries.bi'
  | 'countries.bj'
  | 'countries.bn'
  | 'countries.bo'
  | 'countries.br'
  | 'countries.bs'
  | 'countries.bt'
  | 'countries.bw'
  | 'countries.by'
  | 'countries.bz'
  | 'countries.ca'
  | 'countries.cd'
  | 'countries.cf'
  | 'countries.cg'
  | 'countries.ch'
  | 'countries.ci'
  | 'countries.cl'
  | 'countries.cm'
  | 'countries.cn'
  | 'countries.co'
  | 'countries.cr'
  | 'countries.cu'
  | 'countries.cv'
  | 'countries.cy'
  | 'countries.cz'
  | 'countries.de'
  | 'countries.dj'
  | 'countries.dk'
  | 'countries.dm'
  | 'countries.do'
  | 'countries.dz'
  | 'countries.ec'
  | 'countries.ee'
  | 'countries.eg'
  | 'countries.er'
  | 'countries.es'
  | 'countries.et'
  | 'countries.fi'
  | 'countries.fj'
  | 'countries.fm'
  | 'countries.fr'
  | 'countries.ga'
  | 'countries.gb'
  | 'countries.gd'
  | 'countries.ge'
  | 'countries.gh'
  | 'countries.gm'
  | 'countries.gn'
  | 'countries.gq'
  | 'countries.gr'
  | 'countries.gt'
  | 'countries.gw'
  | 'countries.gy'
  | 'countries.hk'
  | 'countries.hn'
  | 'countries.hr'
  | 'countries.ht'
  | 'countries.hu'
  | 'countries.id'
  | 'countries.ie'
  | 'countries.il'
  | 'countries.in'
  | 'countries.iq'
  | 'countries.ir'
  | 'countries.is'
  | 'countries.it'
  | 'countries.jm'
  | 'countries.jo'
  | 'countries.jp'
  | 'countries.ke'
  | 'countries.kg'
  | 'countries.kh'
  | 'countries.ki'
  | 'countries.km'
  | 'countries.kn'
  | 'countries.kp'
  | 'countries.kr'
  | 'countries.kw'
  | 'countries.kz'
  | 'countries.la'
  | 'countries.lb'
  | 'countries.lc'
  | 'countries.li'
  | 'countries.lk'
  | 'countries.lr'
  | 'countries.ls'
  | 'countries.lt'
  | 'countries.lu'
  | 'countries.lv'
  | 'countries.ly'
  | 'countries.ma'
  | 'countries.mc'
  | 'countries.md'
  | 'countries.me'
  | 'countries.mg'
  | 'countries.mh'
  | 'countries.mk'
  | 'countries.ml'
  | 'countries.mm'
  | 'countries.mn'
  | 'countries.mr'
  | 'countries.mt'
  | 'countries.mu'
  | 'countries.mv'
  | 'countries.mw'
  | 'countries.mx'
  | 'countries.my'
  | 'countries.mz'
  | 'countries.na'
  | 'countries.ne'
  | 'countries.ng'
  | 'countries.ni'
  | 'countries.nl'
  | 'countries.no'
  | 'countries.np'
  | 'countries.nr'
  | 'countries.nz'
  | 'countries.om'
  | 'countries.pa'
  | 'countries.pe'
  | 'countries.pg'
  | 'countries.ph'
  | 'countries.pk'
  | 'countries.pl'
  | 'countries.ps'
  | 'countries.pt'
  | 'countries.pw'
  | 'countries.py'
  | 'countries.qa'
  | 'countries.ro'
  | 'countries.rs'
  | 'countries.ru'
  | 'countries.rw'
  | 'countries.sa'
  | 'countries.sb'
  | 'countries.sc'
  | 'countries.sd'
  | 'countries.se'
  | 'countries.sg'
  | 'countries.si'
  | 'countries.sk'
  | 'countries.sl'
  | 'countries.sm'
  | 'countries.sn'
  | 'countries.so'
  | 'countries.sr'
  | 'countries.ss'
  | 'countries.st'
  | 'countries.sv'
  | 'countries.sy'
  | 'countries.sz'
  | 'countries.td'
  | 'countries.tg'
  | 'countries.th'
  | 'countries.tj'
  | 'countries.tl'
  | 'countries.tm'
  | 'countries.tn'
  | 'countries.to'
  | 'countries.tr'
  | 'countries.tt'
  | 'countries.tv'
  | 'countries.tw'
  | 'countries.tz'
  | 'countries.ua'
  | 'countries.ug'
  | 'countries.us'
  | 'countries.uy'
  | 'countries.uz'
  | 'countries.va'
  | 'countries.vc'
  | 'countries.ve'
  | 'countries.vn'
  | 'countries.vu'
  | 'countries.ws'
  | 'countries.ye'
  | 'countries.za'
  | 'countries.zm'
  | 'countries.zw'
  | 'emails.certificate.body'
  | 'emails.certificate.footer'
  | 'emails.certificate.hello'
  | 'emails.certificate.signature'
  | 'emails.certificate.subject'
  | 'emails.certificate.thanks'
  | 'emails.invitation.body'
  | 'emails.invitation.footer'
  | 'emails.invitation.hello'
  | 'emails.invitation.signature'
  | 'emails.invitation.subject'
  | 'emails.invitation.thanks'
  | 'emails.magicSession.buttonText'
  | 'emails.magicSession.clientInfo'
  | 'emails.magicSession.hello'
  | 'emails.magicSession.optionButton'
  | 'emails.magicSession.optionUrl'
  | 'emails.magicSession.securityPhrase'
  | 'emails.magicSession.signature'
  | 'emails.magicSession.subject'
  | 'emails.magicSession.thanks'
  | 'emails.mfaChallenge.clientInfo'
  | 'emails.mfaChallenge.description'
  | 'emails.mfaChallenge.hello'
  | 'emails.mfaChallenge.signature'
  | 'emails.mfaChallenge.subject'
  | 'emails.mfaChallenge.thanks'
  | 'emails.otpSession.clientInfo'
  | 'emails.otpSession.description'
  | 'emails.otpSession.hello'
  | 'emails.otpSession.securityPhrase'
  | 'emails.otpSession.signature'
  | 'emails.otpSession.subject'
  | 'emails.otpSession.thanks'
  | 'emails.recovery.body'
  | 'emails.recovery.footer'
  | 'emails.recovery.hello'
  | 'emails.recovery.signature'
  | 'emails.recovery.subject'
  | 'emails.recovery.thanks'
  | 'emails.sender'
  | 'emails.sessionAlert.body'
  | 'emails.sessionAlert.footer'
  | 'emails.sessionAlert.hello'
  | 'emails.sessionAlert.listCountry'
  | 'emails.sessionAlert.listDevice'
  | 'emails.sessionAlert.listIpAddress'
  | 'emails.sessionAlert.signature'
  | 'emails.sessionAlert.subject'
  | 'emails.sessionAlert.thanks'
  | 'emails.verification.body'
  | 'emails.verification.footer'
  | 'emails.verification.hello'
  | 'emails.verification.signature'
  | 'emails.verification.subject'
  | 'emails.verification.thanks'
  | 'locale.country.unknown'
  | 'settings.direction'
  | 'settings.inspire'
  | 'settings.locale'
  | 'sms.verification.body'

/**
 * Parameter requirements for each translation key
 */
export interface TranslationParams {
  'continents.af': void
  'continents.an': void
  'continents.as': void
  'continents.eu': void
  'continents.na': void
  'continents.oc': void
  'continents.sa': void
  'countries.ad': void
  'countries.ae': void
  'countries.af': void
  'countries.ag': void
  'countries.al': void
  'countries.am': void
  'countries.ao': void
  'countries.ar': void
  'countries.at': void
  'countries.au': void
  'countries.az': void
  'countries.ba': void
  'countries.bb': void
  'countries.bd': void
  'countries.be': void
  'countries.bf': void
  'countries.bg': void
  'countries.bh': void
  'countries.bi': void
  'countries.bj': void
  'countries.bn': void
  'countries.bo': void
  'countries.br': void
  'countries.bs': void
  'countries.bt': void
  'countries.bw': void
  'countries.by': void
  'countries.bz': void
  'countries.ca': void
  'countries.cd': void
  'countries.cf': void
  'countries.cg': void
  'countries.ch': void
  'countries.ci': void
  'countries.cl': void
  'countries.cm': void
  'countries.cn': void
  'countries.co': void
  'countries.cr': void
  'countries.cu': void
  'countries.cv': void
  'countries.cy': void
  'countries.cz': void
  'countries.de': void
  'countries.dj': void
  'countries.dk': void
  'countries.dm': void
  'countries.do': void
  'countries.dz': void
  'countries.ec': void
  'countries.ee': void
  'countries.eg': void
  'countries.er': void
  'countries.es': void
  'countries.et': void
  'countries.fi': void
  'countries.fj': void
  'countries.fm': void
  'countries.fr': void
  'countries.ga': void
  'countries.gb': void
  'countries.gd': void
  'countries.ge': void
  'countries.gh': void
  'countries.gm': void
  'countries.gn': void
  'countries.gq': void
  'countries.gr': void
  'countries.gt': void
  'countries.gw': void
  'countries.gy': void
  'countries.hk': void
  'countries.hn': void
  'countries.hr': void
  'countries.ht': void
  'countries.hu': void
  'countries.id': void
  'countries.ie': void
  'countries.il': void
  'countries.in': void
  'countries.iq': void
  'countries.ir': void
  'countries.is': void
  'countries.it': void
  'countries.jm': void
  'countries.jo': void
  'countries.jp': void
  'countries.ke': void
  'countries.kg': void
  'countries.kh': void
  'countries.ki': void
  'countries.km': void
  'countries.kn': void
  'countries.kp': void
  'countries.kr': void
  'countries.kw': void
  'countries.kz': void
  'countries.la': void
  'countries.lb': void
  'countries.lc': void
  'countries.li': void
  'countries.lk': void
  'countries.lr': void
  'countries.ls': void
  'countries.lt': void
  'countries.lu': void
  'countries.lv': void
  'countries.ly': void
  'countries.ma': void
  'countries.mc': void
  'countries.md': void
  'countries.me': void
  'countries.mg': void
  'countries.mh': void
  'countries.mk': void
  'countries.ml': void
  'countries.mm': void
  'countries.mn': void
  'countries.mr': void
  'countries.mt': void
  'countries.mu': void
  'countries.mv': void
  'countries.mw': void
  'countries.mx': void
  'countries.my': void
  'countries.mz': void
  'countries.na': void
  'countries.ne': void
  'countries.ng': void
  'countries.ni': void
  'countries.nl': void
  'countries.no': void
  'countries.np': void
  'countries.nr': void
  'countries.nz': void
  'countries.om': void
  'countries.pa': void
  'countries.pe': void
  'countries.pg': void
  'countries.ph': void
  'countries.pk': void
  'countries.pl': void
  'countries.ps': void
  'countries.pt': void
  'countries.pw': void
  'countries.py': void
  'countries.qa': void
  'countries.ro': void
  'countries.rs': void
  'countries.ru': void
  'countries.rw': void
  'countries.sa': void
  'countries.sb': void
  'countries.sc': void
  'countries.sd': void
  'countries.se': void
  'countries.sg': void
  'countries.si': void
  'countries.sk': void
  'countries.sl': void
  'countries.sm': void
  'countries.sn': void
  'countries.so': void
  'countries.sr': void
  'countries.ss': void
  'countries.st': void
  'countries.sv': void
  'countries.sy': void
  'countries.sz': void
  'countries.td': void
  'countries.tg': void
  'countries.th': void
  'countries.tj': void
  'countries.tl': void
  'countries.tm': void
  'countries.tn': void
  'countries.to': void
  'countries.tr': void
  'countries.tt': void
  'countries.tv': void
  'countries.tw': void
  'countries.tz': void
  'countries.ua': void
  'countries.ug': void
  'countries.us': void
  'countries.uy': void
  'countries.uz': void
  'countries.va': void
  'countries.vc': void
  'countries.ve': void
  'countries.vn': void
  'countries.vu': void
  'countries.ws': void
  'countries.ye': void
  'countries.za': void
  'countries.zm': void
  'countries.zw': void
  'emails.certificate.body': { domain: string; attempt: string; error: string }
  'emails.certificate.footer': void
  'emails.certificate.hello': void
  'emails.certificate.signature': { project: string }
  'emails.certificate.subject': { 0: string }
  'emails.certificate.thanks': void
  'emails.invitation.body': { owner: string; team: string; project: string }
  'emails.invitation.footer': void
  'emails.invitation.hello': { user: string }
  'emails.invitation.signature': { project: string }
  'emails.invitation.subject': { 0: string; 1: string }
  'emails.invitation.thanks': void
  'emails.magicSession.buttonText': { project: string }
  'emails.magicSession.clientInfo': {
    agentClient: string
    agentDevice: string
    agentOs: string
  }
  'emails.magicSession.hello': { user: string }
  'emails.magicSession.optionButton': { project: string }
  'emails.magicSession.optionUrl': void
  'emails.magicSession.securityPhrase': { phrase: string }
  'emails.magicSession.signature': { project: string }
  'emails.magicSession.subject': { project: string }
  'emails.magicSession.thanks': void
  'emails.mfaChallenge.clientInfo': {
    agentClient: string
    agentDevice: string
    agentOs: string
  }
  'emails.mfaChallenge.description': { project: string }
  'emails.mfaChallenge.hello': { user: string }
  'emails.mfaChallenge.signature': { project: string }
  'emails.mfaChallenge.subject': { project: string }
  'emails.mfaChallenge.thanks': void
  'emails.otpSession.clientInfo': {
    agentClient: string
    agentDevice: string
    agentOs: string
  }
  'emails.otpSession.description': { project: string }
  'emails.otpSession.hello': { user: string }
  'emails.otpSession.securityPhrase': { phrase: string }
  'emails.otpSession.signature': { project: string }
  'emails.otpSession.subject': { project: string }
  'emails.otpSession.thanks': void
  'emails.recovery.body': { project: string }
  'emails.recovery.footer': void
  'emails.recovery.hello': { user: string }
  'emails.recovery.signature': { project: string }
  'emails.recovery.subject': void
  'emails.recovery.thanks': void
  'emails.sender': { 0: string }
  'emails.sessionAlert.body': {
    project: string
    date: string
    year: string
    time: string
  }
  'emails.sessionAlert.footer': void
  'emails.sessionAlert.hello': { user: string }
  'emails.sessionAlert.listCountry': { country: string }
  'emails.sessionAlert.listDevice': { device: string }
  'emails.sessionAlert.listIpAddress': { ipAddress: string }
  'emails.sessionAlert.signature': { project: string }
  'emails.sessionAlert.subject': { project: string }
  'emails.sessionAlert.thanks': void
  'emails.verification.body': { project: string }
  'emails.verification.footer': void
  'emails.verification.hello': { user: string }
  'emails.verification.signature': { project: string }
  'emails.verification.subject': void
  'emails.verification.thanks': void
  'locale.country.unknown': void
  'settings.direction': void
  'settings.inspire': void
  'settings.locale': void
  'sms.verification.body': { secret: string }
}

/**
 * Helper type to get params for a specific key
 */
export type ParamsFor<K extends TranslationKey> = TranslationParams[K]

/**
 * Check if a key requires parameters
 */
export type RequiresParams<K extends TranslationKey> =
  TranslationParams[K] extends void ? false : true
