/**
 * Generates `src/keys.generated.ts` from en.json — the TranslationKey union.
 * Usage: bun run scripts/generate-keys.ts <enJsonPath>
 */
const [enPath] = process.argv.slice(2)
if (!enPath) {
  console.error('usage: bun run scripts/generate-keys.ts <enJsonPath>')
  process.exit(1)
}

const en = await Bun.file(enPath).json()
const keys = Object.keys(en).sort()

const banner = `// Auto-generated by packages/i18n/scripts/generate-keys.ts — do not edit.
`

const body = `export type TranslationKey =
${keys.map((key) => `  | '${key}'`).join('\n')}
`

await Bun.write(new URL('../src/keys.generated.ts', import.meta.url), banner + body)
console.log(`generated ${keys.length} translation keys`)
