export const APP_PLATFORM_SERVER = 'server';
export const APP_PLATFORM_CLIENT = 'client';
export const APP_PLATFORM_CONSOLE = 'console';

export const platforms = {
  [APP_PLATFORM_CLIENT]: {
    key: APP_PLATFORM_CLIENT,
    name: 'Client',
    description:
      'Client libraries for integrating with Nuvix to build client-based applications and websites. Read the [getting started for web](https://nuvix.io/docs/getting-started-for-web) or [getting started for Flutter](https://nuvix.io/docs/getting-started-for-flutter) tutorials to start building your first application.',
    enabled: true,
    beta: false,
    sdks: [
      {
        key: 'web',
        name: 'Web',
        version: '16.0.0',
        url: 'https://github.com/nuvix/sdk-for-web',
        package: 'https://www.npmjs.com/package/nuvix',
        enabled: true,
        beta: false,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_CLIENT,
        prism: 'javascript',
        gitUrl: 'git@github.com:nuvix/sdk-for-web.git',
        gitRepoName: 'sdk-for-web',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
        demos: [
          {
            icon: 'react.svg',
            name: 'Todo App with React JS',
            description:
              'A simple Todo app that uses both the Nuvix account and database APIs.',
            source: 'https://github.com/nuvix/todo-with-react',
            url: 'https://nuvix-todo-with-react.vercel.app/',
          },
          {
            icon: 'vue.svg',
            name: 'Todo App with Vue JS',
            description:
              'A simple Todo app that uses both the Nuvix account and database APIs.',
            source: 'https://github.com/nuvix/todo-with-vue',
            url: 'https://nuvix-todo-with-vue.vercel.app/',
          },
          {
            icon: 'angular.svg',
            name: 'Todo App with Angular',
            description:
              'A simple Todo app that uses both the Nuvix account and database APIs.',
            source: 'https://github.com/nuvix/todo-with-angular',
            url: 'https://nuvix-todo-with-angular.vercel.app/',
          },
          {
            icon: 'svelte.svg',
            name: 'Todo App with Svelte',
            description:
              'A simple Todo app that uses both the Nuvix account and database APIs.',
            source: 'https://github.com/nuvix/todo-with-svelte',
            url: 'https://nuvix-todo-with-svelte.vercel.app/',
          },
        ],
      },
      {
        key: 'flutter',
        name: 'Flutter',
        version: '13.0.0',
        url: 'https://github.com/nuvix/sdk-for-flutter',
        package: 'https://pub.dev/packages/nuvix',
        enabled: true,
        beta: false,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_CLIENT,
        prism: 'dart',
        gitUrl: 'git@github.com:nuvix/sdk-for-flutter.git',
        gitRepoName: 'sdk-for-flutter',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
      {
        key: 'apple',
        name: 'Apple',
        version: '7.0.0',
        url: 'https://github.com/nuvix/sdk-for-apple',
        package: 'https://github.com/nuvix/sdk-for-apple',
        enabled: true,
        beta: false,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_CLIENT,
        prism: 'swift',
        gitUrl: 'git@github.com:nuvix/sdk-for-apple.git',
        gitRepoName: 'sdk-for-apple',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
      {
        key: 'objective-c',
        name: 'Objective C',
        url: '',
        package: '',
        enabled: false,
        beta: false,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_CLIENT,
        prism: '',
        source: false,
        gitUrl: 'git@github.com:nuvix/sdk-for-objective-c.git',
        gitRepoName: 'sdk-for-objective-c',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
      {
        key: 'android',
        name: 'Android',
        version: '6.0.0',
        url: 'https://github.com/nuvix/sdk-for-android',
        package: 'https://search.maven.org/artifact/io.nuvix/sdk-for-android',
        enabled: true,
        beta: false,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_CLIENT,
        prism: 'kotlin',
        gitUrl: 'git@github.com:nuvix/sdk-for-android.git',
        gitRepoName: 'sdk-for-android',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
      {
        key: 'react-native',
        name: 'React Native',
        version: '0.5.0',
        url: 'https://github.com/nuvix/sdk-for-react-native',
        package: 'https://npmjs.com/package/react-native-nuvix',
        enabled: true,
        beta: true,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_CLIENT,
        prism: 'javascript',
        gitUrl: 'git@github.com:nuvix/sdk-for-react-native.git',
        gitRepoName: 'sdk-for-react-native',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
      {
        key: 'graphql',
        name: 'GraphQL',
        version: 'October 2021',
        url: '',
        package: '',
        enabled: true,
        beta: false,
        dev: false,
        hidden: true,
        family: APP_PLATFORM_CLIENT,
        prism: 'graphql',
        gitUrl: '',
        gitRepoName: '',
        gitUserName: '',
        gitBranch: '',
        isSDK: false,
      },
      {
        key: 'rest',
        name: 'REST',
        version: '',
        url: '',
        package: '',
        enabled: true,
        beta: false,
        dev: false,
        hidden: true,
        family: APP_PLATFORM_CLIENT,
        prism: 'http',
        gitUrl: '',
        gitRepoName: '',
        gitUserName: '',
        gitBranch: '',
        isSDK: false,
      },
    ],
  },
  [APP_PLATFORM_CONSOLE]: {
    key: APP_PLATFORM_CONSOLE,
    name: 'Console',
    enabled: false,
    beta: false,
    sdks: [
      {
        key: 'web',
        name: 'Console',
        version: '1.1.0',
        url: 'https://github.com/nuvix/sdk-for-console',
        package: '',
        enabled: true,
        beta: false,
        dev: false,
        hidden: true,
        family: APP_PLATFORM_CONSOLE,
        prism: 'javascript',
        gitUrl: 'git@github.com:nuvix/sdk-for-console.git',
        gitBranch: 'dev',
        gitRepoName: 'sdk-for-console',
        gitUserName: 'nuvix',
      },
      {
        key: 'cli',
        name: 'Command Line',
        version: '6.0.0',
        url: 'https://github.com/nuvix/sdk-for-cli',
        package: 'https://www.npmjs.com/package/nuvix-cli',
        enabled: true,
        beta: true,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_CONSOLE,
        prism: 'bash',
        gitUrl: 'git@github.com:nuvix/sdk-for-cli.git',
        gitRepoName: 'sdk-for-cli',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
    ],
  },
  [APP_PLATFORM_SERVER]: {
    key: APP_PLATFORM_SERVER,
    name: 'Server',
    description:
      'Libraries for integrating with Nuvix to build server side integrations. Read the [getting started for server](https://nuvix.io/docs/getting-started-for-server) tutorial to start building your first server integration.',
    enabled: true,
    beta: false,
    sdks: [
      {
        key: 'nodejs',
        name: 'Node.js',
        version: '14.1.0',
        url: 'https://github.com/nuvix/sdk-for-node',
        package: 'https://www.npmjs.com/package/node-nuvix',
        enabled: true,
        beta: false,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_SERVER,
        prism: 'javascript',
        gitUrl: 'git@github.com:nuvix/sdk-for-node.git',
        gitRepoName: 'sdk-for-node',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
      {
        key: 'deno',
        name: 'Deno',
        version: '12.1.0',
        url: 'https://github.com/nuvix/sdk-for-deno',
        package: 'https://deno.land/x/nuvix',
        enabled: true,
        beta: false,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_SERVER,
        prism: 'typescript',
        gitUrl: 'git@github.com:nuvix/sdk-for-deno.git',
        gitRepoName: 'sdk-for-deno',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
      {
        key: 'php',
        name: 'PHP',
        version: '12.0.0',
        url: 'https://github.com/nuvix/sdk-for-php',
        package: 'https://packagist.org/packages/nuvix/nuvix',
        enabled: true,
        beta: false,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_SERVER,
        prism: 'php',
        gitUrl: 'git@github.com:nuvix/sdk-for-php.git',
        gitRepoName: 'sdk-for-php',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
      {
        key: 'python',
        name: 'Python',
        version: '6.1.0',
        url: 'https://github.com/nuvix/sdk-for-python',
        package: 'https://pypi.org/project/nuvix/',
        enabled: true,
        beta: false,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_SERVER,
        prism: 'python',
        gitUrl: 'git@github.com:nuvix/sdk-for-python.git',
        gitRepoName: 'sdk-for-python',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
      {
        key: 'ruby',
        name: 'Ruby',
        version: '12.1.0',
        url: 'https://github.com/nuvix/sdk-for-ruby',
        package: 'https://rubygems.org/gems/nuvix',
        enabled: true,
        beta: false,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_SERVER,
        prism: 'ruby',
        gitUrl: 'git@github.com:nuvix/sdk-for-ruby.git',
        gitRepoName: 'sdk-for-ruby',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
      {
        key: 'go',
        name: 'Go',
        version: '0.2.0',
        url: 'https://github.com/nuvix/sdk-for-go',
        package: 'https://github.com/nuvix/sdk-for-go',
        enabled: true,
        beta: true,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_SERVER,
        prism: 'go',
        gitUrl: 'git@github.com:nuvix/sdk-for-go.git',
        gitRepoName: 'sdk-for-go',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
      {
        key: 'dotnet',
        name: '.NET',
        version: '0.10.0',
        url: 'https://github.com/nuvix/sdk-for-dotnet',
        package: 'https://www.nuget.org/packages/Nuvix',
        enabled: true,
        beta: true,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_SERVER,
        prism: 'csharp',
        gitUrl: 'git@github.com:nuvix/sdk-for-dotnet.git',
        gitRepoName: 'sdk-for-dotnet',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
      {
        key: 'dart',
        name: 'Dart',
        version: '12.1.0',
        url: 'https://github.com/nuvix/sdk-for-dart',
        package: 'https://pub.dev/packages/dart_nuvix',
        enabled: true,
        beta: false,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_SERVER,
        prism: 'dart',
        gitUrl: 'git@github.com:nuvix/sdk-for-dart.git',
        gitRepoName: 'sdk-for-dart',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
      {
        key: 'kotlin',
        name: 'Kotlin',
        version: '6.1.0',
        url: 'https://github.com/nuvix/sdk-for-kotlin',
        package: 'https://search.maven.org/artifact/io.nuvix/sdk-for-kotlin',
        enabled: true,
        beta: false,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_SERVER,
        prism: 'kotlin',
        gitUrl: 'git@github.com:nuvix/sdk-for-kotlin.git',
        gitRepoName: 'sdk-for-kotlin',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
      {
        key: 'swift',
        name: 'Swift',
        version: '6.1.0',
        url: 'https://github.com/nuvix/sdk-for-swift',
        package: 'https://github.com/nuvix/sdk-for-swift',
        enabled: true,
        beta: false,
        dev: false,
        hidden: false,
        family: APP_PLATFORM_SERVER,
        prism: 'swift',
        gitUrl: 'git@github.com:nuvix/sdk-for-swift.git',
        gitRepoName: 'sdk-for-swift',
        gitUserName: 'nuvix',
        gitBranch: 'dev',
      },
      {
        key: 'graphql',
        name: 'GraphQL',
        version: 'October 2021',
        url: '',
        package: '',
        enabled: true,
        beta: false,
        dev: false,
        hidden: true,
        family: APP_PLATFORM_SERVER,
        prism: 'graphql',
        gitUrl: '',
        gitRepoName: '',
        gitUserName: '',
        gitBranch: '',
        isSDK: false,
      },
      {
        key: 'rest',
        name: 'REST',
        version: '',
        url: '',
        package: '',
        enabled: true,
        beta: false,
        dev: false,
        hidden: true,
        family: APP_PLATFORM_SERVER,
        prism: 'http',
        gitUrl: '',
        gitRepoName: '',
        gitUserName: '',
        gitBranch: '',
        isSDK: false,
      },
    ],
  },
};
