export const queryOperators = [
    { alias: "eq", operator: "=", meaning: "equals" },
    { alias: "gt", operator: ">", meaning: "greater than" },
    { alias: "gte", operator: ">=", meaning: "greater than or equal" },
    { alias: "lt", operator: "<", meaning: "less than" },
    { alias: "lte", operator: "<=", meaning: "less than or equal" },
    { alias: "neq", operator: "<> or !=", meaning: "not equal" },
    { alias: "like", operator: "LIKE", meaning: "LIKE operator (uses * as an alias for % in patterns)" },
    { alias: "ilike", operator: "ILIKE", meaning: "ILIKE operator (uses * as an alias for % in patterns)" },
    { alias: "match", operator: "~", meaning: "~ operator for pattern matching" },
    { alias: "imatch", operator: "~*", meaning: "~* operator for pattern matching" },
    { alias: "in", operator: "IN", meaning: "one of a list of values" },
    { alias: "is", operator: "IS", meaning: "checking for exact equality (null,true,false,unknown)" },
    { alias: "isdistinct", operator: "IS DISTINCT FROM", meaning: "not equal, treating NULL as a comparable value" },
    { alias: "fts", operator: "@@", meaning: "Full-Text Search using to_tsquery" },
    { alias: "plfts", operator: "@@", meaning: "Full-Text Search using plainto_tsquery" },
    { alias: "phfts", operator: "@@", meaning: "Full-Text Search using phraseto_tsquery" },
    { alias: "wfts", operator: "@@", meaning: "Full-Text Search using websearch_to_tsquery" },
    { alias: "cs", operator: "@>", meaning: "contains" },
    { alias: "cd", operator: "<@", meaning: "contained in" },
    { alias: "ov", operator: "&&", meaning: "overlap (have points in common)" },
    { alias: "sl", operator: "<<", meaning: "strictly left of" },
    { alias: "sr", operator: ">>", meaning: "strictly right of" },
    { alias: "nxr", operator: "&<", meaning: "does not extend to the right of" },
    { alias: "nxl", operator: "&>", meaning: "does not extend to the left of" },
    { alias: "adj", operator: "-|-", meaning: "is adjacent to" },
    { alias: "not", operator: "NOT", meaning: "negates another operator" },
    { alias: "or", operator: "OR", meaning: "logical OR" },
    { alias: "and", operator: "AND", meaning: "logical AND" },
    { alias: "all", operator: "ALL", meaning: "comparison matches all values in the list" },
    { alias: "any", operator: "ANY", meaning: "comparison" }
] as const;

export type QueryOperator = typeof queryOperators[number]['alias'];