import * as path from 'path';


const assetsPath = path.resolve(__dirname, '../../../../assets/avatars/flags');


export const flags = {
    'af': { 'name': 'Afghanistan', 'path': assetsPath + `/af.png` },
    'ao': { 'name': 'Angola', 'path': assetsPath + `/ao.png` },
    'al': { 'name': 'Albania', 'path': assetsPath + `/al.png` },
    'ad': { 'name': 'Andorra', 'path': assetsPath + `/ad.png` },
    'ae': { 'name': 'United Arab Emirates', 'path': assetsPath + `/ae.png` },
    'ar': { 'name': 'Argentina', 'path': assetsPath + `/ar.png` },
    'am': { 'name': 'Armenia', 'path': assetsPath + `/am.png` },
    'ag': { 'name': 'Antigua and Barbuda', 'path': assetsPath + `/ag.png` },
    'au': { 'name': 'Australia', 'path': assetsPath + `/au.png` },
    'at': { 'name': 'Austria', 'path': assetsPath + `/at.png` },
    'az': { 'name': 'Azerbaijan', 'path': assetsPath + `/az.png` },
    'bi': { 'name': 'Burundi', 'path': assetsPath + `/bi.png` },
    'be': { 'name': 'Belgium', 'path': assetsPath + `/be.png` },
    'bj': { 'name': 'Benin', 'path': assetsPath + `/bj.png` },
    'bf': { 'name': 'Burkina Faso', 'path': assetsPath + `/bf.png` },
    'bd': { 'name': 'Bangladesh', 'path': assetsPath + `/bd.png` },
    'bg': { 'name': 'Bulgaria', 'path': assetsPath + `/bg.png` },
    'bh': { 'name': 'Bahrain', 'path': assetsPath + `/bh.png` },
    'bs': { 'name': 'Bahamas', 'path': assetsPath + `/bs.png` },
    'ba': { 'name': 'Bosnia and Herzegovina', 'path': assetsPath + `/ba.png` },
    'by': { 'name': 'Belarus', 'path': assetsPath + `/by.png` },
    'bz': { 'name': 'Belize', 'path': assetsPath + `/bz.png` },
    'bo': { 'name': 'Bolivia', 'path': assetsPath + `/bo.png` },
    'br': { 'name': 'Brazil', 'path': assetsPath + `/br.png` },
    'bb': { 'name': 'Barbados', 'path': assetsPath + `/bb.png` },
    'bn': { 'name': 'Brunei Darussalam', 'path': assetsPath + `/bn.png` },
    'bt': { 'name': 'Bhutan', 'path': assetsPath + `/bt.png` },
    'bw': { 'name': 'Botswana', 'path': assetsPath + `/bw.png` },
    'cf': { 'name': 'Central African Republic', 'path': assetsPath + `/cf.png` },
    'ca': { 'name': 'Canada', 'path': assetsPath + `/ca.png` },
    'ch': { 'name': 'Switzerland', 'path': assetsPath + `/ch.png` },
    'cl': { 'name': 'Chile', 'path': assetsPath + `/cl.png` },
    'cn': { 'name': 'China', 'path': assetsPath + `/cn.png` },
    'ci': { 'name': 'Côte d\'Ivoire', 'path': assetsPath + `/ci.png` },
    'cm': { 'name': 'Cameroon', 'path': assetsPath + `/cm.png` },
    'cd': { 'name': 'Democratic Republic of the Congo', 'path': assetsPath + `/cd.png` },
    'cg': { 'name': 'Republic of the Congo', 'path': assetsPath + `/cg.png` },
    'co': { 'name': 'Colombia', 'path': assetsPath + `/co.png` },
    'km': { 'name': 'Comoros', 'path': assetsPath + `/km.png` },
    'cv': { 'name': 'Cape Verde', 'path': assetsPath + `/cv.png` },
    'cr': { 'name': 'Costa Rica', 'path': assetsPath + `/cr.png` },
    'cu': { 'name': 'Cuba', 'path': assetsPath + `/cu.png` },
    'cy': { 'name': 'Cyprus', 'path': assetsPath + `/cy.png` },
    'cz': { 'name': 'Czech Republic', 'path': assetsPath + `/cz.png` },
    'de': { 'name': 'Germany', 'path': assetsPath + `/de.png` },
    'dj': { 'name': 'Djibouti', 'path': assetsPath + `/dj.png` },
    'dm': { 'name': 'Dominica', 'path': assetsPath + `/dm.png` },
    'dk': { 'name': 'Denmark', 'path': assetsPath + `/dk.png` },
    'do': { 'name': 'Dominican Republic', 'path': assetsPath + `/do.png` },
    'dz': { 'name': 'Algeria', 'path': assetsPath + `/dz.png` },
    'ec': { 'name': 'Ecuador', 'path': assetsPath + `/ec.png` },
    'eg': { 'name': 'Egypt', 'path': assetsPath + `/eg.png` },
    'er': { 'name': 'Eritrea', 'path': assetsPath + `/er.png` },
    'es': { 'name': 'Spain', 'path': assetsPath + `/es.png` },
    'ee': { 'name': 'Estonia', 'path': assetsPath + `/ee.png` },
    'et': { 'name': 'Ethiopia', 'path': assetsPath + `/et.png` },
    'fi': { 'name': 'Finland', 'path': assetsPath + `/fi.png` },
    'fj': { 'name': 'Fiji', 'path': assetsPath + `/fj.png` },
    'fr': { 'name': 'France', 'path': assetsPath + `/fr.png` },
    'fm': { 'name': 'Micronesia (Federated States of)', 'path': assetsPath + `/fm.png` },
    'ga': { 'name': 'Gabon', 'path': assetsPath + `/ga.png` },
    'gb': { 'name': 'United Kingdom', 'path': assetsPath + `/gb.png` },
    'ge': { 'name': 'Georgia', 'path': assetsPath + `/ge.png` },
    'gh': { 'name': 'Ghana', 'path': assetsPath + `/gh.png` },
    'gn': { 'name': 'Guinea', 'path': assetsPath + `/gn.png` },
    'gm': { 'name': 'Gambia', 'path': assetsPath + `/gm.png` },
    'gw': { 'name': 'Guinea-Bissau', 'path': assetsPath + `/gw.png` },
    'gq': { 'name': 'Equatorial Guinea', 'path': assetsPath + `/gq.png` },
    'gr': { 'name': 'Greece', 'path': assetsPath + `/gr.png` },
    'gd': { 'name': 'Grenada', 'path': assetsPath + `/gd.png` },
    'gt': { 'name': 'Guatemala', 'path': assetsPath + `/gt.png` },
    'gy': { 'name': 'Guyana', 'path': assetsPath + `/gy.png` },
    'hn': { 'name': 'Honduras', 'path': assetsPath + `/hn.png` },
    'hr': { 'name': 'Croatia', 'path': assetsPath + `/hr.png` },
    'ht': { 'name': 'Haiti', 'path': assetsPath + `/ht.png` },
    'hu': { 'name': 'Hungary', 'path': assetsPath + `/hu.png` },
    'id': { 'name': 'Indonesia', 'path': assetsPath + `/id.png` },
    'in': { 'name': 'India', 'path': assetsPath + `/in.png` },
    'ie': { 'name': 'Ireland', 'path': assetsPath + `/ie.png` },
    'ir': { 'name': 'Iran (Islamic Republic of)', 'path': assetsPath + `/ir.png` },
    'iq': { 'name': 'Iraq', 'path': assetsPath + `/iq.png` },
    'is': { 'name': 'Iceland', 'path': assetsPath + `/is.png` },
    'il': { 'name': 'Israel', 'path': assetsPath + `/il.png` },
    'it': { 'name': 'Italy', 'path': assetsPath + `/it.png` },
    'jm': { 'name': 'Jamaica', 'path': assetsPath + `/jm.png` },
    'jo': { 'name': 'Jordan', 'path': assetsPath + `/jo.png` },
    'jp': { 'name': 'Japan', 'path': assetsPath + `/jp.png` },
    'kz': { 'name': 'Kazakhstan', 'path': assetsPath + `/kz.png` },
    'ke': { 'name': 'Kenya', 'path': assetsPath + `/ke.png` },
    'kg': { 'name': 'Kyrgyzstan', 'path': assetsPath + `/kg.png` },
    'kh': { 'name': 'Cambodia', 'path': assetsPath + `/kh.png` },
    'ki': { 'name': 'Kiribati', 'path': assetsPath + `/ki.png` },
    'kn': { 'name': 'Saint Kitts and Nevis', 'path': assetsPath + `/kn.png` },
    'kr': { 'name': 'South Korea', 'path': assetsPath + `/kr.png` },
    'kw': { 'name': 'Kuwait', 'path': assetsPath + `/kw.png` },
    'la': { 'name': 'Lao People\'s Democratic Republic', 'path': assetsPath + `/la.png` },
    'lb': { 'name': 'Lebanon', 'path': assetsPath + `/lb.png` },
    'lr': { 'name': 'Liberia', 'path': assetsPath + `/lr.png` },
    'ly': { 'name': 'Libya', 'path': assetsPath + `/ly.png` },
    'lc': { 'name': 'Saint Lucia', 'path': assetsPath + `/lc.png` },
    'li': { 'name': 'Liechtenstein', 'path': assetsPath + `/li.png` },
    'lk': { 'name': 'Sri Lanka', 'path': assetsPath + `/lk.png` },
    'ls': { 'name': 'Lesotho', 'path': assetsPath + `/ls.png` },
    'lt': { 'name': 'Lithuania', 'path': assetsPath + `/lt.png` },
    'lu': { 'name': 'Luxembourg', 'path': assetsPath + `/lu.png` },
    'lv': { 'name': 'Latvia', 'path': assetsPath + `/lv.png` },
    'ma': { 'name': 'Morocco', 'path': assetsPath + `/ma.png` },
    'mc': { 'name': 'Monaco', 'path': assetsPath + `/mc.png` },
    'md': { 'name': 'Moldova', 'path': assetsPath + `/md.png` },
    'mg': { 'name': 'Madagascar', 'path': assetsPath + `/mg.png` },
    'mv': { 'name': 'Maldives', 'path': assetsPath + `/mv.png` },
    'mx': { 'name': 'Mexico', 'path': assetsPath + `/mx.png` },
    'mh': { 'name': 'Marshall Islands', 'path': assetsPath + `/mh.png` },
    'mk': { 'name': 'North Macedonia', 'path': assetsPath + `/mk.png` },
    'ml': { 'name': 'Mali', 'path': assetsPath + `/ml.png` },
    'mt': { 'name': 'Malta', 'path': assetsPath + `/mt.png` },
    'mm': { 'name': 'Myanmar', 'path': assetsPath + `/mm.png` },
    'me': { 'name': 'Montenegro', 'path': assetsPath + `/me.png` },
    'mn': { 'name': 'Mongolia', 'path': assetsPath + `/mn.png` },
    'mz': { 'name': 'Mozambique', 'path': assetsPath + `/mz.png` },
    'mr': { 'name': 'Mauritania', 'path': assetsPath + `/mr.png` },
    'mu': { 'name': 'Mauritius', 'path': assetsPath + `/mu.png` },
    'mw': { 'name': 'Malawi', 'path': assetsPath + `/mw.png` },
    'my': { 'name': 'Malaysia', 'path': assetsPath + `/my.png` },
    'na': { 'name': 'Namibia', 'path': assetsPath + `/na.png` },
    'ne': { 'name': 'Niger', 'path': assetsPath + `/ne.png` },
    'ng': { 'name': 'Nigeria', 'path': assetsPath + `/ng.png` },
    'ni': { 'name': 'Nicaragua', 'path': assetsPath + `/ni.png` },
    'nl': { 'name': 'Netherlands', 'path': assetsPath + `/nl.png` },
    'no': { 'name': 'Norway', 'path': assetsPath + `/no.png` },
    'np': { 'name': 'Nepal', 'path': assetsPath + '/np.png' },
    'nr': { 'name': 'Nauru', 'path': assetsPath + '/nr.png' },
    'nz': { 'name': 'New Zealand', 'path': assetsPath + '/nz.png' },
    'om': { 'name': 'Oman', 'path': assetsPath + '/om.png' },
    'pk': { 'name': 'Pakistan', 'path': assetsPath + '/pk.png' },
    'pa': { 'name': 'Panama', 'path': assetsPath + '/pa.png' },
    'pe': { 'name': 'Peru', 'path': assetsPath + '/pe.png' },
    'ph': { 'name': 'Philippines', 'path': assetsPath + '/ph.png' },
    'pw': { 'name': 'Palau', 'path': assetsPath + '/pw.png' },
    'pg': { 'name': 'Papua New Guinea', 'path': assetsPath + '/pg.png' },
    'pl': { 'name': 'Poland', 'path': assetsPath + '/pl.png' },
    'pf': { 'name': 'French Polynesia', 'path': assetsPath + '/pf.png' },
    'kp': { 'name': 'North Korea', 'path': assetsPath + '/kp.png' },
    'pt': { 'name': 'Portugal', 'path': assetsPath + '/pt.png' },
    'py': { 'name': 'Paraguay', 'path': assetsPath + '/py.png' },
    'qa': { 'name': 'Qatar', 'path': assetsPath + '/qa.png' },
    'ro': { 'name': 'Romania', 'path': assetsPath + '/ro.png' },
    'ru': { 'name': 'Russia', 'path': assetsPath + '/ru.png' },
    'rw': { 'name': 'Rwanda', 'path': assetsPath + '/rw.png' },
    'sa': { 'name': 'Saudi Arabia', 'path': assetsPath + '/sa.png' },
    'sd': { 'name': 'Sudan', 'path': assetsPath + '/sd.png' },
    'sn': { 'name': 'Senegal', 'path': assetsPath + '/sn.png' },
    'sg': { 'name': 'Singapore', 'path': assetsPath + '/sg.png' },
    'sb': { 'name': 'Solomon Islands', 'path': assetsPath + '/sb.png' },
    'sl': { 'name': 'Sierra Leone', 'path': assetsPath + '/sl.png' },
    'sv': { 'name': 'El Salvador', 'path': assetsPath + '/sv.png' },
    'sm': { 'name': 'San Marino', 'path': assetsPath + '/sm.png' },
    'so': { 'name': 'Somalia', 'path': assetsPath + '/so.png' },
    'rs': { 'name': 'Serbia', 'path': assetsPath + '/rs.png' },
    'ss': { 'name': 'South Sudan', 'path': assetsPath + '/ss.png' },
    'st': { 'name': 'Sao Tome and Principe', 'path': assetsPath + '/st.png' },
    'sr': { 'name': 'Suriname', 'path': assetsPath + '/sr.png' },
    'sk': { 'name': 'Slovakia', 'path': assetsPath + '/sk.png' },
    'si': { 'name': 'Slovenia', 'path': assetsPath + '/si.png' },
    'se': { 'name': 'Sweden', 'path': assetsPath + '/se.png' },
    'sz': { 'name': 'Eswatini', 'path': assetsPath + '/sz.png' },
    'sc': { 'name': 'Seychelles', 'path': assetsPath + '/sc.png' },
    'sy': { 'name': 'Syria', 'path': assetsPath + '/sy.png' },
    'td': { 'name': 'Chad', 'path': assetsPath + '/td.png' },
    'tg': { 'name': 'Togo', 'path': assetsPath + '/tg.png' },
    'th': { 'name': 'Thailand', 'path': assetsPath + '/th.png' },
    'tj': { 'name': 'Tajikistan', 'path': assetsPath + '/tj.png' },
    'tm': { 'name': 'Turkmenistan', 'path': assetsPath + '/tm.png' },
    'tl': { 'name': 'Timor-Leste', 'path': assetsPath + '/tl.png' },
    'to': { 'name': 'Tonga', 'path': assetsPath + '/to.png' },
    'tt': { 'name': 'Trinidad and Tobago', 'path': assetsPath + '/tt.png' },
    'tn': { 'name': 'Tunisia', 'path': assetsPath + '/tn.png' },
    'tr': { 'name': 'Turkey', 'path': assetsPath + '/tr.png' },
    'tv': { 'name': 'Tuvalu', 'path': assetsPath + '/tv.png' },
    'tz': { 'name': 'Tanzania', 'path': assetsPath + '/tz.png' },
    'ug': { 'name': 'Uganda', 'path': assetsPath + '/ug.png' },
    'ua': { 'name': 'Ukraine', 'path': assetsPath + '/ua.png' },
    'uy': { 'name': 'Uruguay', 'path': assetsPath + '/uy.png' },
    'us': { 'name': 'United States', 'path': assetsPath + '/us.png' },
    'uz': { 'name': 'Uzbekistan', 'path': assetsPath + '/uz.png' },
    'va': { 'name': 'Vatican City', 'path': assetsPath + '/va.png' },
    'vc': { 'name': 'Saint Vincent and the Grenadines', 'path': assetsPath + '/vc.png' },
    've': { 'name': 'Venezuela', 'path': assetsPath + '/ve.png' },
    'vn': { 'name': 'Vietnam', 'path': assetsPath + '/vn.png' },
    'vu': { 'name': 'Vanuatu', 'path': assetsPath + '/vu.png' },
    'ws': { 'name': 'Samoa', 'path': assetsPath + '/ws.png' },
    'ye': { 'name': 'Yemen', 'path': assetsPath + '/ye.png' },
    'za': { 'name': 'South Africa', 'path': assetsPath + '/za.png' },
    'zm': { 'name': 'Zambia', 'path': assetsPath + '/zm.png' },
    'zw': { 'name': 'Zimbabwe', 'path': assetsPath + '/zw.png' },
};