export class PhraseGenerator {
  // An whimsical list of adjectives
  private static adjectives: string[] = [
    'Bouncing',
    'Whimsical',
    'Giggling',
    'Sparkling',
    'Mysterious',
    'Fuzzy',
    'Enchanted',
    'Wobbly',
    'Cosmic',
    'Jazzy',
    'Quirky',
    'Silly',
    'Daring',
    'Ephemeral',
    'Luminous',
    'Ponderous',
    'Serendipitous',
    'Vibrant',
    'Witty',
    'Zany',
    'Absurd',
    'Bewildering',
    'Charming',
    'Dazzling',
    'Eccentric',
    'Fantastic',
    'Glorious',
    'Haphazard',
    'Idyllic',
    'Jubilant',
    'Kaleidoscopic',
    'Labyrinthine',
    'Magnificent',
    'Nebulous',
    'Opulent',
    'Peculiar',
    'Quixotic',
    'Resplendent',
    'Surreal',
    'Tremendous',
    'Ubiquitous',
    'Vivacious',
    'Wondrous',
    'Xenodochial',
    'Yielding',
    'Zealous',
    'Agile',
    'Blissful',
    'Captivating',
    'Dreamy',
    'Ethereal',
    'Flippant',
    'Grandiose',
    'Harmonious',
    'Incandescent',
    'Jocund',
    'Kinetic',
    'Lyrical',
    'Mirthful',
    'Nefarious',
    'Optimistic',
    'Perplexing',
    'Quintessential',
    'Rambunctious',
    'Scintillating',
    'Translucent',
    'Unfathomable',
    'Voluminous',
    'Wholesome',
    'Xenial',
    'Yearning',
    'Zestful',
    'Ephemeral',
    'Iridescent',
    'Mellifluous',
    'Numinous',
    'Panacea',
    'Quiescent',
    'Resplendent',
    'Sempiternal',
    'Tintinnabulation',
    'Utopia',
    'Verdant',
    'Wafting',
    'Xanadu',
    'Yonder',
    'Zenith',
  ];

  // An interesting list of nouns (often fantastical or quirky)
  private static nouns: string[] = [
    'Unicorn',
    'Robot',
    'Dragon',
    'Penguin',
    'Galaxy',
    'Whisper',
    'Gizmo',
    'Pancake',
    'Zeppelin',
    'Spoon',
    'Muffin',
    'Comet',
    'Pixel',
    'Goblin',
    'Waffle',
    'Octopus',
    'Squid',
    'Chalice',
    'Phoenix',
    'Gargoyle',
    'Jester',
    'Lantern',
    'Nimbus',
    'Orchid',
    'Quasar',
    'Riddle',
    'Sphinx',
    'Tesseract',
    'Umbra',
    'Vortex',
    'Wisp',
    'Xylophone',
    'Yeti',
    'Ziggurat',
    'Astronaut',
    'Bumblebee',
    'Chameleon',
    'Dandelion',
    'Echo',
    'Firefly',
    'Glimmer',
    'Hologram',
    'Illusion',
    'Jubilee',
    'Krypton',
    'Labyrinth',
    'Mirage',
    'Nightingale',
    'Oasis',
    'Paragon',
    'Quiver',
    'Rhapsody',
    'Silhouette',
    'Talisman',
    'Utopia',
    'Vagabond',
    'Wanderer',
    'Xenon',
    'Yggdrasil',
    'Zephyr',
    'Alchemist',
    'Bard',
    'Centaur',
    'Druid',
    'Elf',
    'Fairy',
    'Griffin',
    'Harpy',
    'Imp',
    'Jinn',
    'Kraken',
    'Leprechaun',
    'Mage',
    'Nymph',
    'Ogre',
    'Pixie',
    'Quest',
    'Rogue',
    'Sorcerer',
    'Troll',
    'Vampire',
    'Werewolf',
    'Wraith',
    'Zombie',
  ];

  // A list of "descriptors" to add more flavor and uniqueness to the phrase
  private static descriptors: string[] = [
    'of Destiny',
    'that Sings',
    'of Wonder',
    'in the Stars',
    'of Pure Joy',
    'that Dances',
    'from Beyond',
    'of the Abyss',
    'with a Crown',
    'that Giggles',
    'of the Cosmos',
    'on the Edge',
    'of Forgotten Dreams',
    'that Shimmers',
    'of the Ancient Lore',
    'with a Secret',
    'of Eternal Bloom',
    'that Whispers',
    'of the Silent Sea',
    'under the Moonlight',
    'of the Golden Age',
    'that Sparkles',
    'of Infinite Possibilities',
    'with a Quirk',
    'of the Velvet Sky',
    'that Dreams',
    'of the Crystal Caves',
    'beyond the Veil',
    'of the Whispering Woods',
    'that Soars',
    'of the Sunken City',
    'through the Mists',
    'of the Hidden Path',
    'that Twinkles',
    'of the Emerald Isle',
    'with a Song',
    'of the Shifting Sands',
    'that Blooms',
    'of the Obsidian Spire',
    'in the Labyrinth',
    'of the Radiant Dawn',
    'that Glitters',
    'of the Twilight Realm',
  ];

  /**
   * Generates a unique, funny, and memorable phrase for use in "magic URLs".
   * The phrase combines a random adjective, a random noun, and a random descriptor,
   * followed by a short random alphanumeric suffix for enhanced uniqueness and collision avoidance.
   *
   * @returns {string} A generated phrase, e.g., "Whimsical Unicorn of Destiny-a1b2".
   */
  public static generate(): string {
    const adjective =
      this.adjectives[Math.floor(Math.random() * this.adjectives.length)];
    const noun = this.nouns[Math.floor(Math.random() * this.nouns.length)];
    const descriptor =
      this.descriptors[Math.floor(Math.random() * this.descriptors.length)];

    // Generate a short random alphanumeric suffix (e.g., "a1b2")
    // This significantly increases the number of possible unique phrases and helps prevent collisions.
    const randomSuffix = Math.random().toString(36).substring(2, 6); // Gets 4 random alphanumeric characters
    const phrase = `${adjective} ${noun} ${descriptor}-${randomSuffix}`;

    return phrase;
  }
}
