import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger'
import { type OAuthProviders, oAuthProvidersList } from '@nuvix/core/config'
import { ArrayToLastElement, IsUID } from '@nuvix/core/validators'
import { configuration } from '@nuvix/utils'
import { Expose } from 'class-transformer'
import {
  ArrayMaxSize,
  IsArray,
  IsEmail,
  IsIn,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUrl,
  Length,
  MaxLength,
  MinLength,
} from 'class-validator'

export class CreateEmailSessionDTO {
  /**
   * User email.
   */
  @IsEmail()
  declare email: string

  /**
   * User password. Must be at least 8 chars.
   */
  @MinLength(8)
  declare password: string
}

export class CreateSessionDTO {
  /**
   * User ID. Choose a custom ID or generate a random ID with `ID.unique()`. Valid chars are a-z, A-Z, 0-9, period, hyphen, and underscore. Can\'t start with a special char. Max length is 36 chars.
   */
  @IsUID()
  declare userId: string

  /**
   * Secret of a token generated by login methods. For example, the `createMagicURLToken` or `createPhoneToken` methods.
   */
  @IsString()
  @Length(200, 256)
  declare secret: string
}

export class CreateOAuth2SessionDTO {
  /**
   * URL to redirect back to your app after a successful login attempt.  Only URLs from hostnames in your project\'s platform list are allowed. This requirement helps to prevent an [open redirect](https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html) attack against your project API.
   */
  @IsOptional()
  @ArrayToLastElement()
  @IsUrl()
  success?: string

  /**
   * URL to redirect back to your app after a failed login attempt.  Only URLs from hostnames in your project\'s platform list are allowed. This requirement helps to prevent an [open redirect](https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html) attack against your project API.
   */
  @IsOptional()
  @ArrayToLastElement()
  @IsUrl()
  failure?: string

  @ApiPropertyOptional({
    description: `A list of custom OAuth2 scopes. Check each provider internal docs for a list of supported scopes. Maximum of ${configuration.limits.arrayParamsSize} scopes are allowed, each ${configuration.limits.arrayElementSize} characters long.`,
    isArray: true,
    type: () => String,
  })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  @MaxLength(configuration.limits.arrayElementSize, { each: true })
  @ArrayMaxSize(configuration.limits.arrayParamsSize)
  scopes?: string[] = []
}

@Expose()
export class OAuth2CallbackDTO {
  /**
   *  OAuth2 code. This is a temporary code that the will be later exchanged for an access token.
   */
  @IsOptional()
  @ArrayToLastElement()
  @IsString()
  @MaxLength(2048)
  code?: string

  /**
   * Login state params.
   */
  @IsOptional()
  @ArrayToLastElement()
  @IsString()
  @MaxLength(2048)
  state?: string

  /**
   * Error code returned from the OAuth2 provider.
   */
  @IsOptional()
  @ArrayToLastElement()
  @IsString()
  @MaxLength(2048)
  error?: string

  /**
   * Human-readable text providing additional information about the error returned from the OAuth2 provider.
   */
  @IsOptional()
  @ArrayToLastElement()
  @IsString()
  @MaxLength(2048)
  error_description?: string
}

// Params
export class ProviderParamDTO {
  @ApiProperty({
    description: `OAuth2 Provider.Currently, supported providers are: ${oAuthProvidersList.join(', ')}`,
  })
  @IsString()
  @IsIn(oAuthProvidersList)
  declare provider: OAuthProviders
}

export class SessionsParamDTO {
  /**
   * Session ID. Use the string \'current\' to refer current device session.
   */
  @IsNotEmpty()
  @IsUID()
  declare sessionId: string
}

export class OAuth2CallbackParamDTO {
  /**
   * Project ID.
   */
  @IsUID()
  declare projectId: string

  @ApiProperty({
    description: `OAuth2 Provider.Currently, supported providers are: ${oAuthProvidersList.join(', ')}`,
  })
  @IsString()
  @IsIn(oAuthProvidersList)
  declare provider: OAuthProviders
}
